const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM,VirtualConsole}=require('jsdom');const base=path.resolve(__dirname,'../..'),pause=()=>new Promise(r=>setTimeout(r,20));
function page(role='student'){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(base+'/interactive-lesson/index.html','utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://example.test/interactive-lesson/?assignmentId=assignment-1',runScripts:'outside-only',virtualConsole:vc});const w=dom.window,calls=[];
 const record={id:'assignment-1',title:'Lesson',status:'active',revision:1,answers:{a:'saved'},currentActivityId:'a',route:'core',lesson:{activities:[{id:'a',title:'Question',prompt:'Tell us',response:{schemaVersion:1,mode:'short_text',required:true}}]}};
 let authCallback,conflict=false;const user={uid:role,getIdToken:async()=>role};const auth={currentUser:user,onAuthStateChanged:fn=>{authCallback=fn;fn(user);}};w.firebase={apps:[{}],auth:()=>auth};w.confirm=()=>true;
 w.fetch=async(url,options)=>{const body=JSON.parse(options.body);calls.push(body);let result,status=200;
 if(body.action==='list')result={role,assignments:[]};else if(body.action==='get')result=record;
 else if(body.action==='save'||body.action==='submit'){if(conflict){status=409;result={error:'Conflict'};}else{record.answers=body.answers;record.revision++;if(body.action==='submit')record.status='submitted';result={revision:record.revision};}}
 else if(body.action==='review'){record.status='reviewed';record.feedback=body.feedback;record.revision++;result={revision:record.revision};}
 return{ok:status===200,status,json:async()=>JSON.parse(JSON.stringify(result))};};
 for(const f of ['/interactive-response-view.js','/interactive-lesson/app.js'])vm.runInContext(fs.readFileSync(base+f,'utf8'),dom.getInternalVMContext(),{filename:f});
 return{dom,w,errors,calls,record,$:id=>w.document.getElementById(id),conflict:()=>conflict=true,signout:()=>{auth.currentUser=null;authCallback(null);}};
}
test('student edits saves resumes and submits; no teacher-only content',async()=>{const p=page();try{await pause();let input=p.$('response').querySelector('input');assert.equal(input.value,'saved');input.value='my answer';input.dispatchEvent(new p.w.Event('input'));assert.equal(p.w.localStorage.length,1);p.$('save').click();await pause();assert.equal(p.record.answers.a,'my answer');assert.equal(p.w.localStorage.length,0);assert.ok(p.$('teacher-guide').hidden);p.$('submit').click();await pause();assert.equal(p.record.status,'submitted');assert.ok(p.$('save').hidden);assert.equal(p.$('review-answer').textContent,'my answer');assert.deepEqual(p.errors,[]);}finally{p.dom.window.close();}});
test('409 keeps local answers; signout removes displayed student content',async()=>{const p=page();try{await pause();const input=p.$('response').querySelector('input');input.value='unsaved';input.dispatchEvent(new p.w.Event('input'));p.conflict();p.$('save').click();await pause();assert.equal(p.$('response').querySelector('input').value,'unsaved');assert.equal(p.w.localStorage.length,1);assert.match(p.$('status').textContent,/teine versioon/);p.signout();assert.ok(p.$('lesson').hidden);assert.deepEqual(p.errors,[]);}finally{p.dom.window.close();}});
test('teacher can review a submitted response without editing student answers',async()=>{const p=page('teacher');try{p.record.status='submitted';await pause();assert.ok(p.$('save').hidden);assert.equal(p.$('review').hidden,false);p.$('review-text').value='Well done';p.$('review-save').click();await pause();assert.equal(p.record.feedback,'Well done');assert.equal(p.record.status,'reviewed');assert.equal(p.record.answers.a,'saved');assert.deepEqual(p.errors,[]);}finally{p.dom.window.close();}});
