const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM,VirtualConsole}=require('jsdom');
const base=path.resolve(__dirname,'../..'),core=require(base+'/lesson-authoring-core'),ux=require(base+'/lesson-builder-ux-core');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
function fixture(){let n=0;return ux.lessonTemplate('language60','draft-dom',()=>`act-${n++}`);}
function page(file,query='',draft){
 const html=fs.readFileSync(path.join(base,file),'utf8'),errors=[],requests=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(html.replace(/<script[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://example.test/'+file.replace('index.html','')+query,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
 const w=dom.window;w.firebase={apps:[{}],auth:()=>({currentUser:{getIdToken(){requests.push('token');throw Error('unexpected token');}}})};w.fetch=url=>{requests.push(url);throw Error('unexpected API');};
 w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
 if(draft){w.localStorage.setItem('keelesepp.lesson-authoring.v1',core.serialize(draft));w.sessionStorage.setItem('keelesepp.authoring-preview.aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',core.serialize(draft));}
 for(const match of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)){const src=/src="([^"]+)"/.exec(match[1])?.[1];if(src?.startsWith('https:'))continue;vm.runInContext(src?fs.readFileSync(base+src,'utf8'):match[2],dom.getInternalVMContext(),{filename:src||file});}
 const $=id=>w.document.getElementById(id),click=id=>$(id).click(),input=(id,value,event='input')=>{$(id).value=value;$(id).dispatchEvent(new w.Event(event,{bubbles:true}));};
 return {dom,w,$,click,input,errors,requests,close:()=>dom.window.close()};
}
test('onboarding creates a lesson from a template and hides technical fields',()=>{const p=page('haldus-lesson-builder/index.html');try{p.click('lesson-templates');p.w.document.querySelector('[data-template="language60"]').click();assert.equal(p.$('total').textContent,'7');assert.equal(p.$('activity-id'),null);p.click('activity-menu');p.click('technical');assert.equal(p.$('activity-id').readOnly,true);assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('DnD handle and keyboard reorder save reload and preview keep IDs/content',async()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{const w=p.w,id=fixture().activities[0].id;const handle=w.document.querySelector('[data-drag="'+id+'"]'),target=w.document.querySelector('[data-before="act-5"].activity-row');handle.setPointerCapture=()=>{};w.document.elementFromPoint=()=>target;function pointer(type,x){handle.dispatchEvent(new w.MouseEvent(type,{bubbles:true,cancelable:true,button:0,clientX:x,clientY:100}));}pointer('pointerdown',10);pointer('pointermove',100);assert.ok(w.document.querySelector('.drop-before'));pointer('pointerup',100);assert.equal(w.document.querySelectorAll('.activity-row')[4].dataset.activity,id);w.document.querySelector('[data-drag="'+id+'"]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowUp',altKey:true,bubbles:true,cancelable:true}));p.click('save');const saved=core.parse(w.localStorage.getItem('keelesepp.lesson-authoring.v1'));assert.equal(saved.activities[3].id,id);assert.deepEqual(saved.activities[3].routes,fixture().activities[0].routes);const again=page('haldus-lesson-builder/index.html','',saved);try{assert.equal(again.w.document.querySelectorAll('.activity-row')[3].dataset.activity,id);await pause(520);const token=new URL(again.$('preview-frame').src).searchParams.get('authoringPreview');const snapshot=core.parse(again.w.sessionStorage.getItem('keelesepp.authoring-preview.'+token));assert.deepEqual(snapshot.activities,saved.activities);}finally{again.close();}}finally{p.close();}});
test('duplicate delete confirmation undo and redo work through actual UI',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.click('activity-menu');p.click('duplicate');assert.equal(p.$('total').textContent,'8');p.click('activity-menu');p.click('delete');assert.equal(p.$('total').textContent,'8');p.click('confirm-action');assert.equal(p.$('total').textContent,'7');p.click('undo');assert.equal(p.$('total').textContent,'8');p.click('redo');assert.equal(p.$('total').textContent,'7');assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('route editing and autosave retain every variant after reload',async()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{for(const route of ['support','core','advanced']){p.w.document.querySelector('[data-route="'+route+'"]').click();p.input('prompt','Edited '+route);}await pause(820);assert.match(p.$('save-state').textContent,/Salvestatud/);const d=core.parse(p.w.localStorage.getItem('keelesepp.lesson-authoring.v1'));for(const r of core.ROUTES)assert.equal(d.activities[0].routes[r].prompt,'Edited '+r);const next=page('haldus-lesson-builder/index.html','',d);assert.equal(next.$('prompt').value,'Edited core');next.close();}finally{p.close();}});
test('blank prompt renders inline error and invalid draft cannot preview or overwrite storage',async()=>{const d=fixture(),p=page('haldus-lesson-builder/index.html','',d);try{p.input('prompt','');assert.match(p.$('error-prompt').textContent,/Lisa/);p.click('save');await pause(520);assert.equal(p.$('preview-frame').getAttribute('src'),null);assert.deepEqual(core.parse(p.w.localStorage.getItem('keelesepp.lesson-authoring.v1')),d);}finally{p.close();}});
test('malformed JSON import fails safely and valid import/export roundtrips',async()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{const original=p.w.localStorage.getItem('keelesepp.lesson-authoring.v1');async function imported(text){Object.defineProperty(p.$('import'),'files',{configurable:true,value:[{size:text.length,text:async()=>text}]});p.$('import').dispatchEvent(new p.w.Event('change'));await pause(5);}await imported('{bad');assert.match(p.$('notice').textContent,/Import ebaõnnestus/);assert.equal(p.w.localStorage.getItem('keelesepp.lesson-authoring.v1'),original);let blob;p.w.Blob=Blob;p.w.URL.createObjectURL=b=>(blob=b,'blob:test');p.w.URL.revokeObjectURL=()=>{};p.w.HTMLAnchorElement.prototype.click=()=>{};p.click('more');p.click('export');const exported=await blob.text();assert.deepEqual(core.parse(exported),fixture());await imported(exported);p.click('confirm-action');assert.equal(p.$('total').textContent,'7');}finally{p.close();}});
test('all preview views/routes ignore supplied studentId and perform zero persistent API calls',async()=>{for(const view of ['student','teacher'])for(const route of core.ROUTES){const p=page('haldus-adaptive-lesson/index.html','?authoringPreview=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&studentId=DO-NOT-PERSIST&activity=act-2&route='+route+'&view='+view,fixture());try{await pause(5);assert.equal(p.$('session-status').textContent,'Preview');assert.equal(p.$('focus-title').textContent,fixture().activities[2].title);assert.ok(p.$('workspace').textContent.includes(route==='support'?'märksõnu':route==='advanced'?'põhjendus':'Ma'));p.w.document.querySelector('[data-judge="easy"]').click();await pause(5);p.click('next');p.click('finish');p.click('handoff-btn');await pause(5);assert.deepEqual(p.requests,[]);assert.deepEqual(p.errors,[]);}finally{p.close();}}});
test('unknown preview token fails closed with no fallback or API',()=>{const p=page('haldus-adaptive-lesson/index.html','?authoringPreview=bad&studentId=DO-NOT-PERSIST');try{assert.match(p.w.document.body.textContent,/Tundi ei saa avada/);assert.equal(p.$('workspace'),null);assert.deepEqual(p.requests,[]);}finally{p.close();}});
test('authored HTML remains escaped in editor and preview',()=>{const d=fixture();d.title='<img src=x onerror=alert(1)>';d.activities[0].routes.core.prompt='<script>alert(1)</script>\n<img src=x>';for(const file of ['haldus-lesson-builder/index.html','haldus-adaptive-lesson/index.html']){const p=page(file,file.includes('adaptive')?'?authoringPreview=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&view=student':'',d);try{assert.equal(p.w.document.querySelector('img[src=x]'),null);assert.deepEqual(p.errors,[]);}finally{p.close();}}});
test('preview device/fullscreen and structure drawers have reversible DOM state',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.click('show-structure');assert.ok(p.w.document.body.classList.contains('structure-open'));p.click('close-structure');assert.ok(!p.w.document.body.classList.contains('structure-open'));p.click('fullscreen');assert.ok(p.w.document.body.classList.contains('preview-fullscreen'));p.w.document.querySelector('[data-device="mobile"]').click();assert.equal(p.w.document.querySelector('[data-device="mobile"]').getAttribute('aria-pressed'),'true');p.w.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Escape'}));assert.ok(!p.w.document.body.classList.contains('preview-fullscreen'));}finally{p.close();}});
test('each card menu targets that activity and duplication preserves its content',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{const target=fixture().activities[3];p.w.document.querySelector('[data-card-menu="'+target.id+'"]').click();p.click('duplicate');p.click('save');const saved=core.parse(p.w.localStorage.getItem('keelesepp.lesson-authoring.v1'));assert.notEqual(saved.activities[4].id,target.id);assert.deepEqual(saved.activities[4].routes,target.routes);assert.equal(p.$('total').textContent,'8');assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('cloud UI save reopen publish history and stale conflict keep local recovery',async()=>{
 const p=page('haldus-lesson-builder/index.html','',fixture());try{
 let record=null,published=0,conflict=false;const calls=[];
 const auth={currentUser:{uid:'teacher-ui',getIdToken:async()=> 'test-token'},authStateReady:async()=>{}};p.w.firebase.auth=()=>auth;
 p.w.fetch=async(url,options)=>{const b=JSON.parse(options.body);calls.push(b);let result={};if(conflict&&b.action==='save')return {ok:false,status:409,json:async()=>({error:'Revision conflict'})};
 if(b.action==='create'){record={id:'draft-server',revision:1,lessonId:'lesson-server',content:{...b.content,id:'draft-server'}};result={draft:record};}
 if(b.action==='save'){assert.equal(b.revision,record.revision);record={...record,revision:record.revision+1,content:b.content};result={id:record.id,revision:record.revision};}
 if(b.action==='get')result={draft:record};
 if(b.action==='list')result={drafts:[{...record,title:record.content.title,status:'active',versionNumber:published}]};
 if(b.action==='publish'){published++;record.revision++;result={id:record.id,revision:record.revision,publication:{versionNumber:published}};}
 if(b.action==='history')result={versions:[{id:'lesson-server_v1',versionNumber:1,createdAt:'today'}]};
 return {ok:true,status:200,json:async()=>JSON.parse(JSON.stringify(result))};};
 assert.deepEqual(calls,[]);p.click('cloud-save');await pause(20);assert.equal(p.w.KeeleSeppBuilderBridge.get().id,'draft-server');assert.equal(record.revision,1);
 p.input('lesson-title','Edited');p.click('cloud-save');await pause(20);assert.equal(record.revision,2);
 p.click('cloud-library');await pause(20);p.w.document.querySelector('[data-cloud-open]').click();p.click('confirm-action');await pause(20);assert.equal(p.$('lesson-title').value,'Edited');
 p.click('cloud-more');p.click('cloud-publish');p.click('confirm-action');await pause(20);assert.equal(published,1);
 p.click('cloud-more');p.click('cloud-history');await pause(20);assert.ok(p.w.document.querySelector('[data-version]'));p.click('modal-close');
 conflict=true;p.input('lesson-title','Unsaved conflict work');p.click('cloud-save');await pause(20);assert.match(p.$('cloud-status').textContent,/Konflikt/);assert.equal(p.$('lesson-title').value,'Unsaved conflict work');assert.equal(record.content.title,'Edited');
 assert.equal(JSON.parse(p.w.localStorage.getItem('keelesepp.cloud-bindings.v1'))['draft-server'].revision,3);assert.deepEqual(p.errors,[]);
 }finally{p.close();}
});
test('cloud signed out denial leaves local draft intact and makes no request',async()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.w.firebase.auth=()=>({currentUser:null,authStateReady:async()=>{}});p.click('cloud-save');await pause(20);assert.match(p.$('cloud-status').textContent,/Logi/);assert.equal(p.$('total').textContent,'7');assert.deepEqual(p.requests,[]);}finally{p.close();}});
test('fillable block editor keeps option IDs through labels/routes/undo and preview never calls API',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.input('response-mode','single_choice','change');const get=()=>p.w.KeeleSeppBuilderBridge.get().activities[0];const id=get().id,choice=get().evaluation.response.items[0].id;const field=p.w.document.querySelector('[aria-label="Valik 1"]');field.value='Õige tekst';field.dispatchEvent(new p.w.Event('change'));assert.equal(get().evaluation.response.items[0].id,choice);p.w.document.querySelector('[data-route="support"]').click();assert.equal(get().id,id);assert.equal(get().evaluation.response.items[0].id,choice);p.w.document.querySelector('#response-try input').click();assert.equal(get().evaluation.response.items[0].label,'Õige tekst');assert.deepEqual(p.requests,[]);p.click('undo');assert.equal(get().evaluation.response.items[0].label,'Esimene');assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('sticky Lesson Mode preview exposes fillable response without persistence',()=>{const d=fixture();d.activities[0].responseMode='short_text';d.activities[0].evaluation={response:{schemaVersion:1,mode:'short_text',required:true}};const p=page('haldus-adaptive-lesson/index.html','?authoringPreview=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&studentId=forged',d);try{const input=p.w.document.querySelector('.interactive-preview-response input');assert.ok(input);input.value='preview answer';input.dispatchEvent(new p.w.Event('input'));assert.deepEqual(p.requests,[]);assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('fillable template library creates a ready response with stable choice IDs and zero API calls',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.click('add');assert.match(p.$('template-grid').textContent,/Täidetavad ülesanded/);const card=p.w.document.querySelector('[data-template="interactive-single"]');assert.match(card.textContent,/Täidetav/);card.click();const a=p.w.KeeleSeppBuilderBridge.get().activities[1];assert.equal(a.responseMode,'single_choice');assert.deepEqual(Array.from(a.evaluation.response.items,i=>i.id),['choice-a','choice-b','choice-c']);assert.match(p.w.document.querySelector('[data-activity="'+a.id+'"] small').textContent,/Täidetav/);assert.ok(p.$('response-try').querySelector('input[type="radio"]'));assert.deepEqual(p.requests,[]);assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('fillable worksheet template creates five immediately editable student response blocks',()=>{const p=page('haldus-lesson-builder/index.html');try{p.click('lesson-templates');const card=p.w.document.querySelector('[data-template="worksheet"]');assert.match(card.textContent,/5 plokki/);card.click();const d=p.w.KeeleSeppBuilderBridge.get();assert.equal(d.activities.length,5);assert.deepEqual(Array.from(d.activities,a=>a.responseMode),['short_text','single_choice','multiple_choice','gaps','long_text']);assert.ok(d.activities.every(a=>a.evaluation.response.required));assert.equal(new Set(d.activities.map(a=>a.id)).size,5);assert.deepEqual(p.requests,[]);assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('quick worksheet composer creates mixed fillable blocks as one undoable action',()=>{const p=page('haldus-lesson-builder/index.html');try{p.click('quick-worksheet');p.input('composer-lines','Kes sa oled?\nsingle: Vali vastus | Jah | Ei\ngaps: Täida lause | Esimene | Teine');p.click('composer-create');let d=p.w.KeeleSeppBuilderBridge.get();assert.equal(d.activities.length,3);assert.deepEqual(Array.from(d.activities,a=>a.responseMode),['short_text','single_choice','gaps']);assert.deepEqual(Array.from(d.activities[1].evaluation.response.items,i=>i.label),['Jah','Ei']);assert.match(p.$('response-try').textContent,/Sinu vastus/);assert.deepEqual(p.requests,[]);p.click('undo');d=p.w.KeeleSeppBuilderBridge.get();assert.equal(d.activities.length,0);assert.deepEqual(p.errors,[]);}finally{p.close();}});
test('quick worksheet composer shows inline syntax error without changing lesson',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.click('quick-worksheet');p.input('composer-lines','single: Küsimus | ainult üks');p.click('composer-create');assert.match(p.$('error-composer-lines').textContent,/vähemalt kaks/);assert.equal(p.w.KeeleSeppBuilderBridge.get().activities.length,7);assert.deepEqual(p.requests,[]);}finally{p.close();}});
test('image block keeps its stable ID through edits, Lesson Mode preview and undo',()=>{const p=page('haldus-lesson-builder/index.html','',fixture());try{p.click('add-image');let a=p.w.KeeleSeppBuilderBridge.get().activities[0],asset=a.assets[0],id=asset.id;assert.match(id,/^asset-/);p.input('image-url','https://example.com/classroom.jpg','change');p.input('image-alt','Õpilased klassiruumis','change');p.input('image-caption','Arutage pilti paaris.','change');const draft=p.w.KeeleSeppBuilderBridge.get();a=draft.activities[0];assert.equal(a.assets[0].id,id);assert.equal(a.assets[0].url,'https://example.com/classroom.jpg');assert.equal(p.$('asset-editor').querySelector('img').alt,'Õpilased klassiruumis');const preview=page('haldus-adaptive-lesson/index.html','?authoringPreview=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&view=student',draft);try{assert.equal(preview.w.document.querySelector('.lesson-assets img').alt,'Õpilased klassiruumis');assert.match(preview.w.document.querySelector('.lesson-assets figcaption').textContent,/Arutage/);assert.deepEqual(preview.requests,[]);assert.deepEqual(preview.errors,[]);}finally{preview.close();}assert.deepEqual(p.requests,[]);p.click('undo');assert.equal(p.w.KeeleSeppBuilderBridge.get().activities[0].assets[0].caption,undefined);assert.deepEqual(p.errors,[]);}finally{p.close();}});
