// B1 course (A2 → B1 roadmap), module 7 „Tervis ja enesetunne” (a2b1-031…035), stage A2+.
// Harjuta + Kasuta for the published Avasta sheets, each a whole lesson (40–55 min). Everyday health without medical
// overload (roadmap): booking an appointment, describing a symptom, understanding and giving simple advice. The
// imperative and „peaks / võiks” come back in every lesson; module 6 food words return in healthy habits.
// Material also from the KeeleSepp A2→B1 workbook, lessons 26–29 (Tervis ja enesetunne; Arsti juures).
import { B } from '../blocks.js';

export const MODULE = { id: 'a2b1-module-07', course: 'b1', title: 'Tervis ja enesetunne', level: 'A2+' };

const W = (id, title, instruction, keywords) => B.writing(id, title, instruction, [8, 10], keywords, 3);
const TR = (id, rows) => B.translation(id, 'Tõlgi.', 'Kirjuta eesti keeles.', rows);
const D = (id, rows) => B.dictation(id, 'Etteütlus.', 'Kuula ja kirjuta laused.', rows);

export const LESSONS = {
  'a2b1-031': {
    title: 'Keha ja sümptomid',
    canDo: 'Ma kirjeldan vähemalt kuut sümptomit ja kasutan õigeid konstruktsioone.',
    practice: [
      B.match('031_p_body', 'Keha osad.', 'Ühenda eesti sõna ja vene tõlge.', [['pea', 'голова'], ['kurk', 'горло'], ['kõht', 'живот'], ['selg', 'спина'], ['hammas', 'зуб'], ['põlv', 'колено'], ['silm', 'глаз']], 'half'),
      B.categorize('031_p_sort', 'Valutab või on?', 'Sorteeri: mul valutab … / mul on …', [['Mul valutab', ['pea', 'kurk', 'kõht', 'selg', 'hammas']], ['Mul on', ['nohu', 'köha', 'palavik', 'pearinglus']]]),
      B.gaps('031_p_con', 'Kolm konstruktsiooni.', 'Täida lüngad.', ['[Mul valutab] pea juba kaks päeva.', '[Mul on] kõrge palavik.', 'Ma [tunnen] end väga väsinuna.', 'Lapsel [valutab] kõht.', 'Kas [sul on] köha?', 'Ta [tunneb] end täna paremini.'], ['mul valutab', 'mul on', 'tunnen', 'valutab', 'sul on', 'tunneb']),
      B.reading('031_p_read', 'Loe: halb hommik.', 'Loe tekst ja vasta küsimustele.', 'Margiti halb hommik',
        'Esmaspäeva hommikul ärkas Margit ja tundis kohe, et midagi on valesti. Tal valutas pea ja kurk oli kare. Kui ta püsti tõusis, hakkas pea ringi käima. Margit mõõtis palavikku ja kraadiklaas näitas kolmkümmend kaheksa kraadi. Lisaks oli tal tugev nohu ja vahel ka köha. Ta helistas oma ülemusele ja ütles, et jääb täna koju. Ülemus soovis talle kiiret paranemist. Siis jõi Margit sooja teed meega ja läks tagasi voodisse. Lõuna ajal tundis ta end natuke paremini, aga õhtul tõusis palavik jälle. Tema elukaaslane käis apteegis ja tõi ravimeid. Margit otsustas, et kui homme ei ole parem, helistab ta perearstile. Kolmapäeval oli ta juba peaaegu terve. Neljapäeval läks ta jälle tööle. Kolleegid küsisid, kuidas ta end tunneb, ja Margit vastas, et palju paremini. Ta otsustas, et talvel joob ta rohkem teed ja käib sagedamini õues.',
        [['Mis Margitil hommikul valutas?', 'pea ja kurk'], ['Mis juhtus, kui ta püsti tõusis?', 'pea hakkas ringi käima'], ['Kui kõrge oli palavik?', '38 kraadi|kolmkümmend kaheksa kraadi'], ['Kellele ta helistas?', 'ülemusele'], ['Mida tõi elukaaslane?', 'ravimeid'], ['Millal oli Margit peaaegu terve?', 'kolmapäeval']]),
      B.wordforms('031_p_feel', 'Kuidas sa end tunned?', 'Kirjuta sõna kui-vormis (tunnen end …).', [['väsinud', 'tunnen end …', 'väsinuna'], ['haige', 'tunnen end …', 'haigena'], ['nõrk', 'tunnen end …', 'nõrgana'], ['terve', 'tunnen end …', 'tervena'], ['hea', 'tunnen end …', 'hästi'], ['halb', 'tunnen end …', 'halvasti']]),
      B.errorfix('031_p_fix', 'Paranda viga.', 'Kirjuta lause õigesti.', [['Mina valutab pea.', 'Mul valutab pea.'], ['Mul on valutab kõht.', 'Mul valutab kõht.'], ['Ma olen palavik.', 'Mul on palavik.'], ['Ma tunnen end väsinud.', 'Ma tunnen end väsinuna.'], ['Temal valutavad hammas.', 'Tal valutab hammas.']]),
      TR('031_p_tr', ['У меня болит голова.', 'У меня температура и кашель.', 'Я чувствую себя плохо.', 'У ребёнка болит живот.', 'Как ты себя чувствуешь?', 'У меня насморк уже три дня.']),
      D('031_p_dict', ['Mul valutab pea ja kurk.', 'Mul on kõrge palavik.', 'Ma tunnen end väga väsinuna.', 'Lapsel on köha ja nohu.', 'Täna tunnen end paremini.', 'Homme lähen arsti juurde.']),
      W('031_p_write', 'Kui ma olin haige.', 'Kirjuta 8–10 lauset: kuidas sa end tundsid ja mida tegid.', ['mul valutas', 'mul oli', 'tundsin end', 'jäin koju']),
      B.speaking('031_p_say', 'Kuidas sa end tunned?', 'Paariline on arst. Kirjelda 1–2 minutit oma sümptomeid.', ['Mis sul valutab?', 'Kas sul on palavik?', 'Kuidas sa end tunned?', 'Millal see algas?'], [60, 120], ['Mul valutab…', 'Mul on…', 'Tunnen end…']),
      B.wordorder('031_px_order', 'Pane lause kokku.', 'Kirjuta laused õigesti.', ['Mul valutab juba kaks päeva pea.', 'Eile õhtul oli mul kõrge palavik.', 'Ma tunnen end täna natuke paremini.', 'Lapsel on köha ja nohu.', 'Homme lähen perearsti juurde.']),
      B.selfcheck('031_p_self', ['Ma nimetan 10 kehaosa.', 'Ma eristan „mul valutab” ja „mul on”.', 'Ma ütlen, kuidas end tunnen.', 'Ma kirjeldan haigust 8–10 lausega.'], 'Tean, mis mul viga on'),
    ],
    transfer: [
      B.text('031_t_situation', 'Uus olukord', 'Sa oled tööl ja tunned end äkki halvasti. Pead ütlema ülemusele, et lähed koju, ja kirjutama kolleegile.'),
      B.reading('031_t_read', 'Loe foorumit.', 'Loe kolme postitust ja vasta.', 'Mis aitab külmetuse vastu?',
        'Kati: Mul on juba neli päeva nohu ja kurguvalu. Palavikku ei ole, aga ma tunnen end väga väsinuna. Mida teie teete, kui olete külmetunud? Jaan: Mina joon palju sooja teed meega ja sidruniga. Ma püüan palju magada ja ei käi tööl. Tavaliselt läheb kolme-nelja päevaga üle. Kui palavik on üle kolmekümne üheksa kraadi, helistan perearstile. Liis: Mulle aitab kanasupp! Mu vanaema tegi seda alati, kui olin laps. Lisaks käin värskes õhus jalutamas, aga ainult siis, kui palavikku ei ole. Kati: Aitäh! Ma proovin teed ja suppi. Homme jään koju ja kui ei ole parem, helistan arstile. Jaan: Saa ruttu terveks! Ja ära unusta piisavalt magada. Liis: Kui tahad, toon sulle õhtul suppi. Kati: Oled väga kena, aitäh! Ma kirjutan teile, kuidas mul läheb.',
        [['Mis Katil on?', 'nohu ja kurguvalu'], ['Mida joob Jaan?', 'sooja teed meega ja sidruniga'], ['Millal Jaan perearstile helistab?', 'kui palavik on üle 39 kraadi'], ['Mis aitab Liisi?', 'kanasupp'], ['Millal käib Liis jalutamas?', 'kui palavikku ei ole'], ['Mida Kati homme teeb?', 'jääb koju']]),
      B.choice('031_t_check', 'Mida öelda?', 'Vali olukorda sobiv lause.', [
        ['Sa tahad töölt koju minna.', 'Vabandust, ma tunnen end halvasti. Kas ma võin koju minna?', 'Ma lähen koju.', 'Mul on igav.'],
        ['Kolleeg küsib, mis viga.', 'Mul valutab pea ja on palavik.', 'Mul on pea.', 'Ma olen palavik.'],
        ['Sa helistad arstile.', 'Tere, ma sooviksin aega perearsti juurde.', 'Andke mulle arst.', 'Kus on haigla?'],
        ['Sõber on haige.', 'Saa ruttu terveks!', 'Head isu!', 'Palju õnne!'],
        ['Sa oled paremini.', 'Tänan, täna tunnen end juba paremini.', 'Ma olen hea.', 'Mul on terve.'],
      ], 'full', 'g_use'),
      B.rolecards('031_t_roles', 'Tööl.', 'Rääkige 2–3 minutit.',
        'Sa tunned end halvasti. Selgita ülemusele sümptomeid ja küsi luba koju minna.', 'Oled ülemus. Küsi täpsustusi ja leppige kokku, kes sinu töö täna teeb.',
        ['Mul valutab…', 'Mul on…', 'Kas ma võin…?'], ['Mis juhtus?', 'Kas sa vajad arsti?', 'Kes sinu töö teeb?']),
      W('031_t_msg', 'Sõnum kolleegile.', 'Kirjuta kolleegile 8–10 lauset: mis sul viga on ja mida ta peaks sinu eest tegema.', ['mul on', 'mul valutab', 'palun', 'homme']),
      B.speaking('031_t_tips', 'Minu nipid.', 'Räägi 1–2 minutit, mida sina teed, kui oled külmetunud.', ['Mida sa jood?', 'Kas sa lähed tööle?', 'Millal helistad arstile?'], [60, 120]),
      TR('031_t_tr', ['Мне нужно домой, я плохо себя чувствую.', 'У меня высокая температура.', 'Можешь сделать мою работу сегодня?', 'Выздоравливай скорее!', 'Завтра я позвоню врачу.']),
      B.gaps('031_tx_gaps', 'Täida laused.', 'Vali sobiv sõna.', ['Ma tunnen end [halvasti].', 'Mul [valutab] pea.', 'Kas ma [võin] koju minna?', 'Ma [helistan] homme arstile.', 'Palun [tee] minu eest see töö.', 'Saa ruttu [terveks]!'], ['halvasti', 'valutab', 'võin', 'helistan', 'tee', 'terveks']),
      B.dictation('031_tx_dict', 'Etteütlus.', 'Kuula ja kirjuta.', ['Mul on kõrge palavik.', 'Ma lähen täna koju.', 'Palun ütle ülemusele.', 'Homme helistan arstile.', 'Saa ruttu terveks!']),
      B.wordorder('031_tx_order', 'Pane lause kokku.', 'Kirjuta laused õigesti.', ['Ma tunnen end täna väga halvasti.', 'Kas ma võin koju minna?', 'Palun saada mulle see fail.', 'Homme ma tööle ei tule.', 'Ma helistan sulle õhtul.']),
      B.transformation('031_tx_trans', 'Ütle teisiti.', 'Kirjuta lause antud sõnaga.', [['Ma olen haige.', 'tunnen end', 'Ma tunnen end halvasti.'], ['Pea on haige.', 'valutab', 'Mul valutab pea.'], ['Temperatuur on kõrge.', 'palavik', 'Mul on palavik.'], ['Ma ei tule homme.', 'jään', 'Ma jään homme koju.'], ['Ma tahan arstiga rääkida.', 'helistan', 'Ma helistan arstile.']]),
      B.selfcheck('031_t_self', ['Ma mõistan foorumipostitusi.', 'Ma ütlen ülemusele, et olen haige.', 'Ma kirjutan kolleegile sõnumi.', 'Ma räägin oma nippidest.'], 'Haigena ka suhtlen'),
    ],
  },

  'a2b1-032': {
    title: 'Arsti juures',
    canDo: 'Ma annan arstile põhiinfo ja vastan vähemalt viiele täpsustavale küsimusele.',
    practice: [
      B.match('032_p_qa', 'Küsimus ja vastus.', 'Ühenda arsti küsimus ja patsiendi vastus.', [['Millal see algas?', 'Eile õhtul.'], ['Kui kaua köha on kestnud?', 'Umbes nädal.'], ['Kas teil on palavik?', 'Jah, 38 kraadi.'], ['Kas te võtate ravimeid?', 'Ei, ma ei võta.'], ['Kas teil on allergiat?', 'Jah, penitsilliini vastu.'], ['Kus valutab?', 'Siin, paremal pool.']], 'full', 'g_use'),
      B.gaps('032_p_q', 'Arsti küsimused.', 'Täida küsisõnaga.', ['[Millal] see algas?', '[Kui kaua] see on kestnud?', '[Kus] täpselt valutab?', '[Kas] teil on palavik?', '[Mis] ravimeid te võtate?', '[Kui] kõrge palavik on?'], ['millal', 'kui kaua', 'kus', 'kas', 'mis', 'kui']),
      B.dialogue('032_p_call', 'Aja broneerimine.', 'Täida telefonikõne.', 'Registratuur', 'Patsient', [
        ['A', 'Tere, Kase perearstikeskus. Kuidas saan [aidata]?'], ['B', 'Tere! Ma [sooviksin] aega perearsti juurde.'], ['A', 'Mis on teie [nimi] ja isikukood?'],
        ['B', 'Mari Tamm. Mul on juba neli päeva [köha].'], ['A', 'Kas teil on ka [palavik]?'], ['B', 'Eile oli, täna mitte.'], ['A', 'Kas teile [sobib] homme kell kümme?'], ['B', 'Jah, sobib. Aitäh!'],
      ]),
      B.reading('032_p_read', 'Loe: perearsti juures.', 'Loe vestlus ja vasta.', 'Vastuvõtt',
        'Arst: Tere! Mis teid täna siia toob? Patsient: Tere! Mul on juba nädal aega köha ja eile tekkis ka palavik. Arst: Millal köha algas? Patsient: Eelmisel kolmapäeval. Alguses oli kuiv köha, nüüd on rohkem lima. Arst: Kui kõrge palavik eile oli? Patsient: Õhtul oli kolmkümmend kaheksa ja pool. Arst: Kas te võtate praegu mingeid ravimeid? Patsient: Võtsin eile palavikualandajat. Arst: Kas teil on mõne ravimi vastu allergia? Patsient: Ei ole. Arst: Kuulan teie kopse. Hingake sügavalt sisse. Tundub, et see on bronhiit. Kirjutan teile retsepti. Võtke tablette kolm korda päevas pärast sööki. Puhake kodus vähemalt kolm päeva ja jooge palju vett. Patsient: Kas ma võin tööle minna? Arst: Ei, sel nädalal mitte. Kirjutan teile töövõimetuslehe. Kui palavik ei lange, tulge reedel uuesti. Patsient: Aitäh, doktor! Kas ma saan retsepti kohe apteegist kätte? Arst: Jah, retsept on juba süsteemis. Näidake apteegis lihtsalt oma isikukaarti.',
        [['Kui kaua patsiendil on köha?', 'nädal aega|nädal'], ['Milline oli köha alguses?', 'kuiv'], ['Kui kõrge oli palavik?', '38,5|kolmkümmend kaheksa ja pool'], ['Kas patsiendil on allergia?', 'ei'], ['Mis haigus see arsti arvates on?', 'bronhiit'], ['Kuidas tuleb tablette võtta?', 'kolm korda päevas pärast sööki']]),
      B.transformation('032_p_trans', 'Pikem vastus.', 'Vasta täislausega antud sõnadega.', [['Millal köha algas? (eelmisel nädalal)', 'Köha …', 'Köha algas eelmisel nädalal.'], ['Kui kaua palavik on olnud? (kaks päeva)', 'Palavik on …', 'Palavik on olnud kaks päeva.'], ['Kus valutab? (selg)', 'Mul …', 'Mul valutab selg.'], ['Kas te võtate ravimeid? (ei)', 'Ei, ma …', 'Ei, ma ei võta ravimeid.'], ['Kas teil on allergia? (kasside vastu)', 'Jah, mul …', 'Jah, mul on allergia kasside vastu.']]),
      B.wordorder('032_p_order', 'Pane küsimus kokku.', 'Kirjuta küsimused õigesti.', ['Kui kaua see on kestnud?', 'Millal teil palavik algas?', 'Kas te võtate praegu ravimeid?', 'Kas teil on mõne ravimi vastu allergia?', 'Kus teil täpselt valutab?']),
      TR('032_p_tr', ['Я хотел бы записаться к врачу.', 'Кашель начался неделю назад.', 'Вчера была температура.', 'У меня аллергия на пенициллин.', 'Сколько раз в день принимать таблетки?']),
      D('032_p_dict', ['Mul on juba nädal aega köha.', 'Eile õhtul oli palavik.', 'Ma ei võta praegu ravimeid.', 'Mul ei ole allergiat.', 'Võtke tablette kolm korda päevas.']),
      W('032_p_write', 'Vastuvõtu märkmed.', 'Kirjuta 8–10 lauset: mida sa ütleksid arstile oma viimasest haigusest.', ['algas', 'kestnud', 'mul on olnud', 'võtan']),
      B.speaking('032_p_say', 'Arst ja patsient.', 'Paaris: arst esitab 5 küsimust, patsient vastab täislausega.', ['Millal see algas?', 'Kui kaua see kestab?', 'Kas on palavik?', 'Kas võtate ravimeid?', 'Kas on allergia?'], [90, 120]),
      B.choice('032_px_q', 'Mida arst küsib?', 'Vali sobiv küsimus.', [['Eile õhtul.', 'Millal see algas?', 'Kus valutab?', 'Mis ravimeid võtate?'], ['Umbes nädal.', 'Kui kaua see on kestnud?', 'Millal see algas?', 'Kas on allergia?'], ['Ei, ma ei võta.', 'Kas te võtate ravimeid?', 'Kus valutab?', 'Kui kõrge palavik on?'], ['Siin, paremal.', 'Kus valutab?', 'Millal see algas?', 'Kas on palavik?'], ['38 kraadi.', 'Kui kõrge palavik on?', 'Kui kaua see kestab?', 'Kas on allergia?']], 'full', 'g_use'),
      B.selfcheck('032_p_self', ['Ma broneerin telefoni teel aja.', 'Ma vastan arsti küsimustele täislausega.', 'Ma mõistan, kuidas ravimit võtta.', 'Ma esitan arstile küsimuse.'], 'Arsti juures saan hakkama'),
    ],
    transfer: [
      B.reading('032_t_read', 'Loe infolehte.', 'Loe ravimi infolehte ja vasta.', 'Kuidas ravimit võtta?',
        'Täiskasvanud võtavad üks tablett kolm korda päevas. Tabletid tuleb võtta pärast sööki ja juua klaasi veega. Ärge võtke rohkem kui kuus tabletti ööpäevas. Lastele alla kaheteistkümne aasta seda ravimit ei soovitata. Kui palavik ei lange kolme päeva jooksul, pöörduge arsti poole. Ravim võib põhjustada unisust. Seepärast ei tohi pärast tableti võtmist autot juhtida. Ärge jooge ravimi ajal alkoholi. Rasedad naised peaksid enne kasutamist arstiga nõu pidama. Hoidke ravimit toatemperatuuril ja lastele kättesaamatus kohas. Kui teil tekib nahalööve, lõpetage ravimi võtmine ja helistage arstile. Ravimit ei tohi kasutada pärast kõlblikkusaja lõppu. Kõlblikkusaeg on märgitud pakendile. Küsimuste korral pöörduge apteekri poole. Apteeker selgitab teile hea meelega, kuidas ravimit õigesti kasutada. Kui te võtate samal ajal ka teisi ravimeid, öelge seda kindlasti arstile või apteekrile. Mõnda ravimit ei tohi koos võtta.',
        [['Mitu korda päevas võtavad täiskasvanud tabletti?', 'kolm korda|kolm'], ['Millal tuleb tablett võtta?', 'pärast sööki'], ['Mis on maksimum ööpäevas?', 'kuus tabletti|6'], ['Mida teha, kui palavik ei lange?', 'pöörduda arsti poole'], ['Miks ei tohi autot juhtida?', 'ravim võib põhjustada unisust'], ['Mida teha nahalööbe korral?', 'lõpetada ravim ja helistada arstile']]),
      B.truefalse('032_t_tf', 'Õige või vale?', 'Kontrolli infolehe järgi.', [['Tableti võib võtta tühja kõhuga.', false], ['Lastele alla 12 aasta ravimit ei soovitata.', true], ['Pärast tabletti võib autoga sõita.', false], ['Ravimit hoitakse külmkapis.', false], ['Lööbe korral tuleb arstile helistada.', true]]),
      B.text('032_t_situation', 'Uus olukord', 'Sinu vanem naaber ei räägi hästi eesti keelt. Sa lähed temaga perearsti juurde ja aitad tal rääkida.'),
      B.rolecards('032_t_roles', 'Perearsti juures.', 'Kolm rolli: arst, naaber ja sina. Rääkige 3 minutit.',
        'Oled arst. Küsi vähemalt 6 küsimust ja anna soovitus.', 'Oled abistaja. Vasta naabri eest ja küsi arstilt, kuidas ravimit võtta.',
        ['Millal see algas?', 'Kas teil on…?', 'Võtke…'], ['Tal valutab…', 'See algas…', 'Mitu korda päevas?']),
      W('032_t_note', 'Märkmed naabrile.', 'Kirjuta naabrile 8–10 lauset: mida arst ütles ja kuidas ravimit võtta.', ['arst ütles', 'võta', 'ära', 'kolm korda']),
      B.speaking('032_t_explain', 'Selgita sõbrale.', 'Selgita 1–2 minutit, kuidas Eestis perearsti juurde aega broneerida.', ['Kuhu helistada?', 'Mida öelda?', 'Mida kaasa võtta?'], [60, 120]),
      TR('032_t_tr', ['Принимайте по одной таблетке три раза в день.', 'Не садитесь за руль после таблетки.', 'Если температура не спадёт, позвоните врачу.', 'Храните лекарство в недоступном для детей месте.', 'Нельзя пить алкоголь.']),
      B.gaps('032_tx_gaps', 'Täida laused.', 'Vali sobiv sõna.', ['Võtke [üks] tablett kolm korda päevas.', 'Tablett võtke [pärast] sööki.', '[Ärge] juhtige autot.', 'Hoidke ravimit [toatemperatuuril].', 'Kui tekib lööve, [helistage] arstile.'], ['üks', 'pärast', 'ärge', 'toatemperatuuril', 'helistage']),
      B.errorfix('032_tx_fix', 'Paranda juhis.', 'Kirjuta lause õigesti.', [['Võtke kaks tablett.', 'Võtke kaks tabletti.'], ['Ärge juhite autot.', 'Ärge juhtige autot.'], ['Tablett võtke enne sööki ja pärast sööki.', 'Tablett võtke pärast sööki.'], ['Jooge alkohol ravimi ajal.', 'Ärge jooge alkoholi ravimi ajal.'], ['Hoidke ravimit lastele.', 'Hoidke ravimit lastele kättesaamatus kohas.'], ['Kui palavik ei lange, ootage nädal.', 'Kui palavik ei lange, pöörduge arsti poole.'], ['Võtke ravim pärast kõlblikkusaega.', 'Ärge võtke ravimit pärast kõlblikkusaega.']]),
      B.manymatch('032_tx_who', 'Kellele mis sobib?', 'Kellele võib ravimit anda? Mitu vastust on võimalik.', ['täiskasvanu', '10-aastane laps', 'autojuht', 'rase naine', 'inimene, kes joob veini'], ['võib võtta', 'ei tohi võtta', 'peab arstiga rääkima', 'ei tohi pärast autot juhtida']),
      B.transformation('032_tx_trans', 'Ütle teisiti.', 'Kirjuta lause antud sõnaga.', [['Võta tablett!', 'Võtke … (teie)', 'Võtke tablett!'], ['Ära juhi autot!', 'Ärge … (teie)', 'Ärge juhtige autot!'], ['Joo vett!', 'Jooge … (teie)', 'Jooge vett!'], ['Helista arstile!', 'Helistage … (teie)', 'Helistage arstile!'], ['Ära joo alkoholi!', 'Ärge … (teie)', 'Ärge jooge alkoholi!']]),
      B.selfcheck('032_t_self', ['Ma mõistan ravimi infolehte.', 'Ma aitan teisel arstiga rääkida.', 'Ma kirjutan arsti juhised üles.', 'Ma selgitan, kuidas aega broneerida.'], 'Abistan arsti juures'),
    ],
  },

  'a2b1-033': {
    title: 'Nõuanded ja käskiv kõneviis',
    canDo: 'Ma annan vähemalt viis sobivat nõuannet ja mõistan tüüpilisi juhiseid.',
    practice: [
      B.wordforms('033_p_imp', 'Sa-käsk.', 'Kirjuta käskiv vorm (sina).', [['puhkama', 'sina', 'puhka'], ['jooma', 'sina', 'joo'], ['sööma', 'sina', 'söö'], ['võtma', 'sina', 'võta'], ['magama', 'sina', 'maga'], ['helistama', 'sina', 'helista'], ['minema', 'sina', 'mine'], ['tulema', 'sina', 'tule']]),
      B.wordforms('033_p_neg', 'Ära …!', 'Kirjuta eitav käsk.', [['minema', 'ära …', 'ära mine'], ['jooma', 'ära …', 'ära joo'], ['sööma', 'ära …', 'ära söö'], ['tegema', 'ära …', 'ära tee'], ['suitsetama', 'ära …', 'ära suitseta'], ['muretsema', 'ära …', 'ära muretse']]),
      B.match('033_p_advice', 'Sümptom ja nõuanne.', 'Ühenda probleem ja sobiv nõuanne.', [['Mul valutab pea.', 'Joo vett ja puhka natuke.'], ['Mul on palavik.', 'Jää koju ja võta palavikurohtu.'], ['Mul valutab selg.', 'Ära tõsta raskeid asju.'], ['Ma olen väga väsinud.', 'Mine täna varem magama.'], ['Mul on köha.', 'Joo sooja teed meega.'], ['Mul valutab hammas.', 'Helista hambaarstile.']], 'full', 'g_use'),
      B.reading('033_p_read', 'Loe nõuandeid.', 'Loe artiklit ja vasta.', 'Kuidas külmetusest kiiremini terveks saada?',
        'Sügisel jäävad paljud inimesed haigeks. Kuidas kiiremini terveks saada? Kõigepealt puhka! Kui sul on palavik, ära mine tööle ega kooli. Nii aitad ka teisi, sest sa ei nakata kolleege. Joo palju vedelikku: vett, teed ja sooja puljongit. Söö kergelt, näiteks suppi ja puuvilju. Maga piisavalt, vähemalt kaheksa tundi. Ära suitseta ja ära joo alkoholi. Kui kurk valutab, loputa seda sooja soolaveega. Ära võta antibiootikume ilma arsti loata, sest külmetuse vastu need ei aita. Kui palavik kestab kauem kui kolm päeva või kui sul on raske hingata, helista kindlasti perearstile. Ja pea meeles: pese käsi tihti seebiga! Nii kaitsed ennast ja oma perekonda. Kui oled terveks saanud, hakka liikuma tasapisi. Ära mine kohe pikale jooksule, vaid alusta jalutamisest. Nii taastub keha kiiremini.',
        [['Miks ei tohi palavikuga tööle minna?', 'sa nakatad kolleege|teisi nakatada'], ['Mida tuleb juua?', 'vett, teed ja puljongit'], ['Kui palju tuleb magada?', 'vähemalt kaheksa tundi'], ['Mida teha kurguvalu korral?', 'loputada sooja soolaveega'], ['Miks ei aita antibiootikumid?', 'külmetuse vastu need ei aita'], ['Millal helistada perearstile?', 'kui palavik kestab üle kolme päeva või on raske hingata']]),
      B.transformation('033_p_trans', 'Ütle käsuga.', 'Muuda nõuanne käskivaks.', [['Sa peaksid puhkama.', 'käsk', 'Puhka!'], ['Sa ei peaks tööle minema.', 'eitav käsk', 'Ära mine tööle!'], ['Sa võiksid teed juua.', 'käsk', 'Joo teed!'], ['Sa peaksid arstile helistama.', 'käsk', 'Helista arstile!'], ['Sa ei peaks muretsema.', 'eitav käsk', 'Ära muretse!']]),
      B.errorfix('033_p_fix', 'Paranda käsk.', 'Kirjuta õigesti.', [['Ära minna tööle!', 'Ära mine tööle!'], ['Joob palju vett!', 'Joo palju vett!'], ['Ära sööd liiga palju!', 'Ära söö liiga palju!'], ['Helistad arstile!', 'Helista arstile!'], ['Ära tee muretse!', 'Ära muretse!']]),
      TR('033_p_tr', ['Отдохни сегодня дома.', 'Пей много воды.', 'Не ходи на работу.', 'Позвони врачу.', 'Не волнуйся!', 'Ты мог бы прогуляться.']),
      D('033_p_dict', ['Puhka täna kodus.', 'Joo palju sooja teed.', 'Ära mine täna trenni.', 'Võta ravim pärast sööki.', 'Helista homme arstile.']),
      W('033_p_write', 'Nõuanded sõbrale.', 'Sõber on haige. Kirjuta talle 8–10 nõuannet käskiva kõneviisiga.', ['puhka', 'joo', 'ära', 'võiksid']),
      B.speaking('033_p_say', 'Anna nõu.', 'Paariline ütleb probleemi, sina annad 3 nõuannet. Vahetage rollid.', ['Mul valutab pea.', 'Ma ei saa magada.', 'Mul on stress.'], [60, 120], ['Puhka…', 'Ära…', 'Sa võiksid…']),
      B.wordorder('033_px_order', 'Pane lause kokku.', 'Kirjuta laused õigesti.', ['Puhka täna terve päev kodus.', 'Joo palju sooja teed meega.', 'Ära mine täna trenni.', 'Sa võiksid perearstile helistada.', 'Ära võta antibiootikume ilma arstita.']),
      B.selfcheck('033_p_self', ['Ma moodustan sa-käsu.', 'Ma moodustan eitava käsu.', 'Ma annan sobiva nõuande.', 'Ma mõistan nõuandeartiklit.'], 'Annan head nõu'),
    ],
    transfer: [
      B.text('033_t_situation', 'Uus olukord', 'Sinu kolleeg on viimasel ajal väga väsinud ja magab halvasti. Ta küsib sinult nõu.'),
      B.reading('033_t_read', 'Loe kirja.', 'Loe kolleegi kirja ja vasta.', 'Ma ei saa magada',
        'Tere! Mul on viimasel kuul suur probleem: ma ei saa öösel magada. Ma lähen voodisse kell üksteist, aga uinun alles kell kaks või kolm. Õhtul vaatan tavaliselt telefoni või sülearvutit, sest pean vastama töökirjadele. Joon päevas neli või viis tassi kohvi, et olla ärkvel. Sporti ma praegu ei tee, sest mul pole aega. Hommikul olen väga väsinud ja tööl ei suuda keskenduda. Nädalavahetusel magan kuni lõunani, aga see ei aita. Mul on ka sageli peavalu. Ma ei taha minna arsti juurde, sest arvan, et see ei ole haigus. Mida sina teeksid minu asemel? Mu naine ütleb, et ma olen viimasel ajal väga närviline. Ma tahaksin jälle hästi magada ja tunda end puhanuna. Kas sul on mõni hea nõuanne? Aitäh! Andres',
        [['Mis on Andrese probleem?', 'ta ei saa öösel magada'], ['Millal ta uinub?', 'kell kaks või kolm'], ['Mida ta õhtul teeb?', 'vaatab telefoni või sülearvutit|vastab töökirjadele'], ['Mitu tassi kohvi ta joob?', 'neli või viis'], ['Miks ta sporti ei tee?', 'tal pole aega'], ['Miks ta ei taha arsti juurde minna?', 'ta arvab, et see ei ole haigus']]),
      B.categorize('033_t_sort', 'Hea või halb harjumus?', 'Sorteeri Andrese harjumused.', [['Segab und', ['telefon õhtul', 'palju kohvi', 'magab lõunani', 'töökirjad öösel']], ['Aitaks', ['jalutamine õhtul', 'kindel uneaeg', 'tee kohvi asemel', 'sport']]]),
      B.letter('033_t_reply', 'Vasta Andresele.', 'Anna vähemalt 6 nõuannet. Kasuta käske ja „sa võiksid”.', 'Tere, Andres!', 'Head und!', [80, 100]),
      B.rolecards('033_t_roles', 'Apteegis.', 'Rääkige 2–3 minutit.',
        'Oled klient. Kirjelda probleemi (halb uni, peavalu) ja küsi nõu.', 'Oled apteeker. Esita 3 küsimust ja anna nõuanded käskiva kõneviisiga.',
        ['Mul on probleem…', 'Mida te soovitate?'], ['Kui kaua see kestab?', 'Võtke…', 'Ärge…']),
      B.speaking('033_t_mono', 'Minu nõuanne.', 'Räägi 1–2 minutit: mis aitab sinul hästi magada.', ['Mis kell lähed magama?', 'Mida teed enne und?', 'Mida sa ei tee?'], [60, 120]),
      TR('033_t_tr', ['Не пей кофе вечером.', 'Ложись спать в одно и то же время.', 'Убери телефон за час до сна.', 'Ты мог бы гулять вечером.', 'Сходи к врачу, если не поможет.']),
      B.gaps('033_tx_gaps', 'Täida laused.', 'Vali sobiv sõna.', ['[Ära] joo õhtul kohvi.', '[Mine] magama alati samal ajal.', 'Sa [võiksid] õhtul jalutada.', '[Pane] telefon tund enne und ära.', '[Ära] tööta öösel.', 'Kui see ei aita, [mine] arsti juurde.'], ['ära', 'mine', 'võiksid', 'pane']),
      B.dictation('033_tx_dict', 'Etteütlus.', 'Kuula ja kirjuta.', ['Ära joo õhtul kohvi.', 'Mine magama samal ajal.', 'Pane telefon ära.', 'Sa võiksid jalutada.', 'Mine arsti juurde.']),
      B.transformation('033_tx_trans', 'Ütle teisiti.', 'Kirjuta lause antud sõnaga.', [['Sa peaksid varem magama minema.', 'käsk', 'Mine varem magama!'], ['Sa ei peaks kohvi jooma.', 'eitav käsk', 'Ära joo kohvi!'], ['Sa võiksid jalutada.', 'käsk', 'Jaluta!'], ['Sa ei peaks öösel töötama.', 'eitav käsk', 'Ära tööta öösel!'], ['Sa peaksid arstile minema.', 'käsk', 'Mine arsti juurde!']]),
      B.selfcheck('033_t_self', ['Ma mõistan probleemi kirjeldust.', 'Ma eristan häid ja halbu harjumusi.', 'Ma kirjutan nõuandekirja.', 'Ma annan apteegis või sõbrale nõu.'], 'Nõuandja'),
    ],
  },

  'a2b1-034': {
    title: 'Tervislikud harjumused',
    canDo: 'Ma kirjeldan vähemalt kolme harjumust ja selgitan nende mõju lihtsate põhjustega.',
    practice: [
      B.categorize('034_p_sort', 'Tervislik või mitte?', 'Sorteeri harjumused.', [['Tervislik', ['jalutan iga päev', 'joon piisavalt vett', 'magan kaheksa tundi', 'söön köögivilju']], ['Mitte eriti', ['istun kogu päeva', 'joon palju kohvi', 'söön hilja õhtul', 'vaatan telefoni voodis']]]),
      B.gaps('034_p_should', 'Peaksin või võiksin?', 'Täida lüngad.', ['Ma [peaksin] rohkem liikuma.', 'Sa [võiksid] õhtul jalutada.', 'Ma magan [liiga] vähe.', 'Ma joon [piisavalt] vett.', 'Ta [peaks] vähem kohvi jooma.', 'Me [võiksime] koos trenni minna.'], ['peaksin', 'võiksid', 'liiga', 'piisavalt', 'peaks', 'võiksime']),
      B.wordforms('034_p_cond', 'Tingiv kõneviis.', 'Kirjuta vorm.', [['pidama', 'mina', 'peaksin'], ['pidama', 'sina', 'peaksid'], ['pidama', 'tema', 'peaks'], ['võima', 'mina', 'võiksin'], ['võima', 'sina', 'võiksid'], ['võima', 'meie', 'võiksime']]),
      B.reading('034_p_read', 'Loe: Tõnu muutused.', 'Loe ja vasta.', 'Kuidas Tõnu oma elu muutis',
        'Aasta tagasi tundis Tõnu end pidevalt väsinuna. Ta töötas kontoris ja istus päevas kümme tundi. Õhtul vaatas ta telerit ja sõi kiirtoitu. Siis ütles arst, et Tõnu peaks oma harjumusi muutma. Tõnu otsustas alustada väikestest asjadest. Kõigepealt hakkas ta tööle jalgrattaga sõitma. See võtab kakskümmend minutit, aga on parem kui bussis istumine. Lõuna ajal läheb ta nüüd jalutama. Ta sööb rohkem köögivilju ja joob vähem magusaid jooke. Õhtul paneb ta telefoni kell kümme ära ja loeb raamatut. Nüüd magab ta kaheksa tundi ja tunneb end palju paremini. Ta kaotas ka viis kilo kaalu. Tõnu ütleb, et kõige raskem oli alustada. Esimesel nädalal tahtis ta mitu korda alla anda. Nüüd soovitab ta kõigil alustada ühest väikesest muutusest ja mitte kõike korraga muuta.',
        [['Miks Tõnu oli väsinud?', 'istus palju, sõi kiirtoitu|istus kümme tundi'], ['Kes ütles, et ta peaks harjumusi muutma?', 'arst'], ['Kuidas Tõnu nüüd tööle sõidab?', 'jalgrattaga'], ['Mida ta teeb lõuna ajal?', 'jalutab'], ['Mida ta teeb õhtul kell kümme?', 'paneb telefoni ära ja loeb'], ['Mis oli Tõnu arvates kõige raskem?', 'alustada']]),
      B.transformation('034_p_because', 'Lisa põhjus.', 'Ühenda laused sõnaga „sest”.', [['Ma peaksin rohkem magama. Ma olen väsinud.', 'sest', 'Ma peaksin rohkem magama, sest ma olen väsinud.'], ['Sa võiksid jalutada. Värske õhk on kasulik.', 'sest', 'Sa võiksid jalutada, sest värske õhk on kasulik.'], ['Ma joon vähem kohvi. Ma magan halvasti.', 'sest', 'Ma joon vähem kohvi, sest ma magan halvasti.'], ['Ta sõidab rattaga. See on tervislik.', 'sest', 'Ta sõidab rattaga, sest see on tervislik.'], ['Me sööme rohkem köögivilju. Need on kasulikud.', 'sest', 'Me sööme rohkem köögivilju, sest need on kasulikud.']]),
      B.choice('034_p_mean', 'Liiga palju või piisavalt?', 'Vali sobiv lause.', [['Ta magab ainult viis tundi.', 'Ta magab liiga vähe.', 'Ta magab piisavalt.', 'Ta magab liiga palju.'], ['Ma joon kaks liitrit vett päevas.', 'Ma joon piisavalt.', 'Ma joon liiga vähe.', 'Ma ei joo üldse.'], ['Ta istub kaksteist tundi päevas.', 'Ta istub liiga palju.', 'Ta istub piisavalt.', 'Ta ei istu.'], ['Ma söön iga päev kooki.', 'Ma söön liiga palju magusat.', 'Ma söön tervislikult.', 'Ma ei söö magusat.'], ['Ta liigub iga päev tunni.', 'Ta liigub piisavalt.', 'Ta liigub liiga vähe.', 'Ta ei liigu.']], 'full', 'g_use'),
      TR('034_p_tr', ['Мне следовало бы больше двигаться.', 'Ты мог бы ложиться раньше.', 'Я сплю слишком мало.', 'Я пью достаточно воды.', 'Он пьёт слишком много кофе.']),
      D('034_p_dict', ['Ma peaksin rohkem liikuma.', 'Sa võiksid õhtul jalutada.', 'Ma magan liiga vähe.', 'Ta joob piisavalt vett.', 'Me peaksime vähem istuma.']),
      W('034_p_write', 'Minu harjumused.', 'Kirjuta 8–10 lauset: kolm head ja kolm halba harjumust ning nende mõju.', ['peaksin', 'liiga', 'piisavalt', 'sest']),
      B.speaking('034_p_say', 'Võrdle harjumusi.', 'Võrdle paariliselt oma harjumusi 1–2 minutit.', ['Mitu tundi sa magad?', 'Kui palju sa liigud?', 'Mida sa peaksid muutma?'], [60, 120]),
      B.wordorder('034_px_order', 'Pane lause kokku.', 'Kirjuta laused õigesti.', ['Ma peaksin rohkem värskes õhus olema.', 'Sa võiksid tööle rattaga sõita.', 'Ta magab viimasel ajal liiga vähe.', 'Me sööme nüüd rohkem köögivilju.', 'Ma joon iga päev piisavalt vett.']),
      B.match('034_px_match', 'Harjumus ja mõju.', 'Ühenda harjumus ja tema mõju.', [['Ma magan liiga vähe.', 'Olen päeval väsinud.'], ['Ma liigun iga päev.', 'Tunnen end energilisena.'], ['Ma joon palju kohvi.', 'Ma ei saa öösel magada.'], ['Ma söön palju köögivilju.', 'Mu kõht on korras.'], ['Ma istun terve päeva.', 'Mu selg valutab.']], 'half', 'g_use'),
      B.selfcheck('034_p_self', ['Ma kirjeldan kolme harjumust.', 'Ma kasutan „peaksin” ja „võiksin”.', 'Ma ütlen „liiga” ja „piisavalt”.', 'Ma põhjendan sest-lausega.'], 'Tean, mida muuta'),
    ],
    transfer: [
      B.reading('034_t_read', 'Loe küsitlust.', 'Loe uuringu kokkuvõtet ja vasta.', 'Kui terved on eestlased?',
        'Uuringu järgi liigub ainult kolmandik eestlastest piisavalt. Arstid soovitavad liikuda vähemalt pool tundi päevas, aga paljud istuvad tööl ja kodus. Iga teine inimene magab tööpäevadel vähem kui seitse tundi. Noored kasutavad õhtul palju telefoni ja uinuvad hilja. Positiivne on see, et eestlased söövad rohkem köögivilju kui kümme aastat tagasi. Ka suitsetajaid on vähem. Kõige suurem probleem on stress: pooled vastajad ütlesid, et tunnevad end tihti väsinuna. Uurijad soovitavad teha väikeseid muutusi. Jaluta lõuna ajal. Mine trepist, mitte liftiga. Pane telefon tund aega enne und ära. Need lihtsad sammud aitavad juba mõne nädala pärast. Uuringus osales kaks tuhat inimest kõigist Eesti maakondadest. Kõige aktiivsemad olid Tartu ja Pärnu elanikud. Järgmine uuring tehakse kahe aasta pärast. Tulemused avaldatakse terviseameti kodulehel. Seal on ka palju kasulikke nõuandeid.',
        [['Mitu eestlast liigub piisavalt?', 'kolmandik|üks kolmest'], ['Kui palju arstid soovitavad liikuda?', 'pool tundi päevas|vähemalt pool tundi'], ['Kui palju magab iga teine inimene?', 'vähem kui seitse tundi'], ['Mis on paremaks läinud?', 'rohkem köögivilju, vähem suitsetajaid'], ['Mis on suurim probleem?', 'stress'], ['Mida uurijad soovitavad?', 'jalutada, minna trepist, telefon ära enne und']]),
      B.text('034_t_situation', 'Uus olukord', 'Sinu firma korraldab „Tervise kuu”. Iga töötaja teeb oma plaani: üks harjumus, mida ta kuu jooksul muudab.'),
      B.planning('034_t_plan', 'Minu tervise kuu.', 'Mõtle plaan läbi.', ['Mis harjumust ma muudan?', 'Miks see on tähtis?', 'Mida ma iga päev teen?', 'Kuidas ma kontrollin, et see õnnestub?']),
      W('034_t_write', 'Minu plaan.', 'Kirjuta oma tervise kuu plaan 8–10 lausega.', ['peaksin', 'iga päev', 'sest', 'võiksin']),
      B.rolecards('034_t_roles', 'Tervise kuu kohtumine.', 'Rääkige 2–3 minutit.',
        'Tutvusta kolleegile oma plaani ja küsi tema plaani kohta.', 'Kuula, anna üks nõuanne ja räägi oma plaanist.',
        ['Ma tahan…', 'Ma peaksin…, sest…'], ['Hea mõte!', 'Sa võiksid ka…', 'Minu plaan on…']),
      B.speaking('034_t_mono', 'Esitlus.', 'Tutvusta grupile 1–2 minutiga oma plaani.', ['Mis harjumus?', 'Miks?', 'Kuidas?'], [60, 120]),
      TR('034_t_tr', ['Я хочу больше гулять.', 'Мне следует ложиться раньше.', 'Это важно, потому что я устаю.', 'Каждый день я буду ходить по лестнице.', 'Ты мог бы присоединиться ко мне.']),
      B.rubric('034_t_rubric', 'Kontrolli plaani.', 'Märgi, mis on olemas.', ['Üks selge harjumus.', 'Põhjus sest-lausega.', 'Igapäevane tegevus.', 'Vähemalt 2 korda „peaksin” või „võiksin”.', 'Kuidas edu kontrollida.']),
      B.gaps('034_tx_gaps', 'Täida laused.', 'Vali sobiv sõna.', ['Ma [peaksin] rohkem magama.', 'Sa [võiksid] trepist minna.', 'Ma istun [liiga] palju.', 'Ma ei liigu [piisavalt].', 'See on tähtis, [sest] ma olen väsinud.'], ['peaksin', 'võiksid', 'liiga', 'piisavalt', 'sest']),
      B.dictation('034_tx_dict', 'Etteütlus.', 'Kuula ja kirjuta.', ['Ma tahan rohkem liikuda.', 'Ma peaksin varem magama minema.', 'Ma istun liiga palju.', 'Sa võiksid minuga kaasa tulla.']),
      B.transformation('034_tx_trans', 'Ütle teisiti.', 'Kirjuta lause antud sõnaga.', [['Ma liigun vähe.', 'peaksin', 'Ma peaksin rohkem liikuma.'], ['Sa magad vähe.', 'võiksid', 'Sa võiksid rohkem magada.'], ['Ta joob palju kohvi.', 'liiga', 'Ta joob liiga palju kohvi.'], ['Ma joon kaks liitrit vett.', 'piisavalt', 'Ma joon piisavalt vett.'], ['Me istume palju.', 'peaksime', 'Me peaksime vähem istuma.']]),
      B.match('034_tx_match', 'Soovitus ja põhjus.', 'Ühenda.', [['Mine trepist,', 'sest see on hea südamele.'], ['Jaluta lõuna ajal,', 'sest värske õhk annab energiat.'], ['Pane telefon ära,', 'sest siis uinud kiiremini.'], ['Joo vett,', 'sest keha vajab vedelikku.'], ['Söö puuvilju,', 'sest neis on vitamiine.']], 'half', 'g_use'),
      B.selfcheck('034_t_self', ['Ma mõistan uuringu kokkuvõtet.', 'Ma koostan oma plaani.', 'Ma tutvustan plaani teistele.', 'Ma annan kolleegile nõu.'], 'Tervise kuu algab'),
    ],
  },

  'a2b1-035': {
    title: 'Kontroll 7 — tervis',
    canDo: 'Ma lahendan terviseteemalise suhtlusolukorra iseseisvalt ja arusaadavalt.',
    practice: [
      B.tip('035_p_how', 'Kordamine', 'Tee kõik ilma abita. Märgi kahtlased kohad ja kontrolli neid tundide 31–34 lehtedelt.', 'full'),
      B.gaps('035_p_mix', 'Kümme punkti.', 'Kirjuta õige vorm.', ['[Mul valutab] (valutama) pea.', '[Mul on] palavik ja köha.', 'Ma tunnen end [väsinuna] (väsinud).', '[Puhka] (puhkama) täna kodus!', '[Ära mine] (minema) tööle!', 'Sa [peaksid] (pidama) rohkem magama.', 'Ma magan [liiga] vähe.', '[Kui kaua] see on kestnud?']),
      B.errorfix('035_p_fix', 'Leia viga.', 'Kirjuta lause õigesti.', [['Mina valutab selg.', 'Mul valutab selg.'], ['Ära jood kohvi!', 'Ära joo kohvi!'], ['Ma olen köha.', 'Mul on köha.'], ['Sa peaks rohkem liikuma.', 'Sa peaksid rohkem liikuma.'], ['Joob palju vett!', 'Joo palju vett!']]),
      B.match('035_p_words', 'Sõnavara.', 'Ühenda sõna ja tähendus.', [['palavik', 'kõrge temperatuur'], ['retsept', 'arsti paber ravimi jaoks'], ['perearst', 'oma arst, kelle juurde lähed esimesena'], ['apteek', 'koht, kus ostad ravimeid'], ['nohu', 'nina on täis'], ['köha', 'kurk teeb häält']], 'half'),
      B.reading('035_p_read', 'Loe ja vasta.', 'Loe tekst ja vasta.', 'Ootamatu reisihaigus',
        'Eelmisel suvel olime perega puhkusel Itaalias. Teisel päeval hakkas mu pojal kõht valutama ja tal tõusis palavik. Me ei teadnud, kuhu minna, sest me ei osanud itaalia keelt. Hotelli administraator aitas meid ja helistas arstile. Arst tuli tunni aja pärast. Ta küsis, millal valu algas ja mida poeg oli söönud. Selgus, et poeg oli söönud rannas jäätist, mis oli liiga kaua päikese käes olnud. Arst soovitas juua palju vett, süüa ainult riisi ja kreekereid ning puhata kaks päeva. Ta kirjutas ka ravimi. Kolmandal päeval oli poeg jälle terve ja me saime randa minna. Nüüd võtame reisile alati kaasa väikese apteegi. Selles on plaastrid, valuvaigisti, palavikurohi ja kõhutabletid. Samuti kirjutame üles kohaliku hädaabinumbri. Poeg sööb nüüd jäätist ainult kohvikus. Ja me kõik naerame selle loo üle.',
        [['Mis juhtus pojaga?', 'kõht valutas, tõusis palavik'], ['Kes aitas arsti kutsuda?', 'hotelli administraator'], ['Mida arst küsis?', 'millal valu algas ja mida poeg sõi'], ['Mis oli probleemi põhjus?', 'jäätis, mis oli päikese käes olnud'], ['Mida arst soovitas?', 'juua vett, süüa riisi ja kreekereid, puhata'], ['Mida pere nüüd alati kaasa võtab?', 'väikese apteegi']]),
      TR('035_p_tr', ['У меня болит горло.', 'Не ходи сегодня в школу.', 'Сколько времени это длится?', 'Тебе следовало бы больше спать.', 'Принимайте таблетки после еды.']),
      D('035_p_dict', ['Mul valutab pea.', 'Kui kaua see on kestnud?', 'Joo palju sooja teed.', 'Ära mine täna tööle.', 'Ma peaksin rohkem liikuma.']),
      W('035_p_write', 'Kordamise tekst.', 'Kirjuta 8–10 lauset: kuidas sa hoolitsed oma tervise eest.', ['ma peaksin', 'tavaliselt', 'kui', 'sest']),
      B.speaking('035_p_say', 'Suuline kordamine.', 'Vasta paarilise küsimustele 2 minutit.', ['Millal sa viimati haige olid?', 'Mida sa siis tegid?', 'Mis on sinu tervislik harjumus?'], [90, 120]),
      B.wordorder('035_px_order', 'Pane lause kokku.', 'Kirjuta laused õigesti.', ['Mul valutab kurk juba kolm päeva.', 'Kui kaua teil palavik on olnud?', 'Puhka täna terve päev kodus.', 'Sa peaksid rohkem värskes õhus olema.', 'Võtke tablett pärast sööki.']),
      B.match('035_px_m2', 'Probleem ja nõuanne.', 'Ühenda.', [['Mul valutab pea.', 'Puhka vaikses toas.'], ['Mul on kõrge palavik.', 'Helista perearstile.'], ['Ma ei saa magada.', 'Ära joo õhtul kohvi.'], ['Mul valutab selg.', 'Ära tõsta raskeid asju.'], ['Ma olen stressis.', 'Jaluta looduses.']], 'half', 'g_use'),
      B.wordorder('035_px_wo2', 'Veel lauseid.', 'Kirjuta laused õigesti.', ['Ma tunnen end väga väsinuna.', 'Ära mine täna tööle.', 'Millal teil köha algas?', 'Joo palju sooja teed.', 'Me peaksime vähem istuma.']),
      B.selfcheck('035_p_self', ['Ma tegin ülesanded ilma abita.', 'Ma parandasin vead.', 'Ma tean, mida korrata.', 'Olen valmis Kasuta leheks.'], 'Kordamine tehtud'),
    ],
    transfer: [
      B.text('035_t_situation', 'Lõpuülesanne', 'Sa oled reisil Lõuna-Eestis. Su sõber jääb äkki haigeks. Pead helistama arstile, aitama sõpra ja kirjutama tema perele.'),
      B.reading('035_t_read', 'Loe infot.', 'Loe ja vasta.', 'Tervisenõuande telefon 1220',
        'Kui sa ei saa perearstile helistada, näiteks õhtul või nädalavahetusel, helista tervisenõuande telefonile 1220. Telefon töötab ööpäev läbi. Seal vastavad kogenud õed ja arstid, kes annavad nõu eesti, vene ja inglise keeles. Nad küsivad sinu sümptomite kohta ja ütlevad, mida teha. Mõnikord piisab koduravist, mõnikord soovitavad nad minna erakorralise meditsiini osakonda. Kui olukord on eluohtlik, näiteks inimene ei hinga või on teadvuseta, helista kohe hädaabinumbrile 112. Kõne 1220-le maksab nagu tavaline kõne. Enne helistamist pane kirja peamised sümptomid ja võetud ravimid. Hoia käepärast ka isikukood. Kui helistad lapse pärast, ütle lapse vanus ja kaal. Ära karda helistada ka siis, kui sa ei ole kindel, kas olukord on tõsine. Parem on küsida kui oodata. Õde aitab sul otsustada, mida teha. Teenus on tasuta.',
        [['Millal helistada numbrile 1220?', 'kui ei saa perearstile helistada|õhtul või nädalavahetusel'], ['Mis keeltes saab nõu?', 'eesti, vene ja inglise'], ['Kes telefonile vastavad?', 'õed ja arstid'], ['Millal helistada 112?', 'kui olukord on eluohtlik'], ['Mida enne helistamist kirja panna?', 'sümptomid ja ravimid']]),
      B.rolecards('035_t_call', 'Kõne numbrile 1220.', 'Rääkige 3 minutit.',
        'Sinu sõbral on kõrge palavik ja kõhuvalu. Kirjelda sümptomeid ja küsi, mida teha.', 'Oled õde. Esita 6 küsimust ja anna nõuanded.',
        ['Minu sõbral on…', 'See algas…', 'Mida me peaksime tegema?'], ['Millal see algas?', 'Kas tal on…?', 'Andke talle…', 'Kui…, helistage 112.']),
      B.letter('035_t_letter', 'Kiri sõbra perele (90–110 sõna).', 'Kirjuta, mis juhtus, mida arst ütles ja kuidas sõber end nüüd tunneb.', 'Tere!', 'Ärge muretsege!', [90, 110]),
      B.rubric('035_t_rubric', 'Hindamise tingimused.', 'Märgi, mis on täidetud.', ['Kirjeldasin sümptomeid õigete konstruktsioonidega.', 'Vastasin vähemalt 5 küsimusele.', 'Kasutasin käskivat kõneviisi.', 'Kirjas on mis juhtus, arsti nõu ja praegune seis.', 'Ma ei läinud üle vene keelele.']),
      B.speaking('035_t_mono', 'Monoloog.', 'Räägi 2 minutit ilma tekstita: kuidas Eestis arstiabi saada.', ['Kuhu helistada?', 'Millal helistada 112?', 'Mida arstile öelda?'], [90, 120]),
      TR('035_t_tr', ['У моего друга высокая температура.', 'Это началось сегодня утром.', 'Что нам делать?', 'Дайте ему много воды.', 'Если станет хуже, звоните 112.']),
      B.gaps('035_tx_gaps', 'Täida laused.', 'Vali sobiv sõna.', ['Minu sõbral [on] kõrge palavik.', 'Tal [valutab] kõht.', 'See [algas] täna hommikul.', 'Mida me [peaksime] tegema?', 'Kui läheb halvemaks, [helistage] 112.'], ['on', 'valutab', 'algas', 'peaksime', 'helistage']),
      B.dictation('035_tx_dict', 'Etteütlus.', 'Kuula ja kirjuta.', ['Minu sõber on haige.', 'Tal on palavik ja kõhuvalu.', 'Me helistasime numbrile 1220.', 'Õde andis meile nõu.', 'Nüüd on tal parem.']),
      B.transformation('035_tx_trans', 'Ütle teisiti.', 'Kirjuta lause antud sõnaga.', [['Ta on haige.', 'tunneb end', 'Ta tunneb end halvasti.'], ['Kõht on haige.', 'valutab', 'Tal valutab kõht.'], ['Anna talle vett!', 'Andke … (teie)', 'Andke talle vett!'], ['Ta peaks puhkama.', 'käsk', 'Puhka!'], ['Kui kaua see kestab?', 'algas', 'Millal see algas?']]),
      B.selfcheck('035_t_self', ['Ma mõistan infoteksti.', 'Ma helistasin ja kirjeldasin olukorda.', 'Ma kirjutasin perele 90–110 sõna.', 'Ma selgitan, kuidas arstiabi saada.'], 'Moodul 7 tehtud'),
    ],
  },
};
