import { CheckCircle2, Clock3, Plus, Search, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useAuth } from '../../app/AuthContext.jsx';
import { Badge, Button, Card, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Select } from '../../components/ui/index.js';
import { useAsyncData } from '../../hooks/useAsyncData.js';
import { homeworkService, studentsService } from '../../services/firebase/index.js';
import { hasAnyRole, ROLES } from '../../utils/roles.js';

const blank = { studentId: '', task: '', due: new Date().toISOString().slice(0, 10) };
export default function HomeworkPage() {
  const { user } = useAuth(); const staff = hasAnyRole(user.roles, [ROLES.ADMIN, ROLES.TEACHER]);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [modal, setModal] = useState(false); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState('');
  const state = useAsyncData(async () => { const owned = staff ? null : await studentsService.listOwned(user.uid); const studentResult = staff ? await studentsService.list({ status: 'active', pageSize: 500, exhaustive: true }) : { items: owned }; const homework = staff ? await homeworkService.list() : await homeworkService.listByStudentIds(owned.map((item) => item.id)); return [homework, studentResult]; }, [staff, user.uid]);
  const filtered = useMemo(() => (state.data?.[0] || []).filter((item) => `${item.studentName || ''} ${item.task || ''}`.toLocaleLowerCase('et').includes(query.toLocaleLowerCase('et')) && (status === 'all' || (status === 'done' ? item.status === 'Tehtud' : item.status !== 'Tehtud'))), [state.data, query, status]);
  if (state.loading) return <LoadingState label="Laen kodutöid…" />;
  if (state.error) return <ErrorState message={state.error.message} onRetry={state.reload} />;
  const [, students] = state.data;
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const student = students.items.find((item) => item.id === form.studentId); if (!student) throw new Error('Vali õpilane.'); await homeworkService.create({ ...form, studentName: student.name }); setModal(false); setForm(blank); await state.reload(); } catch (error) { setActionError(error.message); } finally { setSaving(false); } };
  return <div className="page-content"><PageHeader eyebrow="Õppetöö" title="Kodutööd" description="Ülesanded, tähtajad ja lõpetamise olek ühes vaates." actions={<Button onClick={() => setModal(true)}><Plus size={18} /> Uus kodutöö</Button>} />{actionError ? <div className="action-error">{actionError}<button onClick={() => setActionError('')}>×</button></div> : null}
    <Card className="list-card"><div className="list-toolbar"><div className="search-field"><Search size={18} /><input aria-label="Otsi kodutööd" placeholder="Otsi õpilast või ülesannet" value={query} onChange={(e) => setQuery(e.target.value)} /></div><Select aria-label="Kodutöö staatus" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Kõik</option><option value="open">Pooleli</option><option value="done">Tehtud</option></Select></div>
    {filtered.length ? <div className="task-list">{filtered.map((item) => { const done = item.status === 'Tehtud'; const overdue = !done && item.due < new Date().toISOString().slice(0, 10); return <article className={done ? 'task-row is-done' : 'task-row'} key={item.id}><button className="task-check" aria-label={done ? 'Märgi pooleliolevaks' : 'Märgi tehtuks'} onClick={async () => { await homeworkService.setStatus(item.id, done ? 'Ootel' : 'Tehtud'); await state.reload(); }}>{done ? <CheckCircle2 /> : <Clock3 />}</button><div><strong>{item.task}</strong><span>{item.studentName || 'Õpilane'}</span></div><div className="task-due"><Badge tone={done ? 'success' : overdue ? 'danger' : 'neutral'}>{done ? 'Tehtud' : `Tähtaeg ${item.due || '—'}`}</Badge><button className="text-button danger" aria-label="Kustuta" onClick={async () => { if (window.confirm('Kas kustutada kodutöö?')) { await homeworkService.remove(item.id); await state.reload(); } }}><Trash2 size={17} /></button></div></article>; })}</div> : <EmptyState title="Kodutöid ei leitud" description="Lisa esimene ülesanne või muuda filtrit." />}</Card>
    <Modal open={modal} title="Uus kodutöö" onClose={() => setModal(false)} footer={<><Button variant="secondary" onClick={() => setModal(false)}>Loobu</Button><Button loading={saving} type="submit" form="homework-form">Lisa ülesanne</Button></>}><form id="homework-form" className="form-grid" onSubmit={submit}><Select className="form-grid__wide" label="Õpilane" value={form.studentId} onChange={(e) => setForm({ ...form, studentId: e.target.value })} required><option value="">Vali õpilane</option>{students.items.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</Select><Input className="form-grid__wide" label="Ülesanne" value={form.task} onChange={(e) => setForm({ ...form, task: e.target.value })} required /><Input label="Tähtaeg" type="date" value={form.due} onChange={(e) => setForm({ ...form, due: e.target.value })} required /></form></Modal>
  </div>;
}
