(function(){
  'use strict';
  const $=id=>document.getElementById(id),bridge=window.KeeleSeppBuilderBridge;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const script=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(Error('Sisselogimist ei saanud laadida.'));document.head.append(s);});
  let auth,loading=false,result=null;
  async function token(){if(!loading)loading=(async()=>{if(!window.firebase){await script('https://www.gstatic.com/firebasejs/9.22.2/firebase-app-compat.js');await script('https://www.gstatic.com/firebasejs/9.22.2/firebase-auth-compat.js');}if(!firebase.apps.length)firebase.initializeApp({apiKey:'AIzaSyAp8emBOh1fIqv72k_O5hkLkXVkfBt1al4',authDomain:'keelesepp-5136b.firebaseapp.com',projectId:'keelesepp-5136b',appId:'1:674098517935:web:e73d04a4ada67874da015a'});auth=firebase.auth();if(auth.authStateReady)await auth.authStateReady();else await new Promise(resolve=>{let off;off=auth.onAuthStateChanged(()=>{setTimeout(()=>off?.(),0);resolve();});});})();await loading;if(!auth.currentUser)throw Error('Logi esmalt KeeleSeppa sisse.');return auth.currentUser.getIdToken();}
  function form(){const lesson=bridge.get().authoring?.lesson||{};bridge.modal('Loo üks ülesanne AI-ga',`<p>AI teeb ühe redigeeritava mustandi. Kontrolli tulemust enne tundi.</p><div class="ai-form-grid"><label>Teema<input id="ai-topic" maxlength="180" value="${esc(lesson.topic||'') }" placeholder="Näiteks: igapäevane rutiin"></label><label>Tase<select id="ai-cefr">${['A1','A2','B1','B2','C1'].map(x=>`<option ${x===(lesson.cefr||'B1')?'selected':''}>${x}</option>`).join('')}</select></label><label>Vastuse viis<select id="ai-mode"><option value="short_text">Lühivastus</option><option value="long_text">Pikem vastus</option><option value="single_choice">Üks valik</option><option value="multiple_choice">Mitu valikut</option><option value="gaps">Täida lüngad</option></select></label></div><label>Soov või õppimise eesmärk<textarea id="ai-goal" maxlength="400" placeholder="Mida õpilane peaks harjutama?">${esc(lesson.goal||'')}</textarea></label><p class="ai-cost-note">Kulu piiramiseks kasutatakse kiiret Haiku mudelit, luuakse ainult üks plokk ja vastuse pikkus on serveris piiratud.</p><button id="ai-run" class="primary">✦ Genereeri üks mustand</button><div id="ai-output" role="status"></div>`);$('ai-run').onclick=generate;}
  async function generate(){const button=$('ai-run'),topic=$('ai-topic').value.trim(),goal=$('ai-goal').value.trim();if(!topic){$('ai-output').textContent='Lisa teema.';return;}button.disabled=true;$('ai-output').textContent='Koostan üht ülesannet…';try{const response=await fetch('/api/generate-activity',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+await token()},body:JSON.stringify({topic,goal,cefr:$('ai-cefr').value,responseMode:$('ai-mode').value})});const data=await response.json();if(!response.ok)throw Error(data.error||'Genereerimine ebaõnnestus.');result=data.activity;$('ai-output').innerHTML=`<div class="ai-result"><h3>${esc(result.title)}</h3><small>${esc(result.skillId)} · ${result.minutes} min</small><pre>${esc(result.routes.core.prompt)}</pre><button id="ai-add" class="primary">Lisa tundi ja redigeeri</button></div>`;$('ai-add').onclick=()=>{bridge.insertGenerated(result);bridge.close();};}catch(e){$('ai-output').textContent=e.message;}finally{button.disabled=false;}}
  $('generate-activity').onclick=form;
})();
