(function(){
  'use strict';
  const core=window.KeeleSeppLessonAuthoring,ux=window.KeeleSeppBuilderUX,templates=window.KeeleSeppBlockTemplates,$=id=>document.getElementById(id);
  const STORAGE='keelesepp.lesson-authoring.v1',PREFIX='keelesepp.authoring-preview.';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uuid=prefix=>prefix+'-'+crypto.randomUUID();
  const types={diagnostic:'Diagnostika',vocabulary:'Sõnavaratöö',controlled_practice:'Juhitud harjutus',scene:'Olukord',roleplay:'Rollimäng',transfer:'Uus olukord',assessment:'Kontroll'};
  const icons={diagnostic:'◎',vocabulary:'Aa',controlled_practice:'✎',scene:'▧',roleplay:'☏',transfer:'↗',assessment:'✓'};
  const routes={support:'Vajab tuge',core:'Tavaline tase',advanced:'Liiga lihtne'};
  let draft=ux.prepare(core.createDraft(uuid('draft'))),selected='',route='core',clipboard=null,collapsed=new Set(),device='desktop',previewToken='',previewTimer=null,dragId='',modalReturn=null;
  const saver=ux.autosave({storage:localStorage,key:STORAGE,onStatus:(status,message)=>{$('save-state').textContent=({saved:'✓ Salvestatud · siin brauseris',saving:'Salvestan…',dirty:'Salvestamata muudatused',error:'Salvestamine ebaõnnestus'})[status];$('save-state').dataset.status=status;if(message)notice('Salvestamine ebaõnnestus. Ekspordi varukoopia. '+message);}});
  try{const restored=saver.restore();if(restored){draft=restored;$('save-state').textContent='✓ Taastatud sellest brauserist';}}catch(e){notice('Varasemat mustandit ei saanud avada. Faili ega salvestust ei kirjutatud üle. '+e.message);}
  let history=ux.history(draft);selected=draft.activities[0]?.id||'';
  function notice(text){$('notice').hidden=!text;$('notice').textContent=text;}
  function announce(text){$('announcement').textContent=text;}
  function current(){return draft.activities.find(a=>a.id===selected);}
  function commit(next,{key='',select=selected,editor=true}={}){if(!history.commit(next,key))return;draft=history.get();selected=draft.activities.some(a=>a.id===select)?select:draft.activities[0]?.id||'';saver.queue(draft);renderStructure();renderHealth();if(editor)renderEditor();renderTop();schedulePreview();}
  function undo(){draft=history.undo();selected=draft.activities.some(a=>a.id===selected)?selected:draft.activities[0]?.id||'';saver.queue(draft);render();announce('Muudatus võetud tagasi.');}
  function redo(){draft=history.redo();selected=draft.activities.some(a=>a.id===selected)?selected:draft.activities[0]?.id||'';saver.queue(draft);render();announce('Muudatus tehtud uuesti.');}
  function renderTop(){document.body.classList.toggle('empty-lesson',!draft.activities.length);$('lesson-title').value=draft.title;$('lesson-meta').textContent=`${draft.authoring.lesson.cefr} · ${draft.authoring.lesson.minutes} min`;$('undo').disabled=!history.canUndo;$('redo').disabled=!history.canRedo;}
  function render(){renderTop();renderStructure();renderEditor();renderHealth();schedulePreview();}
  function select(id){selected=id;renderStructure();renderEditor();schedulePreview();document.body.classList.remove('structure-open');}
  function phaseOptions(value){const seen=new Map(templates.PHASES);for(const p of [...(draft.context?.phases||[]),...draft.authoring.phases])seen.set(p.id,p.title);for(const a of draft.activities)if(!seen.has(a.phaseId))seen.set(a.phaseId,ux.phaseName(draft,a.phaseId));return [...seen].map(([id,label])=>`<option value="${esc(id)}" ${value===id?'selected':''}>${esc(label)}</option>`).join('');}
  function renderStructure(){
    $('total').textContent=draft.activities.length;
    const query=$('search').value.toLocaleLowerCase(),skill=$('filter-skill').value,type=$('filter-type').value;
    const filtered=draft.activities.filter(a=>(!query||(a.title+' '+a.routes.core.prompt).toLocaleLowerCase().includes(query))&&(!skill||a.skillIds.includes(skill))&&(!type||a.workspaceType===type));
    let previous='',html='';const errors=ux.validate(draft).errors;
    filtered.forEach((a,i)=>{const m=ux.meta(draft,a.id),n=draft.activities.findIndex(b=>b.id===a.id);
      if(previous!==a.phaseId){html+=`<div class="phase-head drop-target" data-before="${esc(a.id)}" data-phase="${esc(a.phaseId)}"><button data-collapse="${esc(a.phaseId)}" aria-expanded="${!collapsed.has(a.phaseId)}">${collapsed.has(a.phaseId)?'▸':'▾'} ${esc(ux.phaseName(draft,a.phaseId))}</button></div>`;previous=a.phaseId;}
      if(!collapsed.has(a.phaseId))html+=`<article class="activity-row drop-target ${a.id===selected?'selected':''}" data-before="${esc(a.id)}" data-phase="${esc(a.phaseId)}" data-activity="${esc(a.id)}"><button class="drag-handle" draggable="false" data-drag="${esc(a.id)}" aria-label="Liiguta ${esc(a.title)}. Alt ja nooleklahvid muudavad järjekorda." title="Lohista või Alt + ↑ / ↓">⠿</button><button class="activity-select" data-select="${esc(a.id)}" aria-current="${a.id===selected}"><span class="activity-icon">${esc(icons[a.workspaceType])}</span><span class="activity-copy"><b>${n+1}. ${esc(a.title||'Nimetu ülesanne')}</b><small>${esc(a.skillIds.map(s=>ux.SKILLS[s]).join(' · '))}${a.evaluation?.response?' · Täidetav':''}</small></span><span class="activity-time">${m.minutes||0}′<small>${errors.some(e=>e.activityId===a.id)?'!':'✓'}</small></span></button><button class="card-menu" data-card-menu="${esc(a.id)}" aria-label="${esc(a.title)}: toimingud" title="Ploki toimingud">⋮</button></article>`;
      if(i===filtered.length-1||filtered[i+1].phaseId!==a.phaseId)html+=`<div class="phase-end drop-target" data-phase="${esc(a.phaseId)}" data-before="${esc(draft.activities[n+1]?.id||'')}"><span>Aseta etapi lõppu</span></div>`;
    });
    $('activities').innerHTML=html||'<p class="empty-small">'+(draft.activities.length?'Otsingule vastavaid plokke pole.':'Alusta tunnimallist või lisa esimene plokk.')+'</p>';
    $('activities').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>select(b.dataset.select));
    $('activities').querySelectorAll('[data-card-menu]').forEach(b=>b.onclick=()=>{select(b.dataset.cardMenu);activityMenu();});
    $('activities').querySelectorAll('[data-collapse]').forEach(b=>b.onclick=()=>{const id=b.dataset.collapse;collapsed.has(id)?collapsed.delete(id):collapsed.add(id);renderStructure();});
    $('activities').querySelectorAll('[data-drag]').forEach(b=>{
      let pointer=null;
      b.onpointerdown=e=>{if(e.button!==0)return;pointer={x:e.clientX,y:e.clientY,id:b.dataset.drag};b.setPointerCapture(e.pointerId);};
      b.onpointermove=e=>{
        if(!pointer)return;
        if(!dragId&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)<5)return;
        dragId=pointer.id;document.body.classList.add('dragging');b.closest('article').classList.add('drag-source');
        const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('.drop-target');
        document.querySelectorAll('.drop-before').forEach(x=>x.classList.remove('drop-before'));
        if(zone&&zone.dataset.before!==dragId)zone.classList.add('drop-before');
        const box=$('structure').getBoundingClientRect();if(e.clientY>box.bottom-30)$('structure').scrollTop+=14;else if(e.clientY<box.top+30)$('structure').scrollTop-=14;
      };
      b.onpointerup=e=>{if(!pointer)return;const id=dragId,zone=document.querySelector('.drop-before');pointer=null;const next=id&&zone?ux.reorder(draft,id,zone.dataset.before,zone.dataset.phase):null;clearDrag();if(next){commit(next,{select:id});announce('Plokk liigutatud.');}};
      b.onpointercancel=()=>{pointer=null;clearDrag();};
      b.onkeydown=e=>{if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();move(e.key==='ArrowUp'?-1:1,b.dataset.drag);}if(e.key==='Escape'){pointer=null;clearDrag();}};
    });
  }
  function clearDrag(){dragId='';document.body.classList.remove('dragging');document.querySelectorAll('.drop-before,.drag-source').forEach(el=>el.classList.remove('drop-before','drag-source'));}
  function move(delta,id=selected){commit(ux.move(draft,id,delta),{select:id});const handle=[...$('activities').querySelectorAll('[data-drag]')].find(b=>b.dataset.drag===id);handle?.focus();announce('Ploki uus koht: '+(draft.activities.findIndex(a=>a.id===id)+1));}
  function field(label,id,value,{textarea=false,max=180,placeholder='',hint=''}={}){return `<label class="field">${label}${textarea?`<textarea id="${id}" maxlength="${max}" placeholder="${esc(placeholder)}" aria-describedby="error-${id}">${esc(value)}</textarea>`:`<input id="${id}" maxlength="${max}" value="${esc(value)}" placeholder="${esc(placeholder)}" aria-describedby="error-${id}">`}<small class="field-error" id="error-${id}"></small>${id==='prompt'?`<small class="counter" id="prompt-counter">${String(value||'').length} / ${max}</small>`:''}${hint?`<small class="hint">${hint}</small>`:''}</label>`;}
  function renderEditor(){
    const a=current();if(!a){$('editor').innerHTML=`<div class="onboarding"><span class="welcome-icon">✦</span><p class="eyebrow">SINU JÄRGMINE HEA TUND</p><h1>Kuidas soovid alustada?</h1><p>Vali valmis struktuur või pane oma tund kokku. Kõiki plokke saad hiljem muuta.</p><div class="start-cards"><button id="scratch"><b>＋ Loo nullist</b><small>Vali oma esimene plokk</small></button><button id="lesson-templates"><b>▦ Vali tunnimall</b><small>45–60 minutit, valmis struktuur</small></button><button id="school"><b>↗ Kopeeri koolitund</b><small>Kool ja õppimine · 12 ülesannet</small></button><button id="import-start"><b>↑ Impordi fail</b><small>Taasta varasem varukoopia</small></button></div><p class="hint">Alusta kohalikult. Pilve salvestamiseks vali „Salvesta pilve”.</p></div>`;$('scratch').onclick=()=>library('blocks');$('lesson-templates').onclick=()=>library('lessons');$('school').onclick=copySchool;$('import-start').onclick=()=>$('import').click();return;}
    const m=ux.meta(draft,a.id),index=draft.activities.findIndex(b=>b.id===a.id),v=a.routes[route];
    $('editor').innerHTML=`<div class="editor-heading"><span class="eyebrow">ÜLESANNE ${index+1} / ${draft.activities.length}</span><div class="compact-actions"><button id="up" ${index===0?'disabled':''} aria-label="Liiguta üles">↑</button><button id="down" ${index===draft.activities.length-1?'disabled':''} aria-label="Liiguta alla">↓</button><button id="activity-menu" aria-label="Ülesande toimingud">•••</button></div></div>${field('Ülesande nimi','activity-title',a.title,{placeholder:'Näiteks: Räägime koolipäevast'})}<div class="field-grid"><label class="field">Etapp<select id="phase">${phaseOptions(a.phaseId)}</select></label><label class="field">Tüüp<select id="workspace-type">${Object.entries(types).map(([k,v])=>`<option value="${k}" ${a.workspaceType===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="field-grid"><label class="field">Kestus, min<input id="activity-minutes" type="number" min="0" max="240" value="${m.minutes||0}"><small class="field-error" id="error-activity-minutes"></small></label><label class="field">Kujundus<select id="layout">${[['native','Olemasoleva tunni vaade'],...templates.LAYOUTS].map(([k,v])=>`<option value="${k}" ${m.layout===k?'selected':''}>${v}</option>`).join('')}</select></label></div><fieldset><legend>Harjutatavad oskused</legend><div class="skills">${core.SKILLS.map(s=>`<label><input type="checkbox" data-skill="${s}" ${a.skillIds.includes(s)?'checked':''}><span>${ux.SKILLS[s]}</span></label>`).join('')}</div><small id="error-skills" class="field-error"></small></fieldset><div class="section-label"><h2>Õpilase ülesanne</h2><span>Vali sobiv tugi</span></div><div class="routes" role="group" aria-label="Ülesande toe tase">${core.ROUTES.map(r=>`<button data-route="${r}" aria-pressed="${r===route}">${routes[r]}<small>${r==='core'?'Standard':r==='support'?'Support':'Advanced'}</small></button>`).join('')}</div>${field('Mida õpilane näeb','prompt',v.prompt,{textarea:true,max:3000,placeholder:'Kirjelda selgelt, mida õpilane teeb.',hint:'Kirjuta ülesanne, küsimused või tekst. Iga rida võib olla eraldi kaart.'})}<div class="adapt-actions"><button id="simplify">↙ Lisa rohkem tuge</button><button id="challenge">↗ Lisa väljakutse</button><button id="copy-standard">Kopeeri tavaline teistele</button></div><details class="teacher-fields" open><summary>Õpetajale · õpilase vaates peidetud</summary>${field('Oodatav tulemus','expected',v.expected,{textarea:true,max:3000,placeholder:'Näidisvastus või eduka soorituse tunnused'})}${field('Juhis õpetajale','instruction',v.teacherInstruction,{textarea:true,max:4000,placeholder:'Kuidas suunata ja mida tähele panna?'})}</details>${m.reference?'<p class="reference-note">↗ Koopia olemasolevast koolitunnist. Algne tund jääb muutmata.</p>':''}`;
    const patch=(p,key)=>commit(core.updateActivity(draft,selected,p),{key:selected+key,editor:false});
    $('activity-title').oninput=e=>patch({title:e.target.value},'title');
    $('phase').onchange=e=>{const next=core.updateActivity(draft,selected,{phaseId:e.target.value});commit(next);};
    $('workspace-type').onchange=e=>patch({workspaceType:e.target.value},'type');
    $('activity-minutes').oninput=e=>{const d=ux.copy(draft);d.authoring.activities[selected].minutes=e.target.value===''?-1:Number(e.target.value);commit(d,{key:selected+'minutes',editor:false});};
    $('layout').onchange=e=>{const d=ux.copy(draft);d.authoring.activities[selected].layout=e.target.value;commit(d,{editor:false});};
    $('editor').querySelectorAll('[data-skill]').forEach(b=>b.onchange=()=>patch({skillIds:[...$('editor').querySelectorAll('[data-skill]:checked')].map(x=>x.dataset.skill)},'skills'));
    $('editor').querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;$('preview-route').value=route;renderEditor();renderHealth();schedulePreview();});
    for(const [id,key] of [['prompt','prompt'],['expected','expected'],['instruction','teacherInstruction']])$(id).oninput=e=>{const a=current();patch({routes:{...a.routes,[route]:{...a.routes[route],[key]:e.target.value}}},route+key);};
    $('up').onclick=()=>move(-1);$('down').onclick=()=>move(1);$('activity-menu').onclick=activityMenu;
    $('simplify').onclick=()=>adapt('support');$('challenge').onclick=()=>adapt('advanced');$('copy-standard').onclick=()=>confirmAction('Asenda toevariandid?','Tavalise taseme tekst kopeeritakse mõlemale teisele tasemele. Muudatuse saab tagasi võtta.',()=>commit(ux.adapt(draft,selected,'all')));
    renderInline();
    window.dispatchEvent(new Event("keelesepp-editor-rendered"));
  }
  function adapt(r){confirmAction('Loo uus toevariant?','Valitud variant asendatakse tavalise teksti ja ühe lisajuhisega. See ei kasuta tehisintellekti.',()=>{route=r;$('preview-route').value=r;commit(ux.adapt(draft,selected,r));});}
  function renderInline(){if($('prompt-counter')&&current())$('prompt-counter').textContent=current().routes[route].prompt.length+' / 3000';const result=ux.validate(draft),a=current();if(!a)return;const fields={'activity-title':'title',prompt:'prompt-'+route,skills:'skillIds',expected:'expected-'+route,instruction:'teacherInstruction-'+route};for(const [id,key] of Object.entries(fields)){const el=$('error-'+id);if(el){el.textContent=result.errors.find(e=>e.activityId===a.id&&e.field===key)?.message||'';$(id)?.setAttribute('aria-invalid',String(!!el.textContent));}}const minutes=$('error-activity-minutes');if(minutes)minutes.textContent=ux.meta(draft,a.id).minutes<0||ux.meta(draft,a.id).minutes>240?'Sisesta kestus 0–240 minutit.':'';}
  function renderHealth(){const v=ux.validate(draft);if(!draft.activities.length){$('health').innerHTML='<p class="hint">Siin näed tunni valmisolekut, kui lisad esimese ploki.</p>';$('validation-summary').textContent='Alusta valmis struktuurist või esimesest plokist.';$('validation-summary').className='';return;}$('health').innerHTML=`<div class="health-title"><b>Valmisolek</b><strong>${v.health}%</strong></div><progress max="100" value="${v.health}" aria-label="Mustandi valmisolek"></progress><small>Tunni kavand, mitte õpilase tulemus</small><details><summary>Vaata soovitusi · ${v.warnings.length+v.tips.length}</summary>${v.checks.map(c=>`<p>${c.ok?'✓':'○'} ${esc(c.label)}</p>`).join('')}${v.warnings.map(w=>`<p class="warning">! ${esc(w.message)}</p>`).join('')}${v.tips.map(w=>`<p>↗ ${esc(w.message)}</p>`).join('')}</details>`;$('validation-summary').innerHTML=v.errors.length?`<b>${v.errors.length} viga vajab parandamist</b> `+v.errors.slice(0,3).map((e,i)=>`<button data-error-index="${i}">${esc(draft.activities.find(a=>a.id===e.activityId)?.title||'Tund')}: ${esc(e.message)}</button>`).join(''):`${draft.activities.length} plokki · ${v.minutes} min plaanitud`;$('validation-summary').querySelectorAll('[data-error-index]').forEach(b=>b.onclick=()=>{const e=v.errors[Number(b.dataset.errorIndex)];if(e.activityId){const r=e.field.split('-').at(-1);if(core.ROUTES.includes(r)){route=r;$('preview-route').value=r;}select(e.activityId);$('prompt')?.focus();}else $('lesson-title').focus();});$('validation-summary').className=v.errors.length?'has-errors':'';renderInline();}
  function openModal(title,html){modalReturn=document.activeElement;$('modal-title').textContent=title;$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
  function closeModal(){$('modal').close();modalReturn?.focus();}
  $('modal-close').onclick=closeModal;$('modal').addEventListener('cancel',()=>setTimeout(()=>modalReturn?.focus(),0));
  function confirmAction(title,text,action){openModal(title,`<p>${esc(text)}</p><div class="modal-actions"><button id="cancel-action">Loobu</button><button class="primary" id="confirm-action">Kinnita</button></div>`);$('cancel-action').onclick=closeModal;$('confirm-action').onclick=()=>{closeModal();action();};}
  function library(mode){openModal(mode==='lessons'?'Vali tunni algus':'Lisa sobiv plokk',`<div class="library-tabs"><button id="blocks-tab" aria-pressed="${mode==='blocks'}">Ülesanded</button><button id="lessons-tab" aria-pressed="${mode==='lessons'}">Tunnimallid</button></div><input id="template-search" type="search" aria-label="Otsi malle" placeholder="⌕ Otsi nime või oskuse järgi"><div id="template-grid"></div>`);$('blocks-tab').onclick=()=>library('blocks');$('lessons-tab').onclick=()=>library('lessons');const show=()=>{const q=$('template-search').value.toLocaleLowerCase(),rows=mode==='blocks'?templates.BLOCKS:templates.LESSONS;let category='';$('template-grid').innerHTML=rows.filter(t=>(t.title+' '+(t.category||'')).toLocaleLowerCase().includes(q)).map(t=>{let heading='';if(mode==='blocks'&&category!==t.category){category=t.category;heading=`<h3>${esc(category)}</h3>`;}return heading+`<button class="template-card" data-template="${t.id}"><span class="template-icon">${mode==='blocks'?icons[t.type]:'▦'}</span><span><b>${esc(t.title)}</b><small>${mode==='blocks'?esc(ux.SKILLS[t.skill])+' · '+t.minutes+' min'+(t.response?' · Täidetav':''):t.blocks.length+' plokki · vabalt muudetav'}</small></span><span>＋</span></button>`;}).join('');$('template-grid').querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const t=b.dataset.template;if(mode==='blocks'){const id=uuid('act');closeModal();commit(ux.insert(draft,t,id,selected),{select:id});}else{const apply=()=>{closeModal();const next=ux.lessonTemplate(t,uuid('draft'),()=>uuid('act'));commit(next,{select:next.activities[0].id});};draft.activities.length?confirmAction('Asenda tunni struktuur?','Praegune kohalik kavand asendatakse. Undo taastab selle. Algseid avaldatud tunde ei muudeta.',apply):apply();}});};$('template-search').oninput=show;show();}
  function worksheetComposer(){
    openModal('Lisa küsimuste loend',`<p>Muuda märkmed korraga õpilase tööleheks. Iga rida loob eraldi täidetava ploki.</p><label class="field">Küsimused<textarea id="composer-lines" maxlength="20000" placeholder="Mis on sinu nimi?\nsingle: Vali õige vastus | A | B | C\ngaps: Täida lüngad | Lünk 1 | Lünk 2"></textarea><small id="error-composer-lines" class="field-error"></small></label><div class="composer-help"><b>Vastuse tüüp rea alguses</b><code>short: lühivastus (vaikimisi)</code><code>long: pikem vastus</code><code>single: küsimus | valik A | valik B</code><code>multiple: küsimus | valik A | valik B</code><code>gaps: juhis | lünk 1 | lünk 2</code></div><div class="modal-actions"><button id="composer-cancel">Loobu</button><button id="composer-create" class="primary">Lisa töölehele</button></div>`);
    $('composer-cancel').onclick=closeModal;$('composer-create').onclick=()=>{try{const result=ux.composeWorksheet(draft,$('composer-lines').value,()=>uuid('act'));closeModal();commit(result.draft,{select:result.created[0]});announce(result.created.length+' ülesannet lisatud.');}catch(e){$('error-composer-lines').textContent=e.message;}};
  }
  function copySchool(){const apply=()=>{closeModal();const next=ux.prepare(core.fromLesson(window.KeeleSeppAdaptiveLessons['est-b1-school-learning-01'],uuid('draft')));commit(next,{select:next.activities[0].id});};draft.activities.length?confirmAction('Kopeeri koolitund?','See asendab kohaliku kavandi. Varasema kavandi saad taastada Undo abil.',apply):apply();}
  function activityMenu(){const a=current(),m=ux.meta(draft,a.id);openModal('Ülesande toimingud',`<div class="action-menu"><button id="duplicate">⧉ Tee koopia</button><button id="copy-activity">Kopeeri plokk</button><button id="paste" ${clipboard?'':'disabled'}>Kleebi selle alla</button><button id="move-to">Liiguta etappi…</button><button id="reset-template" ${m.templateId?'':'disabled'}>Taasta algmall</button><button id="delete" class="danger">Kustuta plokk</button><button id="technical">Lisavalikud → tehnilised andmed</button></div>`);
    $('duplicate').onclick=()=>{const id=uuid('act');closeModal();commit(ux.duplicate(draft,selected,id),{select:id});};$('copy-activity').onclick=()=>{clipboard={activity:ux.copy(a),metadata:ux.copy(m)};closeModal();announce('Plokk kopeeritud. Vali koht ja Kleebi selle alla.');notice('Plokk kopeeritud. Kleebi see ülesande toimingute menüüst.');};$('paste').onclick=()=>{const id=uuid('act');closeModal();commit(ux.paste(draft,clipboard,id,selected),{select:id});};
    $('delete').onclick=()=>confirmAction('Kustuta „'+a.title+'”?',(m.reference?'See plokk pärineb olemasolevast tunnist. Algne tund jääb alles. ':'')+(draft.activities.length===1?'Kustutad tunni viimase ploki. ':'')+'Kustutamise saab Undo abil tagasi võtta.',()=>commit(ux.remove(draft,selected)));
    $('reset-template').onclick=()=>confirmAction('Taasta ploki algmall?','Sisu ja toevariandid asendatakse. Ploki püsiv identiteet säilib.',()=>commit(ux.reset(draft,selected)));
    $('move-to').onclick=()=>{openModal('Liiguta teise etappi',`<label class="field">Etapp<select id="target-phase">${phaseOptions(a.phaseId)}</select></label><button id="confirm-move" class="primary">Liiguta etapi lõppu</button>`);$('confirm-move').onclick=()=>{const phase=$('target-phase').value,others=draft.activities.filter(b=>b.id!==selected),last=others.findLastIndex(b=>b.phaseId===phase),before=last<0?'':others[last+1]?.id||'';closeModal();commit(ux.reorder(draft,selected,before,phase));};};
    $('technical').onclick=()=>{openModal('Tehnilised andmed',`<p>Püsivat identiteeti ei saa muuta.</p><label class="field">Activity ID<input id="activity-id" readonly value="${esc(a.id)}"></label><label class="field">Schema version<input readonly value="${a.schemaVersion}"></label><label class="field">Internal phase ID<input readonly value="${esc(a.phaseId)}"></label>`);};
  }
  function settings(){const l=draft.authoring.lesson;openModal('Tunni seaded',`<div class="field-grid"><label class="field">Keeletase<select id="setting-cefr">${['A1','A2','B1','B2','C1'].map(k=>`<option ${k===l.cefr?'selected':''}>${k}</option>`).join('')}</select></label><label class="field">Kestus, min<input id="setting-minutes" type="number" min="0" max="240" value="${l.minutes}"><small id="error-setting-minutes" class="field-error"></small></label></div>${field('Tunni eesmärk','setting-goal',l.goal,{textarea:true,max:4000,placeholder:'Tunni lõpuks oskab õpilane…'})}${field('Teema','setting-topic',l.topic)}${field('Märksõnad','setting-tags',l.tags,{placeholder:'Eralda komaga'})}<fieldset><legend>Tunni oskused</legend><div class="skills">${core.SKILLS.map(k=>`<label><input data-lesson-skill="${k}" type="checkbox" ${l.skills.includes(k)?'checked':''}><span>${ux.SKILLS[k]}</span></label>`).join('')}</div></fieldset>${field('Edu tunnused · üks reale','setting-successCriteria',l.successCriteria,{textarea:true,max:4000})}${field('Märkmed õpetajale','setting-notes',l.notes,{textarea:true,max:4000})}<p class="hint">Muudatused jäävad kohalikku kavandisse. Õppekava seost ei looda.</p><button id="settings-done" class="primary">Valmis</button>`);
    for(const key of ['cefr','minutes','goal','topic','tags','successCriteria','notes'])$('setting-'+key).oninput=e=>{const d=ux.copy(draft);d.authoring.lesson[key]=key==='minutes'?(e.target.value===''?-1:Number(e.target.value)):e.target.value;commit(d,{key:'lesson-'+key,editor:false});if($('error-setting-minutes'))$('error-setting-minutes').textContent=d.authoring.lesson.minutes<0||d.authoring.lesson.minutes>240?'Sisesta kestus 0–240 minutit.':'';};$('modal-content').querySelectorAll('[data-lesson-skill]').forEach(b=>b.onchange=()=>{const d=ux.copy(draft);d.authoring.lesson.skills=[...$('modal-content').querySelectorAll('[data-lesson-skill]:checked')].map(b=>b.dataset.lessonSkill);commit(d,{editor:false});});$('settings-done').onclick=closeModal;
  }
  function closeSnapshot(){if(previewToken){try{sessionStorage.removeItem(PREFIX+previewToken);}catch{}previewToken='';}$('preview-frame').removeAttribute('src');}
  function schedulePreview(){clearTimeout(previewTimer);$('preview-state').textContent='Uuendan eelvaadet…';previewTimer=setTimeout(refreshPreview,450);}
  function refreshPreview(){clearTimeout(previewTimer);const result=ux.validate(draft);if(!result.ok){closeSnapshot();$('preview-state').textContent=draft.activities.length?'Paranda vead, et näha kehtivat eelvaadet.':'Lisa esimene plokk — siin avaneb kohe õpilase vaade.';return;}try{closeSnapshot();previewToken=crypto.randomUUID();sessionStorage.setItem(PREFIX+previewToken,core.serialize(draft));$('preview-frame').src='/haldus-adaptive-lesson/?'+new URLSearchParams({authoringPreview:previewToken,activity:selected,route:$('preview-route').value,view:$('preview-view').value});$('preview-state').textContent='Värske eelvaade · '+(current()?.title||draft.title);resizePreview();}catch(e){notice('Eelvaadet ei saanud avada: '+e.message);}}
  function resizePreview(){$('preview-viewport').style.maxWidth={desktop:'1120px',tablet:'768px',mobile:'375px'}[device];const available=$('preview-viewport').clientWidth,width={desktop:Math.min(1100,Math.max(375,available)),tablet:768,mobile:375}[device];if(!available)return;const scale=Math.min(1,available/width);$('preview-frame').style.width=width+'px';$('preview-frame').style.height=Math.max(620,Math.min(1400,600/scale))+'px';$('preview-frame').style.transform=`scale(${scale})`;$('preview-canvas').style.height=Math.min(760,parseFloat($('preview-frame').style.height)*scale)+'px';}
  addEventListener('resize',resizePreview);addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('preview-frame').contentWindow||e.data?.type!=='keelesepp-preview-navigation'||e.data.token!==previewToken||!draft.activities.some(a=>a.id===e.data.activityId))return;if(selected!==e.data.activityId){selected=e.data.activityId;renderStructure();renderEditor();}});
  $('preview-frame').onload=resizePreview;$('preview-view').onchange=refreshPreview;$('preview-route').onchange=()=>{route=$('preview-route').value;renderEditor();refreshPreview();};
  document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;document.querySelectorAll('[data-device]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));resizePreview();});
  $('fullscreen').onclick=()=>{document.body.classList.toggle('preview-fullscreen');resizePreview();};$('show-preview').onclick=()=>{document.body.classList.remove('preview-collapsed');document.body.classList.add('preview-open');resizePreview();refreshPreview();};$('close-preview').onclick=()=>{document.body.classList.remove('preview-open','preview-fullscreen');document.body.classList.toggle('preview-collapsed',innerWidth>1300);};$('refresh-preview').onclick=refreshPreview;
  $('show-structure').onclick=()=>document.body.classList.toggle('structure-open');$('close-structure').onclick=()=>document.body.classList.remove('structure-open');
  $('more').onclick=()=>{openModal('Veel võimalusi',`<div class="action-menu"><button id="new">＋ Uus tund</button><button id="choose-lesson">▦ Vali tunnimall</button><button id="copy-school">↗ Kopeeri koolitund</button><button id="export">↓ Ekspordi varukoopia</button><button id="import-menu">↑ Impordi JSON</button></div><p class="hint">Üks kohalik mustand selles brauseris. Ekspordi eri tundidest eraldi failid.</p>`);$('new').onclick=()=>confirmAction('Alusta uut tundi?','Praegune kavand asendatakse. Undo taastab selle; ekspordi esmalt eraldi varukoopia, kui vaja.',()=>commit(ux.prepare(core.createDraft(uuid('draft')))));$('choose-lesson').onclick=()=>library('lessons');$('copy-school').onclick=copySchool;$('export').onclick=exportDraft;$('import-menu').onclick=()=>$('import').click();};
  function exportDraft(){if(!ux.validate(draft).ok){closeModal();notice('Paranda vead enne eksportimist.');return;}const blob=new Blob([core.serialize(draft)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=draft.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);closeModal();}
  $('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>core.MAX_BYTES)throw Error('Fail on liiga suur.');const next=ux.prepare(core.parse(await file.text()));if(!ux.validate(next).ok)throw Error('Failis on vigased ülesanded.');const apply=()=>{closeModal();commit(next,{select:next.activities[0]?.id});notice('Mustand imporditud.');};draft.activities.length?confirmAction('Asenda kavand imporditud tunniga?','Praeguse kavandi saad Undo abil taastada.',apply):apply();}catch(error){notice('Import ebaõnnestus. Praegune kavand jäi alles. '+error.message);}finally{e.target.value='';}};
  $('add-phase').onclick=()=>{openModal('Lisa oma etapp',`${field('Etapi nimi','new-phase','',{placeholder:'Näiteks: Paaristöö'})}<button id="create-phase" class="primary">Lisa ja kasuta valitud plokil</button>`);$('create-phase').onclick=()=>{const title=$('new-phase').value.trim();if(!title){$('error-new-phase').textContent='Lisa etapi nimi.';return;}const d=ux.copy(draft),id=uuid('phase');d.authoring.phases.push({id,title});if(current())d.activities.find(a=>a.id===selected).phaseId=id;closeModal();commit(d);};};
  $('add').onclick=()=>library('blocks');$('quick-worksheet').onclick=worksheetComposer;$('settings').onclick=settings;$('undo').onclick=undo;$('redo').onclick=redo;$('save').onclick=()=>{saver.queue(draft);if(!saver.flush()){renderHealth();notice('Mustand pole salvestatud. Paranda vead või kontrolli brauseri salvestusruumi.');}else notice('');};
  $('lesson-title').oninput=e=>{const next=ux.copy(draft);next.title=e.target.value;commit(next,{key:'lesson-title',editor:false});};
  for(const id of ['search','filter-skill','filter-type'])$(id).oninput=renderStructure;
  $('filter-skill').insertAdjacentHTML('beforeend',Object.entries(ux.SKILLS).map(([k,v])=>`<option value="${k}">${v}</option>`).join(''));$('filter-type').insertAdjacentHTML('beforeend',Object.entries(types).map(([k,v])=>`<option value="${k}">${v}</option>`).join(''));
  addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!$('modal').open){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==='Escape'&&!$('modal').open){document.body.classList.remove('preview-fullscreen','preview-open','structure-open');resizePreview();}});
  addEventListener('beforeunload',e=>{if(saver.dirty){e.preventDefault();e.returnValue='';}});
  render();
window.KeeleSeppBuilderBridge={selected:()=>selected,patchResponse:spec=>{const next=ux.copy(draft),a=next.activities.find(a=>a.id===selected);if(!a)return;a.evaluation={...a.evaluation};if(spec){a.responseMode=spec.mode;a.evaluation.response=spec;}else{delete a.responseMode;delete a.evaluation.response;}commit(next);},get:()=>ux.copy(draft),replace:next=>{draft=ux.prepare(next);history=ux.history(draft);selected=draft.activities[0]?.id||'';saver.queue(draft);render();},modal:openModal,close:closeModal,confirm:confirmAction};
})();
