export const CONTENT_LIBRARY_SCHEMA = 'keelesepp.generator-content-library/1';
export const CONTENT_LIBRARY_VERSION = 5;

const vocabulary = (id, rows) => rows.map(([key, word, translation, lexicalType, focusId]) => ({
  id: `${id}-v-${key}`, word, translation, lexicalType, focusIds: [focusId],
}));

const sentences = (id, rows) => rows.map(([key, focusId, contextId, text, difficulty = 1]) => ({
  id: `${id}-s-${key}`, focusIds: [focusId], contextIds: [contextId], difficulty, text, slots: {},
}));

const prompts = (id, prefix, rows) => rows.map(([key, focusId, contextId, text]) => ({
  id: `${id}-${prefix}-${key}`, focusIds: [focusId], contextIds: [contextId], text,
}));

export const REUSABLE_CONTENT_LIBRARY = Object.freeze({
  introduction: {
    id: 'introduction',
    focus: { id: 'introduction', type: 'communication', label: 'Tutvumine ja viisakus', patterns: ['Tere! Mina olen …', 'Meeldiv tutvuda.', 'Vabandust, kuidas?'], aliases: ['tutvumine', 'viisakus'] },
    vocabulary: vocabulary('introduction', [
      ['tere', 'tere', 'здравствуйте', 'phrase', 'introduction'],
      ['tutvuda', 'tutvuma', 'знакомиться', 'verb', 'introduction'],
      ['meeldiv', 'meeldiv', 'приятно', 'adjective', 'introduction'],
      ['palun', 'palun', 'пожалуйста', 'phrase', 'introduction'],
      ['aitah', 'aitäh', 'спасибо', 'phrase', 'introduction'],
      ['vabandust', 'vabandust', 'извините', 'phrase', 'introduction'],
    ]),
    contexts: [
      { id: 'intro-course', label: 'Esimene kord keelekursusel', tags: ['introduction'], names: ['Mari', 'Daria'], times: ['09:00', '12:30', '18:00'] },
      { id: 'intro-neighbour', label: 'Kohtumine uue naabriga', tags: ['introduction'], names: ['Jaan', 'Olga'], times: ['10:15', '15:00', '19:30'] },
      { id: 'intro-work', label: 'Uue kolleegiga tutvumine', tags: ['introduction'], names: ['Katrin', 'Andrei'], times: ['08:30', '13:00', '17:15'] },
    ],
    sentences: sentences('introduction', [
      ['1', 'introduction', 'intro-course', 'Tere! Mina olen Daria.'],
      ['2', 'introduction', 'intro-course', 'Meeldiv tutvuda! Mina olen Mari.'],
      ['3', 'introduction', 'intro-neighbour', 'Vabandust, kuidas teie nimi on?'],
      ['4', 'introduction', 'intro-neighbour', 'Tere tulemast meie majja!'],
      ['5', 'introduction', 'intro-work', 'Tere! Ma olen teie uus kolleeg.'],
      ['6', 'introduction', 'intro-work', 'Palun korrake oma nime aeglasemalt.'],
    ]),
    dialogues: [{ id: 'introduction-d-1', focusIds: ['introduction'], contextIds: ['intro-course'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Tere! Mina olen Ksenia. Mis teie [nimi] on?' },
      { who: 'B', text: 'Tere! Mina olen Martin. Meeldiv [tutvuda].' },
      { who: 'A', text: 'Meeldiv tutvuda!' },
    ] }],
    errorPairs: [
      { id: 'introduction-e-1', focusIds: ['introduction'], wrong: 'Tere, mina nimi on Olga.', correct: 'Tere, minu nimi on Olga.' },
      { id: 'introduction-e-2', focusIds: ['introduction'], wrong: 'Meeldiv tutvustan.', correct: 'Meeldiv tutvuda.' },
    ],
    translations: [
      { id: 'introduction-t-1', focusIds: ['introduction'], sourceLang: 'ru', source: 'Извините, как вас зовут?', target: 'Vabandust, mis teie nimi on?', alternatives: [] },
      { id: 'introduction-t-2', focusIds: ['introduction'], sourceLang: 'ru', source: 'Очень приятно познакомиться.', target: 'Väga meeldiv tutvuda.', alternatives: [] },
    ],
    speakingPrompts: prompts('introduction', 'sp', [['1', 'introduction', 'intro-course', 'Tutvusta ennast õpetajale ja küsi temalt vähemalt kolm küsimust.'], ['2', 'introduction', 'intro-work', 'Alusta vestlust uue kolleegiga, palu üht vastust korrata ja lõpeta vestlus viisakalt.']]),
    writingPrompts: prompts('introduction', 'wp', [['1', 'introduction', 'intro-course', 'Kirjuta 5–6 repliigiga tutvumisvestlus kahe kursuslase vahel.']]),
    successCriteria: ['Ma tutvustan ennast, küsin vestluspartnerilt põhiinfot ja kasutan viisakusväljendeid.'],
  },
  'basic-questions': {
    id: 'basic-questions',
    focus: { id: 'basic-questions', type: 'communication', label: 'Põhiküsimused ja täpsustamine', patterns: ['Mis su nimi on?', 'Kust sa pärit oled?', 'Mis keeli sa räägid?'], aliases: ['küsimused', 'täpsustamine'] },
    vocabulary: vocabulary('basic-questions', [
      ['mis', 'mis', 'что / какой', 'pronoun', 'basic-questions'],
      ['kus', 'kus', 'где', 'adverb', 'basic-questions'],
      ['kust', 'kust', 'откуда', 'adverb', 'basic-questions'],
      ['milline', 'milline', 'какой', 'pronoun', 'basic-questions'],
      ['kuidas', 'kuidas', 'как', 'adverb', 'basic-questions'],
    ]),
    contexts: [],
    sentences: sentences('basic-questions', [
      ['1', 'basic-questions', 'intro-course', 'Mis su nimi on?'],
      ['2', 'basic-questions', 'intro-course', 'Kust sa pärit oled?'],
      ['3', 'basic-questions', 'intro-work', 'Mis keeli sa räägid?'],
      ['4', 'basic-questions', 'intro-neighbour', 'Kus sa praegu elad?'],
      ['5', 'basic-questions', 'intro-work', 'Kuidas palun? Kas te võite korrata?'],
    ]),
    dialogues: [], errorPairs: [], translations: [], speakingPrompts: [], writingPrompts: [], successCriteria: [],
  },
  'olema-present': {
    id: 'olema-present',
    focus: { id: 'olema-present', type: 'grammar', label: 'Olema olevikus ja eitus', patterns: ['ma olen / ma ei ole', 'sa oled / sa ei ole', 'ta on / ta ei ole'], aliases: ['olema', 'eitus'] },
    vocabulary: vocabulary('olema-present', [
      ['olen', 'olen', 'я являюсь', 'verb', 'olema-present'],
      ['oled', 'oled', 'ты являешься', 'verb', 'olema-present'],
      ['on', 'on', 'он / она является', 'verb', 'olema-present'],
      ['ei-ole', 'ei ole', 'не является', 'verb', 'olema-present'],
      ['oleme', 'oleme', 'мы являемся / мы находимся', 'verb', 'olema-present'],
    ]),
    contexts: [
      { id: 'verbs-profile', label: 'Minu lühike profiil', tags: ['profile'], names: ['Anna', 'Mihkel'], times: ['08:00', '13:00', '18:30'] },
      { id: 'verbs-class', label: 'Keeletunnis', tags: ['study'], names: ['Irina', 'Toomas'], times: ['09:15', '14:30', '19:00'] },
      { id: 'verbs-work', label: 'Töö ja igapäev', tags: ['work'], names: ['Sergei', 'Liis'], times: ['07:45', '12:00', '17:30'] },
    ],
    sentences: sentences('olema-present', [
      ['1', 'olema-present', 'verbs-profile', 'Ma olen Anna ja ma olen kolmkümmend aastat vana.'],
      ['2', 'olema-present', 'verbs-profile', 'Ma ei ole õpetaja, ma olen õpilane.'],
      ['3', 'olema-present', 'verbs-class', 'Kas sa oled täna tunnis?'],
      ['4', 'olema-present', 'verbs-class', 'Me oleme eesti keele kursusel.'],
      ['5', 'olema-present', 'verbs-work', 'Ta on praegu tööl.'],
    ]),
    dialogues: [],
    errorPairs: [{ id: 'olema-present-e-1', focusIds: ['olema-present'], wrong: 'Mina on õpilane.', correct: 'Mina olen õpilane.' }, { id: 'olema-present-e-2', focusIds: ['olema-present'], wrong: 'Ta ei on tööl.', correct: 'Ta ei ole tööl.' }],
    translations: [{ id: 'olema-present-t-1', focusIds: ['olema-present'], sourceLang: 'ru', source: 'Я не учитель, я ученик.', target: 'Ma ei ole õpetaja, ma olen õpilane.', alternatives: [] }, { id: 'olema-present-t-2', focusIds: ['olema-present'], sourceLang: 'ru', source: 'Мы сегодня на курсе.', target: 'Me oleme täna kursusel.', alternatives: [] }],
    speakingPrompts: [], writingPrompts: [], successCriteria: [],
  },
  'present-common-verbs': {
    id: 'present-common-verbs',
    focus: { id: 'present-common-verbs', type: 'grammar', label: 'Sagedased tegusõnad olevikus', patterns: ['ma elan', 'ma töötan', 'ma õpin', 'ma räägin'], aliases: ['olevik', 'mina-vorm'] },
    vocabulary: vocabulary('present-common-verbs', [
      ['elan', 'elan', 'я живу', 'verb', 'present-common-verbs'],
      ['tootan', 'töötan', 'я работаю', 'verb', 'present-common-verbs'],
      ['opin', 'õpin', 'я учусь', 'verb', 'present-common-verbs'],
      ['raagin', 'räägin', 'я говорю', 'verb', 'present-common-verbs'],
      ['armastan', 'armastan', 'я люблю', 'verb', 'present-common-verbs'],
      ['elab', 'elab', 'он / она живёт', 'verb', 'present-common-verbs'],
      ['tootab', 'töötab', 'он / она работает', 'verb', 'present-common-verbs'],
      ['raagime', 'räägime', 'мы говорим', 'verb', 'present-common-verbs'],
    ]),
    contexts: [],
    sentences: sentences('present-common-verbs', [
      ['1', 'present-common-verbs', 'verbs-profile', 'Ma elan Tallinnas ja räägin vene keelt.'],
      ['2', 'present-common-verbs', 'verbs-class', 'Ma õpin õhtul eesti keelt.'],
      ['3', 'present-common-verbs', 'verbs-work', 'Ma töötan haiglas ja elan töökoha lähedal.'],
      ['4', 'present-common-verbs', 'verbs-profile', 'Minu sõber elab Tartus ja töötab koolis.'],
      ['5', 'present-common-verbs', 'verbs-class', 'Me räägime tunnis ainult eesti keelt.'],
    ]),
    dialogues: [{ id: 'present-common-verbs-d-1', focusIds: ['present-common-verbs'], contextIds: ['verbs-class'], speakers: ['Õpetaja', 'Õpilane'], lines: [{ who: 'Õpetaja', text: 'Kus sa [elad] ja mida sa teed?' }, { who: 'Õpilane', text: 'Ma elan Tallinnas, [töötan] poes ja õpin eesti keelt.' }] }],
    errorPairs: [{ id: 'present-common-verbs-e-1', focusIds: ['present-common-verbs'], wrong: 'Ma elad Tallinnas.', correct: 'Ma elan Tallinnas.' }, { id: 'present-common-verbs-e-2', focusIds: ['present-common-verbs'], wrong: 'Ta töötan koolis.', correct: 'Ta töötab koolis.' }],
    translations: [{ id: 'present-common-verbs-t-1', focusIds: ['present-common-verbs'], sourceLang: 'ru', source: 'Я живу в Таллинне и работаю в магазине.', target: 'Ma elan Tallinnas ja töötan poes.', alternatives: [] }, { id: 'present-common-verbs-t-2', focusIds: ['present-common-verbs'], sourceLang: 'ru', source: 'Она учит эстонский язык.', target: 'Ta õpib eesti keelt.', alternatives: [] }],
    speakingPrompts: prompts('present-common-verbs', 'sp', [['1', 'present-common-verbs', 'verbs-profile', 'Räägi kuue lausega, kus sa elad, töötad või õpid ja mis keeli sa räägid.']]),
    writingPrompts: prompts('present-common-verbs', 'wp', [['1', 'present-common-verbs', 'verbs-profile', 'Kirjuta 6–8 lauset endast. Kasuta vähemalt nelja erinevat oleviku tegusõna.']]),
    successCriteria: ['Ma kasutan olema-verbi ja sagedasi oleviku tegusõnu arusaadavalt enda kohta rääkides.'],
  },
  'personal-info': {
    id: 'personal-info',
    focus: { id: 'personal-info', type: 'communication', label: 'Isikuandmed ja ankeet', patterns: ['nimi', 'aadress', 'telefon', 'e-post'], aliases: ['isikuandmed', 'ankeet'] },
    vocabulary: vocabulary('personal-info', [
      ['nimi', 'nimi', 'имя', 'noun', 'personal-info'], ['aadress', 'aadress', 'адрес', 'noun', 'personal-info'], ['telefon', 'telefoninumber', 'номер телефона', 'noun', 'personal-info'], ['epost', 'e-posti aadress', 'электронная почта', 'noun', 'personal-info'], ['kodakondsus', 'kodakondsus', 'гражданство', 'noun', 'personal-info'], ['allkiri', 'allkiri', 'подпись', 'noun', 'personal-info'], ['vastus', 'vastus', 'ответ', 'noun', 'personal-info'],
    ]),
    contexts: [
      { id: 'form-course', label: 'Keelekursuse ankeet', tags: ['form'], names: ['Anna', 'Maksim'], times: ['09:00', '13:30', '18:00'] },
      { id: 'form-library', label: 'Raamatukogu kasutajakaart', tags: ['form'], names: ['Jelena', 'Marko'], times: ['10:00', '14:15', '17:45'] },
      { id: 'form-message', label: 'Sõnum õpetajale', tags: ['message'], names: ['Sofia', 'Andres'], times: ['08:30', '12:00', '19:00'] },
    ],
    sentences: sentences('personal-info', [
      ['1', 'personal-info', 'form-course', 'Minu nimi on Anna Petrova.'], ['2', 'personal-info', 'form-course', 'Minu telefoninumber on 5550 1234.'], ['3', 'personal-info', 'form-library', 'Minu aadress on Pargi tänav 8–12.'], ['4', 'personal-info', 'form-library', 'Minu kodakondsus on Ukraina.'], ['5', 'personal-info', 'form-message', 'Minu e-posti aadress on anna@example.ee.'], ['6', 'personal-info', 'form-message', 'Palun saatke vastus minu e-posti aadressile.'],
    ]),
    dialogues: [{ id: 'personal-info-d-1', focusIds: ['personal-info'], contextIds: ['form-course'], speakers: ['Sekretär', 'Õppija'], lines: [{ who: 'Sekretär', text: 'Palun öelge oma [nimi] ja telefoninumber.' }, { who: 'Õppija', text: 'Minu nimi on Anna Petrova ja [number] on 5550 1234.' }] }],
    errorPairs: [], translations: [],
    speakingPrompts: prompts('personal-info', 'sp', [['1', 'personal-info', 'form-course', 'Vasta õpetaja küsimustele ja anna suuliselt viis isikuandmet.']]),
    writingPrompts: prompts('personal-info', 'wp', [['1', 'personal-info', 'form-message', 'Kirjuta õpetajale 4–6 lauset: kes sa oled, kuidas sinuga ühendust saada ja millal saad tunnis osaleda.']]),
    successCriteria: ['Ma täidan lihtsa ankeedi ja annan kõik vajalikud kontaktandmed arusaadavalt.'],
  },
  'numbers-dates': {
    id: 'numbers-dates',
    focus: { id: 'numbers-dates', type: 'communication', label: 'Arvud, kuupäevad ja kontaktandmed', patterns: ['sünniaeg', 'kuupäev', 'telefoninumber'], aliases: ['arvud', 'kuupäevad'] },
    vocabulary: vocabulary('numbers-dates', [
      ['sunniaeg', 'sünniaeg', 'дата рождения', 'noun', 'numbers-dates'], ['kuupaev', 'kuupäev', 'дата', 'noun', 'numbers-dates'], ['aasta', 'aasta', 'год', 'noun', 'numbers-dates'], ['kuu', 'kuu', 'месяц', 'noun', 'numbers-dates'], ['number', 'number', 'номер', 'noun', 'numbers-dates'], ['kehtib', 'kehtib', 'действителен', 'verb', 'numbers-dates'], ['kell', 'kell', 'в … часов', 'noun', 'numbers-dates'], ['oige', 'õige', 'правильный', 'adjective', 'numbers-dates'],
    ]),
    contexts: [],
    sentences: sentences('numbers-dates', [
      ['1', 'numbers-dates', 'form-course', 'Minu sünniaeg on 5. juuli 1988.'], ['2', 'numbers-dates', 'form-library', 'Kaart kehtib kuni 31. detsembrini.'], ['3', 'numbers-dates', 'form-message', 'Tund algab 12. oktoobril kell 18.00.'], ['4', 'numbers-dates', 'form-course', 'Palun kirjutage kuupäev numbritega.'], ['5', 'numbers-dates', 'form-library', 'Kontrollige, kas telefoninumber on õige.'],
    ]),
    dialogues: [],
    errorPairs: [{ id: 'numbers-dates-e-1', focusIds: ['numbers-dates'], wrong: 'Minu sünniaeg on viis juuli.', correct: 'Minu sünniaeg on 5. juuli.' }, { id: 'numbers-dates-e-2', focusIds: ['numbers-dates'], wrong: 'Tund on kell kaheksateist null.', correct: 'Tund on kell kaheksateist.' }],
    translations: [{ id: 'numbers-dates-t-1', focusIds: ['numbers-dates'], sourceLang: 'ru', source: 'Моя дата рождения — 5 июля 1988 года.', target: 'Minu sünniaeg on 5. juuli 1988.', alternatives: [] }, { id: 'numbers-dates-t-2', focusIds: ['numbers-dates'], sourceLang: 'ru', source: 'Урок начинается 12 октября в 18 часов.', target: 'Tund algab 12. oktoobril kell 18.', alternatives: [] }],
    speakingPrompts: [], writingPrompts: [], successCriteria: [],
  },
  'family-relations': {
    id: 'family-relations',
    focus: { id: 'family-relations', type: 'communication', label: 'Pere ja lähedased', patterns: ['See on minu …', 'Kelle …?', 'Tal on …'], aliases: ['pere', 'lähedased', 'sugulased', 'kelle'] },
    vocabulary: vocabulary('family-relations', [
      ['ema', 'ema', 'мама', 'noun', 'family-relations'],
      ['isa', 'isa', 'папа', 'noun', 'family-relations'],
      ['ode', 'õde', 'сестра', 'noun', 'family-relations'],
      ['vend', 'vend', 'брат', 'noun', 'family-relations'],
      ['abikaasa', 'abikaasa', 'супруг / супруга', 'noun', 'family-relations'],
      ['tutar', 'tütar', 'дочь', 'noun', 'family-relations'],
      ['poeg', 'poeg', 'сын', 'noun', 'family-relations'],
      ['vanemad', 'vanemad', 'родители', 'noun', 'family-relations'],
      ['lapsed', 'lapsed', 'дети', 'noun', 'family-relations'],
      ['vanaema', 'vanaema', 'бабушка', 'noun', 'family-relations'],
      ['vanaisa', 'vanaisa', 'дедушка', 'noun', 'family-relations'],
      ['sugulane', 'sugulane', 'родственник', 'noun', 'family-relations'],
      ['sugulased', 'sugulased', 'родственники', 'noun', 'family-relations'],
      ['nimi', 'nimi', 'имя', 'noun', 'family-relations'],
      ['kolm-last', 'kolm last', 'трое детей', 'phrase', 'family-relations'],
    ]),
    contexts: [
      { id: 'family-tree', label: 'Perekonna sugupuu', tags: ['family', 'relations'], names: ['Mari', 'Jüri', 'Katrin', 'Martin'], times: ['10:00', '14:00', '18:00'] },
      { id: 'family-photo', label: 'Perefoto kirjeldamine', tags: ['family', 'description'], names: ['Anna', 'Maksim', 'Sofia', 'Aleksandr'], times: ['09:30', '15:15', '19:00'] },
      { id: 'family-visit', label: 'Külaskäik lähedaste juurde', tags: ['family', 'visit'], names: ['Olga', 'Viktor', 'Daria', 'Nikita'], times: ['11:00', '16:30', '20:00'] },
    ],
    sentences: sentences('family-relations', [
      ['1', 'family-relations', 'family-tree', 'See on minu ema Mari ja see on minu isa Jüri.'],
      ['2', 'family-relations', 'family-tree', 'Minu õe nimi on Katrin ja minu venna nimi on Martin.'],
      ['3', 'family-relations', 'family-tree', 'Kelle tütar on Sofia? Sofia on Anna tütar.'],
      ['4', 'family-relations', 'family-tree', 'Minu vanematel on kolm last.'],
      ['5', 'family-relations', 'family-photo', 'Fotol on minu abikaasa ja meie kaks last.'],
      ['6', 'family-relations', 'family-photo', 'Minu vanaema istub vasakul ja vanaisa seisab tema kõrval.'],
      ['7', 'family-relations', 'family-photo', 'Minu vend on kolmkümmend aastat vana ja töötab õpetajana.'],
      ['8', 'family-relations', 'family-visit', 'Laupäeval läheme lastega vanaema juurde.'],
      ['9', 'family-relations', 'family-visit', 'Minu sugulased elavad Tartus.'],
      ['10', 'family-relations', 'family-visit', 'Kas sinu õde tuleb ka külla?'],
    ]),
    dialogues: [{ id: 'family-relations-d-1', focusIds: ['family-relations'], contextIds: ['family-photo'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Kes on sellel fotol?' },
      { who: 'B', text: 'See on minu [õde] Sofia ja tema kõrval on meie vend Maksim.' },
      { who: 'A', text: 'Kas neil on lapsi?' },
      { who: 'B', text: 'Sofial on üks [tütar], aga Maksimil lapsi ei ole.' },
    ] }],
    errorPairs: [
      { id: 'family-relations-e-1', focusIds: ['family-relations'], wrong: 'Minu õde nimi on Sofia.', correct: 'Minu õe nimi on Sofia.' },
      { id: 'family-relations-e-2', focusIds: ['family-relations'], wrong: 'Tal on kaks laps.', correct: 'Tal on kaks last.' },
    ],
    translations: [
      { id: 'family-relations-t-1', focusIds: ['family-relations'], sourceLang: 'ru', source: 'Это моя сестра, а рядом с ней — её муж.', target: 'See on minu õde ja tema kõrval on tema abikaasa.', alternatives: [] },
      { id: 'family-relations-t-2', focusIds: ['family-relations'], sourceLang: 'ru', source: 'У моих родителей трое детей.', target: 'Minu vanematel on kolm last.', alternatives: [] },
    ],
    speakingPrompts: prompts('family-relations', 'sp', [
      ['1', 'family-relations', 'family-tree', 'Tutvusta oma peret või väljamõeldud perekonda. Nimeta vähemalt neli inimest ja lisa igaühe kohta üks detail.'],
      ['2', 'family-relations', 'family-photo', 'Kirjelda perefotot: kes on pildil, kuidas nad on omavahel seotud ja mida nad teevad.'],
    ]),
    writingPrompts: prompts('family-relations', 'wp', [
      ['1', 'family-relations', 'family-visit', 'Kirjuta 6–8 lauset oma perest või lähedastest. Kasuta vähemalt kuut peresõna ja kahte kelle-vormi.'],
    ]),
    successCriteria: ['Ma nimetan peresuhteid ja lisan vähemalt nelja inimese kohta ühe arusaadava detaili.'],
  },
  'possession-genitive': {
    id: 'possession-genitive',
    focus: { id: 'possession-genitive', type: 'grammar', label: 'Omastav ja omamine', patterns: ['minu / sinu / tema / meie / teie / nende', 'See on Mari kott.', 'Kelle oma see on?', 'See on minu venna oma.'], aliases: ['genitiiv', 'omastav', 'kelle oma'] },
    vocabulary: vocabulary('possession-genitive', [
      ['minu', 'minu', 'мой', 'pronoun', 'possession-genitive'],
      ['sinu', 'sinu', 'твой', 'pronoun', 'possession-genitive'],
      ['tema', 'tema', 'его / её', 'pronoun', 'possession-genitive'],
      ['meie', 'meie', 'наш', 'pronoun', 'possession-genitive'],
      ['teie', 'teie', 'ваш', 'pronoun', 'possession-genitive'],
      ['nende', 'nende', 'их', 'pronoun', 'possession-genitive'],
      ['kelle', 'kelle', 'чей / чья', 'pronoun', 'possession-genitive'],
      ['oma', 'oma', 'свой / принадлежащий', 'pronoun', 'possession-genitive'],
      ['venna', 'venna', 'брата (vend → venna)', 'noun', 'possession-genitive'],
      ['oe', 'õe', 'сестры (õde → õe)', 'noun', 'possession-genitive'],
      ['kott', 'kott', 'сумка', 'noun', 'possession-genitive'],
      ['voti', 'võti', 'ключ', 'noun', 'possession-genitive'],
      ['korter', 'korter', 'квартира', 'noun', 'possession-genitive'],
      ['vihik', 'vihik', 'тетрадь', 'noun', 'possession-genitive'],
      ['opetaja', 'õpetaja', 'учителя', 'noun', 'possession-genitive'],
    ]),
    contexts: [
      { id: 'possession-home', label: 'Pere asjad kodus', tags: ['family', 'home'], names: ['Mari', 'Martin', 'Katrin'], times: [] },
      { id: 'possession-lost', label: 'Kadunud asjade kast', tags: ['things', 'questions'], names: ['Anna', 'Toomas', 'Olga'], times: [] },
      { id: 'possession-labels', label: 'Nimesildid ja allkirjad', tags: ['labels', 'school'], names: ['Sofia', 'Jaan', 'Irina'], times: [] },
    ],
    sentences: sentences('possession-genitive', [
      ['1', 'possession-genitive', 'possession-home', 'See on minu ema telefon.'],
      ['2', 'possession-genitive', 'possession-home', 'Minu õe auto on punane.'],
      ['3', 'possession-genitive', 'possession-home', 'Meie korter on teisel korrusel.'],
      ['10', 'possession-genitive', 'possession-home', 'Tema isa töötab haiglas.'],
      ['4', 'possession-genitive', 'possession-lost', 'Kelle kott see on? See on Martini kott.'],
      ['5', 'possession-genitive', 'possession-lost', 'Kas see vihik on sinu oma? Ei, see on Anna oma.'],
      ['6', 'possession-genitive', 'possession-lost', 'See jope on minu venna oma.'],
      ['7', 'possession-genitive', 'possession-labels', 'Õpetaja laud on akna all.'],
      ['8', 'possession-genitive', 'possession-labels', 'Nende lapsed käivad samas koolis.'],
      ['9', 'possession-genitive', 'possession-labels', 'Teie võti on laual.'],
    ]),
    dialogues: [{ id: 'possession-genitive-d-1', focusIds: ['possession-genitive'], contextIds: ['possession-lost'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Vabandust, [kelle] kott see on?' },
      { who: 'B', text: 'See on minu [venna] kott. Ta unustas selle siia.' },
      { who: 'A', text: 'Ja kelle prillid need on?' },
      { who: 'B', text: 'Need on Mari [omad].' },
    ] }],
    errorPairs: [
      { id: 'possession-genitive-e-1', focusIds: ['possession-genitive'], wrong: 'See on minu vend auto.', correct: 'See on minu venna auto.' },
      { id: 'possession-genitive-e-2', focusIds: ['possession-genitive'], wrong: 'See raamat on mina oma.', correct: 'See raamat on minu oma.' },
      { id: 'possession-genitive-e-3', focusIds: ['possession-genitive'], wrong: 'Need prillid on Anna oma.', correct: 'Need prillid on Anna omad.' },
    ],
    translations: [
      { id: 'possession-genitive-t-1', focusIds: ['possession-genitive'], sourceLang: 'ru', source: 'Чья это сумка? — Это сумка моего брата.', target: 'Kelle kott see on? See on minu venna kott.', alternatives: ['Kelle kott see on? — See on minu venna kott.'] },
      { id: 'possession-genitive-t-2', focusIds: ['possession-genitive'], sourceLang: 'ru', source: 'Наша квартира на втором этаже.', target: 'Meie korter on teisel korrusel.', alternatives: [] },
    ],
    speakingPrompts: prompts('possession-genitive', 'sp', [
      ['1', 'possession-genitive', 'possession-home', 'Nimeta viis asja oma kodus ja ütle, kelle omad need on.'],
      ['2', 'possession-genitive', 'possession-lost', 'Mängi kadunud asjade kasti: küsi „Kelle … see on?” ja vasta täislausega.'],
    ]),
    writingPrompts: prompts('possession-genitive', 'wp', [
      ['1', 'possession-genitive', 'possession-home', 'Kirjuta 6–8 lauset oma pere asjadest. Kasuta vähemalt kuut omastava vormi, näiteks minu venna, Mari, meie.'],
    ]),
    successCriteria: ['Ma väljendan omamist ja suhteid omastavaga ning vastan küsimusele „Kelle oma see on?”.'],
  },
  'appearance-character': {
    id: 'appearance-character',
    focus: { id: 'appearance-character', type: 'vocabulary', label: 'Välimus ja iseloom', patterns: ['Ta on pikk / lühike.', 'Tal on tumedad juuksed.', 'väga / üsna / natuke'], aliases: ['välimus', 'iseloom', 'omadussõnad'] },
    vocabulary: vocabulary('appearance-character', [
      ['pikk', 'pikk', 'высокий', 'adjective', 'appearance-character'],
      ['luhike', 'lühike', 'невысокий', 'adjective', 'appearance-character'],
      ['noor', 'noor', 'молодой', 'adjective', 'appearance-character'],
      ['vanem', 'vanem', 'старше / пожилой', 'adjective', 'appearance-character'],
      ['heledad', 'heledad juuksed', 'светлые волосы', 'phrase', 'appearance-character'],
      ['tumedad', 'tumedad juuksed', 'тёмные волосы', 'phrase', 'appearance-character'],
      ['prillid', 'prillid', 'очки', 'noun', 'appearance-character'],
      ['sobralik', 'sõbralik', 'дружелюбный', 'adjective', 'appearance-character'],
      ['rahulik', 'rahulik', 'спокойный', 'adjective', 'appearance-character'],
      ['aktiivne', 'aktiivne', 'активный', 'adjective', 'appearance-character'],
      ['lobus', 'lõbus', 'весёлый', 'adjective', 'appearance-character'],
      ['tosine', 'tõsine', 'серьёзный', 'adjective', 'appearance-character'],
      ['abivalmis', 'abivalmis', 'готовый помочь', 'adjective', 'appearance-character'],
      ['habelik', 'häbelik', 'стеснительный', 'adjective', 'appearance-character'],
      ['juuksed', 'juuksed', 'волосы', 'noun', 'appearance-character'],
    ]),
    contexts: [
      { id: 'looks-photo', label: 'Inimesed fotol', tags: ['description', 'photo'], names: ['Anna', 'Jüri', 'Liis'], times: [] },
      { id: 'looks-guess', label: 'Arva ära, kes see on', tags: ['description', 'game'], names: ['Mari', 'Andrei', 'Kadri'], times: [] },
      { id: 'looks-compare', label: 'Kaks sõpra', tags: ['description', 'comparison'], names: ['Martin', 'Jüri', 'Daria'], times: [] },
    ],
    sentences: sentences('appearance-character', [
      ['1', 'appearance-character', 'looks-photo', 'Minu vend on pikk ja tal on tumedad juuksed.'],
      ['2', 'appearance-character', 'looks-photo', 'Fotol on noor naine, kellel on heledad juuksed.'],
      ['3', 'appearance-character', 'looks-photo', 'Anna on üsna lühike ja tal on prillid.'],
      ['4', 'appearance-character', 'looks-guess', 'See mees on väga sõbralik ja abivalmis.'],
      ['5', 'appearance-character', 'looks-guess', 'Ta on natuke tõsine, aga tegelikult väga lõbus.'],
      ['6', 'appearance-character', 'looks-guess', 'Kas tal on pikad või lühikesed juuksed?'],
      ['7', 'appearance-character', 'looks-compare', 'Mari on rahulik, aga tema õde on väga aktiivne.'],
      ['8', 'appearance-character', 'looks-compare', 'Jüri on vanem kui Martin, aga Martin on pikem.', 2],
      ['9', 'appearance-character', 'looks-compare', 'Daria on alguses häbelik, aga sõpradega väga lõbus.', 2],
    ]),
    dialogues: [{ id: 'appearance-character-d-1', focusIds: ['appearance-character'], contextIds: ['looks-guess'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Kas see inimene on mees või naine?' },
      { who: 'B', text: 'Naine. Ta on üsna [noor] ja tal on pikad heledad juuksed.' },
      { who: 'A', text: 'Milline ta iseloomult on?' },
      { who: 'B', text: 'Ta on väga [sõbralik] ja natuke häbelik.' },
    ] }],
    errorPairs: [
      { id: 'appearance-character-e-1', focusIds: ['appearance-character'], wrong: 'Tal on pikk juuksed.', correct: 'Tal on pikad juuksed.' },
      { id: 'appearance-character-e-2', focusIds: ['appearance-character'], wrong: 'Martin on pikk kui Jüri.', correct: 'Martin on pikem kui Jüri.' },
    ],
    translations: [
      { id: 'appearance-character-t-1', focusIds: ['appearance-character'], sourceLang: 'ru', source: 'Моя сестра довольно высокая и очень дружелюбная.', target: 'Minu õde on üsna pikk ja väga sõbralik.', alternatives: [] },
      { id: 'appearance-character-t-2', focusIds: ['appearance-character'], sourceLang: 'ru', source: 'У него тёмные волосы и очки.', target: 'Tal on tumedad juuksed ja prillid.', alternatives: [] },
    ],
    speakingPrompts: prompts('appearance-character', 'sp', [
      ['1', 'appearance-character', 'looks-photo', 'Kirjelda kaht inimest fotol: välimus ja iseloom. Kasuta sõnu väga, üsna ja natuke.'],
      ['2', 'appearance-character', 'looks-guess', 'Arvamismäng: kirjelda tuttavat inimest nime ütlemata, partner arvab, kes see on.'],
    ]),
    writingPrompts: prompts('appearance-character', 'wp', [
      ['1', 'appearance-character', 'looks-compare', 'Kirjuta 6–8 lauset oma sõbrast: milline ta välja näeb ja milline ta on. Kasuta vähemalt kümmet omadussõna.'],
    ]),
    successCriteria: ['Ma kirjeldan inimese välimust ja iseloomu ning kasutan vähemalt kümmet omadussõna.'],
  },
  'people-profiles': {
    id: 'people-profiles',
    focus: { id: 'people-profiles', type: 'communication', label: 'Lühikesed isikukirjeldused', patterns: ['Kes ta on?', 'Kui vana ta on?', 'Kus ta elab?', 'Mida ta teeb?'], aliases: ['minu inimesed', 'profiil', 'isikukirjeldus'] },
    vocabulary: vocabulary('people-profiles', [
      ['kes', 'kes', 'кто', 'pronoun', 'people-profiles'],
      ['milline', 'milline', 'какой', 'pronoun', 'people-profiles'],
      ['vana', 'vana', 'лет (о возрасте) / старый', 'adjective', 'people-profiles'],
      ['naaber', 'naaber', 'сосед', 'noun', 'people-profiles'],
      ['parit', 'pärit', 'родом', 'adverb', 'people-profiles'],
      ['elab', 'elab', 'живёт', 'verb', 'people-profiles'],
      ['tootab', 'töötab', 'работает', 'verb', 'people-profiles'],
      ['opib', 'õpib', 'учится', 'verb', 'people-profiles'],
      ['apteegis', 'apteegis', 'в аптеке', 'noun', 'people-profiles'],
      ['ulikoolis', 'ülikoolis', 'в университете', 'noun', 'people-profiles'],
      ['uhiselamus', 'ühiselamus', 'в общежитии', 'noun', 'people-profiles'],
      ['nadalavahetusel', 'nädalavahetusel', 'на выходных', 'adverb', 'people-profiles'],
      ['vabal-ajal', 'vabal ajal', 'в свободное время', 'phrase', 'people-profiles'],
    ]),
    contexts: [
      { id: 'profile-kati', label: 'Profiil: Kati', tags: ['profile', 'reading'], names: ['Kati'], times: [] },
      { id: 'profile-sergei', label: 'Profiil: Sergei', tags: ['profile', 'reading'], names: ['Sergei'], times: [] },
      { id: 'profile-liisa', label: 'Profiil: Liisa', tags: ['profile', 'reading'], names: ['Liisa'], times: [] },
    ],
    sentences: sentences('people-profiles', [
      ['1', 'people-profiles', 'profile-kati', 'Kati on kakskümmend kaheksa aastat vana ja elab Pärnus.'],
      ['2', 'people-profiles', 'profile-kati', 'Ta töötab apteegis ja käib õhtuti jooksmas.'],
      ['3', 'people-profiles', 'profile-kati', 'Mida Kati vabal ajal teeb? Ta jookseb ja loeb raamatuid.'],
      ['4', 'people-profiles', 'profile-sergei', 'Sergei on Kati naaber ja ta on pärit Narvast.'],
      ['5', 'people-profiles', 'profile-sergei', 'Sergei on viiskümmend aastat vana ja töötab bussijuhina.'],
      ['6', 'people-profiles', 'profile-sergei', 'Milline Sergei on? Ta on rahulik ja abivalmis.'],
      ['7', 'people-profiles', 'profile-liisa', 'Liisa on Sergei tütar ja õpib ülikoolis arstiks.'],
      ['8', 'people-profiles', 'profile-liisa', 'Liisa elab Tartus ühiselamus ja sõidab nädalavahetusel koju.'],
      ['9', 'people-profiles', 'profile-liisa', 'Kus Liisa elab? Ta elab Tartus.'],
      ['10', 'people-profiles', 'profile-kati', 'Kes on Kati? Kati on noor naine, kes töötab apteegis.'],
    ]),
    dialogues: [{ id: 'people-profiles-d-1', focusIds: ['people-profiles'], contextIds: ['profile-kati'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Kes see naine on?' },
      { who: 'B', text: 'See on Kati. Ta on minu [naaber].' },
      { who: 'A', text: 'Mida ta teeb?' },
      { who: 'B', text: 'Ta [töötab] apteegis ja käib õhtuti jooksmas.' },
    ] }],
    errorPairs: [
      { id: 'people-profiles-e-1', focusIds: ['people-profiles'], wrong: 'Kati on kakskümmend kaheksa aastat.', correct: 'Kati on kakskümmend kaheksa aastat vana.' },
      { id: 'people-profiles-e-2', focusIds: ['people-profiles'], wrong: 'Sergei on pärit Narva.', correct: 'Sergei on pärit Narvast.' },
    ],
    translations: [
      { id: 'people-profiles-t-1', focusIds: ['people-profiles'], sourceLang: 'ru', source: 'Лиза учится в университете и живёт в Тарту.', target: 'Liisa õpib ülikoolis ja elab Tartus.', alternatives: [] },
      { id: 'people-profiles-t-2', focusIds: ['people-profiles'], sourceLang: 'ru', source: 'Сергей родом из Нарвы.', target: 'Sergei on pärit Narvast.', alternatives: [] },
    ],
    speakingPrompts: prompts('people-profiles', 'sp', [
      ['1', 'people-profiles', 'profile-sergei', 'Jutusta ühe profiili põhjal 5–6 lausega: kes see inimene on, kus ta elab ja mida ta teeb.'],
      ['2', 'people-profiles', 'profile-liisa', 'Küsi partnerilt tema tuttava kohta: kes ta on, kui vana ta on, kus ta elab ja mida ta teeb.'],
    ]),
    writingPrompts: prompts('people-profiles', 'wp', [
      ['1', 'people-profiles', 'profile-kati', 'Kirjuta 5–6 lauseline profiil ühest oma lähedasest: kes ta on, kui vana ta on, kus ta elab ja mida ta teeb.'],
    ]),
    successCriteria: ['Ma leian lühikesest isikukirjeldusest faktid ja jutustan selle 5–6 lausega ümber.'],
  },
  'daily-routine': {
    id: 'daily-routine',
    focus: { id: 'daily-routine', type: 'communication', label: 'Minu tavaline päev', patterns: ['hommikul / päeval / õhtul / öösel', 'Hommikul ärkan kell …', 'Õhtul tulen koju.'], aliases: ['päevakava', 'minu päev', 'ajamäärused'] },
    vocabulary: vocabulary('daily-routine', [
      ['hommikul', 'hommikul', 'утром', 'adverb', 'daily-routine'],
      ['paeval', 'päeval', 'днём', 'adverb', 'daily-routine'],
      ['ohtul', 'õhtul', 'вечером', 'adverb', 'daily-routine'],
      ['oosel', 'öösel', 'ночью', 'adverb', 'daily-routine'],
      ['arkan', 'ärkan', 'я просыпаюсь', 'verb', 'daily-routine'],
      ['lahen', 'lähen', 'я иду / еду', 'verb', 'daily-routine'],
      ['tulen', 'tulen', 'я прихожу', 'verb', 'daily-routine'],
      ['tootan', 'töötan', 'я работаю', 'verb', 'daily-routine'],
      ['puhkan', 'puhkan', 'я отдыхаю', 'verb', 'daily-routine'],
      ['soon', 'söön', 'я ем', 'verb', 'daily-routine'],
      ['magan', 'magan', 'я сплю', 'verb', 'daily-routine'],
      ['koju', 'koju', 'домой', 'adverb', 'daily-routine'],
    ]),
    contexts: [
      { id: 'day-workday', label: 'Tavaline tööpäev', tags: ['routine', 'work'], names: ['Mari', 'Andrei'], times: ['06:30', '08:00', '17:30', '22:45'] },
      { id: 'day-weekend', label: 'Puhkepäev', tags: ['routine', 'weekend'], names: ['Kadri', 'Sergei'], times: ['09:15', '13:00', '19:30'] },
      { id: 'day-student', label: 'Õpilase päev', tags: ['routine', 'study'], names: ['Liisa', 'Nikita'], times: ['07:00', '15:45', '21:00'] },
    ],
    sentences: sentences('daily-routine', [
      ['1', 'daily-routine', 'day-workday', 'Hommikul ärkan kell seitse.'],
      ['2', 'daily-routine', 'day-workday', 'Päeval töötan kontoris.'],
      ['3', 'daily-routine', 'day-workday', 'Õhtul tulen koju ja teen süüa.'],
      ['4', 'daily-routine', 'day-weekend', 'Laupäeval ärkan hilja ja puhkan terve päeva.'],
      ['5', 'daily-routine', 'day-weekend', 'Pühapäeval lähen sõpradega jalutama.'],
      ['6', 'daily-routine', 'day-weekend', 'Öösel magan kaheksa tundi.'],
      ['7', 'daily-routine', 'day-student', 'Hommikul joon teed ja söön putru.'],
      ['8', 'daily-routine', 'day-student', 'Pärast kooli lähen trenni.'],
      ['9', 'daily-routine', 'day-student', 'Õhtul õpin ja loen raamatut.'],
    ]),
    dialogues: [{ id: 'daily-routine-d-1', focusIds: ['daily-routine'], contextIds: ['day-workday'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Mis kell sa tavaliselt ärkad?' },
      { who: 'B', text: 'Tööpäeval ärkan kell kuus, aga laupäeval [magan] kauem.' },
      { who: 'A', text: 'Mida sa õhtul teed?' },
      { who: 'B', text: 'Õhtul [tulen] koju ja vaatan uudiseid.' },
    ] }],
    errorPairs: [
      { id: 'daily-routine-e-1', focusIds: ['daily-routine'], wrong: 'Õhtus tulen koju.', correct: 'Õhtul tulen koju.' },
      { id: 'daily-routine-e-2', focusIds: ['daily-routine'], wrong: 'Ma lähen kodu kell viis.', correct: 'Ma lähen koju kell viis.' },
    ],
    translations: [
      { id: 'daily-routine-t-1', focusIds: ['daily-routine'], sourceLang: 'ru', source: 'Утром я встаю в семь часов.', target: 'Hommikul ärkan kell seitse.', alternatives: ['Ma ärkan hommikul kell seitse.'] },
      { id: 'daily-routine-t-2', focusIds: ['daily-routine'], sourceLang: 'ru', source: 'Вечером я прихожу домой и отдыхаю.', target: 'Õhtul tulen koju ja puhkan.', alternatives: [] },
    ],
    speakingPrompts: prompts('daily-routine', 'sp', [
      ['1', 'daily-routine', 'day-workday', 'Räägi poolteist minutit oma tavalisest päevast. Kasuta vähemalt kuut ajamäärust.'],
      ['2', 'daily-routine', 'day-weekend', 'Võrdle oma tööpäeva ja puhkepäeva: mis on samamoodi, mis on teisiti?'],
    ]),
    writingPrompts: prompts('daily-routine', 'wp', [
      ['1', 'daily-routine', 'day-student', 'Kirjuta 6–8 lauset oma tavalisest päevast hommikust õhtuni.'],
    ]),
    successCriteria: ['Ma kirjeldan oma tavalist päeva järjest ja kasutan vähemalt kuut ajamäärust.'],
  },
  'clock-time': {
    id: 'clock-time',
    focus: { id: 'clock-time', type: 'grammar', label: 'Kellaaeg, algus, lõpp ja kestus', patterns: ['kell kuus / pool seitse / veerand seitse / kolmveerand seitse', 'alates kella üheksast kuni kella kaheksani', 'enne tundi / pärast tööd'], aliases: ['kellaaeg', 'ajaväljendid'] },
    vocabulary: vocabulary('clock-time', [
      ['kell', 'kell', 'в … часов / часы', 'noun', 'clock-time'],
      ['pool', 'pool', 'половина (pool seitse = 6:30)', 'numeral', 'clock-time'],
      ['veerand', 'veerand', 'четверть (veerand kolm = 2:15)', 'numeral', 'clock-time'],
      ['kolmveerand', 'kolmveerand', 'без четверти (kolmveerand kümme = 9:45)', 'numeral', 'clock-time'],
      ['alates', 'alates', 'начиная с', 'adposition', 'clock-time'],
      ['kuni', 'kuni', 'до', 'adposition', 'clock-time'],
      ['enne', 'enne', 'перед (enne tundi = перед уроком)', 'adposition', 'clock-time'],
      ['parast', 'pärast', 'после', 'adposition', 'clock-time'],
      ['algab', 'algab', 'начинается', 'verb', 'clock-time'],
      ['lopeb', 'lõpeb', 'заканчивается', 'verb', 'clock-time'],
      ['kestab', 'kestab', 'длится', 'verb', 'clock-time'],
      ['tundi', 'tundi', 'часа / часов (kaks tundi)', 'noun', 'clock-time'],
    ]),
    contexts: [
      { id: 'time-schedule', label: 'Kursuse tunniplaan', tags: ['time', 'schedule'], names: ['Mari', 'Toomas'], times: ['18:00', '19:30', '10:15'] },
      { id: 'time-phone', label: 'Info telefoni teel', tags: ['time', 'phone'], names: ['Olga', 'Jaan'], times: ['09:00', '20:00', '14:45'] },
      { id: 'time-meeting', label: 'Kohtumise kokkuleppimine', tags: ['time', 'meeting'], names: ['Kadri', 'Maksim'], times: ['14:15', '13:30', '09:45'] },
    ],
    sentences: sentences('clock-time', [
      ['1', 'clock-time', 'time-schedule', 'Tund algab kell kuus ja lõpeb kell pool kaheksa.'],
      ['2', 'clock-time', 'time-schedule', 'Kursus kestab kaks tundi.'],
      ['3', 'clock-time', 'time-schedule', 'Enne tundi joon kohvi.'],
      ['4', 'clock-time', 'time-phone', 'Pood on avatud alates kella üheksast kuni kella kaheksani.', 2],
      ['5', 'clock-time', 'time-phone', 'Arsti vastuvõtt on kell kolmveerand kümme.'],
      ['6', 'clock-time', 'time-phone', 'Vabandust, mis kell on? Kell on pool kaks.'],
      ['7', 'clock-time', 'time-meeting', 'Kohtume kell veerand kolm kohviku ees.'],
      ['8', 'clock-time', 'time-meeting', 'Pärast tööd lähen poodi.'],
      ['9', 'clock-time', 'time-meeting', 'Koosolek kestab umbes pool tundi.'],
    ]),
    dialogues: [{ id: 'clock-time-d-1', focusIds: ['clock-time'], contextIds: ['time-phone'], speakers: ['Klient', 'Müüja'], lines: [
      { who: 'Klient', text: 'Tere! Mis kellast teie pood avatud on?' },
      { who: 'Müüja', text: 'Pood on avatud [alates] kella üheksast [kuni] kella kaheksani.' },
      { who: 'Klient', text: 'Aitäh! Kas laupäeval ka?' },
      { who: 'Müüja', text: 'Laupäeval on pood avatud kella kümnest kella neljani.' },
    ] }],
    errorPairs: [
      { id: 'clock-time-e-1', focusIds: ['clock-time'], wrong: 'Pood on avatud alates kell üheksa.', correct: 'Pood on avatud alates kella üheksast.' },
      { id: 'clock-time-e-2', focusIds: ['clock-time'], wrong: 'Pärast tööst lähen poodi.', correct: 'Pärast tööd lähen poodi.' },
    ],
    translations: [
      { id: 'clock-time-t-1', focusIds: ['clock-time'], sourceLang: 'ru', source: 'Урок начинается в половине седьмого.', target: 'Tund algab kell pool seitse.', alternatives: [] },
      { id: 'clock-time-t-2', focusIds: ['clock-time'], sourceLang: 'ru', source: 'Магазин открыт с девяти до восьми.', target: 'Pood on avatud kella üheksast kella kaheksani.', alternatives: ['Pood on avatud alates kella üheksast kuni kella kaheksani.'] },
    ],
    speakingPrompts: prompts('clock-time', 'sp', [
      ['1', 'clock-time', 'time-phone', 'Helista kursuse sekretärile: küsi, millal tund algab ja lõpeb ning kui kaua paus kestab.'],
      ['2', 'clock-time', 'time-schedule', 'Ütle, mis kell sa tavaliselt tööd alustad ja lõpetad ning mida teed enne ja pärast seda.'],
    ]),
    writingPrompts: prompts('clock-time', 'wp', [
      ['1', 'clock-time', 'time-meeting', 'Kirjuta sõbrale lühike sõnum: millal ja kus te kohtute ning kui kaua kohtumine kestab.'],
    ]),
    successCriteria: ['Ma ütlen ja mõistan kellaaegu, algust, lõppu ja kestust ning kasutan väljendeid enne ja pärast.'],
  },
  frequency: {
    id: 'frequency',
    focus: { id: 'frequency', type: 'grammar', label: 'Kui tihti? Sagedus ja sõnajärg', patterns: ['alati / tavaliselt / sageli / mõnikord / harva', 'Ma ei … mitte kunagi.', 'kord nädalas / iga päev'], aliases: ['sagedus', 'kui tihti'] },
    vocabulary: vocabulary('frequency', [
      ['alati', 'alati', 'всегда', 'adverb', 'frequency'],
      ['tavaliselt', 'tavaliselt', 'обычно', 'adverb', 'frequency'],
      ['sageli', 'sageli', 'часто', 'adverb', 'frequency'],
      ['monikord', 'mõnikord', 'иногда', 'adverb', 'frequency'],
      ['harva', 'harva', 'редко', 'adverb', 'frequency'],
      ['mitte-kunagi', 'mitte kunagi', 'никогда', 'adverb', 'frequency'],
      ['iga-paev', 'iga päev', 'каждый день', 'adverb', 'frequency'],
      ['kord-nadalas', 'kord nädalas', 'раз в неделю', 'adverb', 'frequency'],
      ['kui-tihti', 'kui tihti', 'как часто', 'phrase', 'frequency'],
      ['kain', 'käin', 'я хожу / посещаю', 'verb', 'frequency'],
      ['kaks-korda', 'kaks korda nädalas', 'два раза в неделю', 'adverb', 'frequency'],
      ['uks-kord', 'üks kord', 'один раз', 'adverb', 'frequency'],
    ]),
    contexts: [
      { id: 'habits-interview', label: 'Intervjuu harjumustest', tags: ['habits', 'interview'], names: ['Anna', 'Martin'], times: [] },
      { id: 'habits-health', label: 'Tervislikud harjumused', tags: ['habits', 'health'], names: ['Kati', 'Viktor'], times: [] },
      { id: 'habits-home', label: 'Kodused tööd', tags: ['habits', 'home'], names: ['Olga', 'Jüri'], times: [] },
    ],
    sentences: sentences('frequency', [
      ['1', 'frequency', 'habits-interview', 'Kui tihti sa sporti teed?'],
      ['2', 'frequency', 'habits-interview', 'Tavaliselt sõidan tööle bussiga.'],
      ['3', 'frequency', 'habits-interview', 'Mõnikord vaatan õhtul filmi.'],
      ['4', 'frequency', 'habits-health', 'Ma joon hommikul alati klaasi vett.'],
      ['5', 'frequency', 'habits-health', 'Ta käib sageli ujumas.'],
      ['6', 'frequency', 'habits-health', 'Ma ei suitseta mitte kunagi.'],
      ['7', 'frequency', 'habits-home', 'Ma koristan kodu kord nädalas.'],
      ['8', 'frequency', 'habits-home', 'Ta jalutab koeraga iga päev.'],
      ['9', 'frequency', 'habits-home', 'Me sööme väljas harva.'],
    ]),
    dialogues: [{ id: 'frequency-d-1', focusIds: ['frequency'], contextIds: ['habits-interview'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: '[Kui tihti] sa trennis käid?' },
      { who: 'B', text: 'Ma käin trennis kaks korda nädalas, aga [mõnikord] ainult üks kord.' },
      { who: 'A', text: 'Kas sa sööd hommikust?' },
      { who: 'B', text: 'Jah, ma söön hommikust [alati].' },
    ] }],
    errorPairs: [
      { id: 'frequency-e-1', focusIds: ['frequency'], wrong: 'Ma mitte kunagi suitsetan.', correct: 'Ma ei suitseta mitte kunagi.' },
      { id: 'frequency-e-2', focusIds: ['frequency'], wrong: 'Ma käin kino harva.', correct: 'Ma käin kinos harva.' },
    ],
    translations: [
      { id: 'frequency-t-1', focusIds: ['frequency'], sourceLang: 'ru', source: 'Обычно я хожу на работу пешком.', target: 'Tavaliselt lähen tööle jala.', alternatives: ['Ma lähen tavaliselt tööle jala.'] },
      { id: 'frequency-t-2', focusIds: ['frequency'], sourceLang: 'ru', source: 'Она никогда не пьёт кофе.', target: 'Ta ei joo kunagi kohvi.', alternatives: ['Ta ei joo mitte kunagi kohvi.'] },
    ],
    speakingPrompts: prompts('frequency', 'sp', [
      ['1', 'frequency', 'habits-interview', 'Intervjueeri õpetajat tema harjumuste kohta: küsi vähemalt viis „Kui tihti …?” küsimust.'],
      ['2', 'frequency', 'habits-health', 'Räägi oma tervislikest ja vähem tervislikest harjumustest. Kasuta vähemalt viit sagedust väljendavat sõna.'],
    ]),
    writingPrompts: prompts('frequency', 'wp', [
      ['1', 'frequency', 'habits-home', 'Kirjuta 6–8 lauset oma harjumustest. Kasuta sõnu alati, tavaliselt, sageli, mõnikord, harva ja mitte kunagi.'],
    ]),
    successCriteria: ['Ma ütlen, kui tihti ma midagi teen, ja panen sagedust väljendava sõna lauses loomulikku kohta.'],
  },
  'week-plan': {
    id: 'week-plan',
    focus: { id: 'week-plan', type: 'communication', label: 'Minu nädal ja plaanid', patterns: ['esmaspäeval … / nädalavahetusel …', 'siis / pärast seda', 'ja / aga'], aliases: ['nädal', 'nädalaplaan', 'sidesõnad'] },
    vocabulary: vocabulary('week-plan', [
      ['esmaspaeval', 'esmaspäeval', 'в понедельник', 'adverb', 'week-plan'],
      ['teisipaeval', 'teisipäeval', 'во вторник', 'adverb', 'week-plan'],
      ['kolmapaeval', 'kolmapäeval', 'в среду', 'adverb', 'week-plan'],
      ['neljapaeval', 'neljapäeval', 'в четверг', 'adverb', 'week-plan'],
      ['reedel', 'reedel', 'в пятницу', 'adverb', 'week-plan'],
      ['laupaeval', 'laupäeval', 'в субботу', 'adverb', 'week-plan'],
      ['puhapaeval', 'pühapäeval', 'в воскресенье', 'adverb', 'week-plan'],
      ['nadalavahetusel', 'nädalavahetusel', 'на выходных', 'adverb', 'week-plan'],
      ['siis', 'siis', 'потом', 'conjunction', 'week-plan'],
      ['parast-seda', 'pärast seda', 'после этого', 'phrase', 'week-plan'],
      ['aga', 'aga', 'но', 'conjunction', 'week-plan'],
      ['ja', 'ja', 'и', 'conjunction', 'week-plan'],
    ]),
    contexts: [
      { id: 'week-work', label: 'Töönädal', tags: ['week', 'work'], names: ['Mari', 'Sergei'], times: [] },
      { id: 'week-family', label: 'Pere nädalaplaan', tags: ['week', 'family'], names: ['Kadri', 'Jüri'], times: [] },
      { id: 'week-course', label: 'Kursuse nädal', tags: ['week', 'study'], names: ['Liisa', 'Andrei'], times: [] },
    ],
    sentences: sentences('week-plan', [
      ['1', 'week-plan', 'week-work', 'Esmaspäeval töötan kella üheksast kella viieni.'],
      ['2', 'week-plan', 'week-work', 'Kolmapäeval lähen pärast tööd poodi, siis teen kodus süüa.'],
      ['3', 'week-plan', 'week-work', 'Reedel kohtun pärast tööd sõpradega.'],
      ['4', 'week-plan', 'week-family', 'Laupäeval koristame kodu ja pärast seda puhkame.'],
      ['5', 'week-plan', 'week-family', 'Pühapäeval sõidame vanemate juurde.'],
      ['6', 'week-plan', 'week-family', 'Nädalavahetusel tahan kaua magada, aga lapsed ärkavad vara.'],
      ['7', 'week-plan', 'week-course', 'Teisipäeval ja neljapäeval on mul eesti keele tund.'],
      ['8', 'week-plan', 'week-course', 'Neljapäeval kirjutan kodutöö ja siis kordan sõnu.'],
    ]),
    dialogues: [{ id: 'week-plan-d-1', focusIds: ['week-plan'], contextIds: ['week-work'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Mida sa [reedel] teed?' },
      { who: 'B', text: 'Reedel töötan kella neljani ja [siis] lähen trenni.' },
      { who: 'A', text: 'Kas nädalavahetusel oled vaba?' },
      { who: 'B', text: 'Laupäeval jah, [aga] pühapäeval sõidan ema juurde.' },
    ] }],
    errorPairs: [
      { id: 'week-plan-e-1', focusIds: ['week-plan'], wrong: 'Laupäevas koristan kodu.', correct: 'Laupäeval koristan kodu.' },
      { id: 'week-plan-e-2', focusIds: ['week-plan'], wrong: 'Esmaspäev ma töötan kella viieni.', correct: 'Esmaspäeval töötan kella viieni.' },
    ],
    translations: [
      { id: 'week-plan-t-1', focusIds: ['week-plan'], sourceLang: 'ru', source: 'В среду после работы я иду в магазин.', target: 'Kolmapäeval lähen pärast tööd poodi.', alternatives: [] },
      { id: 'week-plan-t-2', focusIds: ['week-plan'], sourceLang: 'ru', source: 'На выходных я хочу отдохнуть.', target: 'Nädalavahetusel tahan puhata.', alternatives: [] },
    ],
    speakingPrompts: prompts('week-plan', 'sp', [
      ['1', 'week-plan', 'week-family', 'Räägi oma järgmisest nädalast päev-päevalt. Kasuta sõnu siis, pärast seda ja aga.'],
    ]),
    writingPrompts: prompts('week-plan', 'wp', [
      ['1', 'week-plan', 'week-course', 'Kirjuta 70–90 sõnaline tekst oma nädalast. Kasuta vähemalt viit ajamäärust või sidesõna, näiteks esmaspäeval, siis, pärast seda, aga, nädalavahetusel.'],
    ]),
    successCriteria: ['Ma kirjutan oma nädalast järjestatud teksti ja kasutan vähemalt viit ajamäärust või sidesõna.'],
  },
  'home-rooms': {
    id: 'home-rooms',
    focus: { id: 'home-rooms', type: 'vocabulary', label: 'Kodu, ruumid ja mööbel', patterns: ['Minu korteris on …', 'Elutoas on …', '… asub … kõrval'], aliases: ['kodu', 'ruumid', 'mööbel'] },
    vocabulary: vocabulary('home-rooms', [
      ['tuba', 'tuba', 'комната', 'noun', 'home-rooms'],
      ['kook', 'köök', 'кухня', 'noun', 'home-rooms'],
      ['vannituba', 'vannituba', 'ванная комната', 'noun', 'home-rooms'],
      ['esik', 'esik', 'прихожая', 'noun', 'home-rooms'],
      ['rodu', 'rõdu', 'балкон', 'noun', 'home-rooms'],
      ['magamistuba', 'magamistuba', 'спальня', 'noun', 'home-rooms'],
      ['elutuba', 'elutuba', 'гостиная', 'noun', 'home-rooms'],
      ['laud', 'laud', 'стол', 'noun', 'home-rooms'],
      ['tool', 'tool', 'стул', 'noun', 'home-rooms'],
      ['diivan', 'diivan', 'диван', 'noun', 'home-rooms'],
      ['voodi', 'voodi', 'кровать', 'noun', 'home-rooms'],
      ['kapp', 'kapp', 'шкаф', 'noun', 'home-rooms'],
    ]),
    contexts: [
      { id: 'home-plan', label: 'Korteri plaan', tags: ['home', 'plan'], names: ['Anna', 'Maksim'], times: [] },
      { id: 'home-room', label: 'Elutoa kirjeldus', tags: ['home', 'room'], names: ['Mari', 'Jaan'], times: [] },
      { id: 'home-compare', label: 'Kaks erinevat kodu', tags: ['home', 'comparison'], names: ['Olga', 'Martin'], times: [] },
    ],
    sentences: sentences('home-rooms', [
      ['1', 'home-rooms', 'home-plan', 'Minu korteris on kaks tuba ja väike köök.'],
      ['2', 'home-rooms', 'home-plan', 'Vannituba asub esiku kõrval.'],
      ['3', 'home-rooms', 'home-plan', 'Elutoast saab minna rõdule.'],
      ['4', 'home-rooms', 'home-room', 'Elutoas on diivan, laud ja neli tooli.'],
      ['5', 'home-rooms', 'home-room', 'Magamistoas on voodi ja suur kapp.'],
      ['6', 'home-rooms', 'home-room', 'Köögis on väike laud ja kaks tooli.'],
      ['7', 'home-rooms', 'home-compare', 'Anna korter on väike, aga väga valgusküllane.'],
      ['8', 'home-rooms', 'home-compare', 'Martini majas on kolm magamistuba ja suur elutuba.'],
      ['9', 'home-rooms', 'home-compare', 'Mõlemas kodus on rõdu, aga ainult ühes on eraldi köök.'],
    ]),
    dialogues: [{ id: 'home-rooms-d-1', focusIds: ['home-rooms'], contextIds: ['home-plan'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Mitu [tuba] sinu korteris on?' },
      { who: 'B', text: 'Kolm tuba. Elutoa kõrval on [köök].' },
      { who: 'A', text: 'Kas sul on rõdu?' },
      { who: 'B', text: 'Jah, rõdule saab minna [elutoast].' },
    ] }],
    errorPairs: [
      { id: 'home-rooms-e-1', focusIds: ['home-rooms'], wrong: 'Minu korter on kaks tuba.', correct: 'Minu korteris on kaks tuba.' },
      { id: 'home-rooms-e-2', focusIds: ['home-rooms'], wrong: 'Elutoas on üks laud ja kaks tool.', correct: 'Elutoas on üks laud ja kaks tooli.' },
      { id: 'home-rooms-e-3', focusIds: ['home-rooms'], wrong: 'Vannituba on esik kõrval.', correct: 'Vannituba on esiku kõrval.' },
    ],
    translations: [
      { id: 'home-rooms-t-1', focusIds: ['home-rooms'], sourceLang: 'ru', source: 'В моей квартире две комнаты и маленькая кухня.', target: 'Minu korteris on kaks tuba ja väike köök.', alternatives: [] },
      { id: 'home-rooms-t-2', focusIds: ['home-rooms'], sourceLang: 'ru', source: 'В спальне есть кровать и большой шкаф.', target: 'Magamistoas on voodi ja suur kapp.', alternatives: [] },
    ],
    transformations: [
      { id: 'home-rooms-tr-1', focusIds: ['home-rooms'], from: 'Elutoas on üks tool.', prompt: 'Muuda mitmuseks: kolm.', answer: 'Elutoas on kolm tooli.', alternatives: [] },
      { id: 'home-rooms-tr-2', focusIds: ['home-rooms'], from: 'Minu korteris on väike köök.', prompt: 'Lisa kontrast: elutuba on suur.', answer: 'Minu korteris on väike köök, aga elutuba on suur.', alternatives: [] },
    ],
    listeningScripts: [],
    speakingPrompts: prompts('home-rooms', 'sp', [
      ['1', 'home-rooms', 'home-plan', 'Kirjelda oma kodu 7–9 lausega: mitu tuba seal on, millised ruumid ja mööbel sul on.'],
      ['2', 'home-rooms', 'home-compare', 'Võrdle kahte kodu. Ütle vähemalt kolm erinevust ja üks sarnasus.'],
    ]),
    writingPrompts: prompts('home-rooms', 'wp', [
      ['1', 'home-rooms', 'home-room', 'Kirjuta 60–80 sõna oma kodust. Kirjelda vähemalt kolme ruumi ja viit mööblieset.'],
    ]),
    successCriteria: ['Ma kirjeldan oma kodu 7–9 lausega ning nimetan ruume ja põhilisi mööbliesemeid.'],
  },
  'inner-local-cases': {
    id: 'inner-local-cases',
    focus: { id: 'inner-local-cases', type: 'grammar', label: 'Kus? Kuhu? Kust? — sees', patterns: ['kodus / koju / kodust', 'poes / poodi / poest', 'toas / tuppa / toast'], aliases: ['sisekohakäänded', 'kus kuhu kust', '-s -sse -st'] },
    vocabulary: vocabulary('inner-local-cases', [
      ['kodus', 'kodus', 'дома (где?)', 'adverb', 'inner-local-cases'],
      ['koju', 'koju', 'домой (куда?)', 'adverb', 'inner-local-cases'],
      ['kodust', 'kodust', 'из дома (откуда?)', 'adverb', 'inner-local-cases'],
      ['poes', 'poes', 'в магазине', 'noun-form', 'inner-local-cases'],
      ['poodi', 'poodi', 'в магазин', 'noun-form', 'inner-local-cases'],
      ['poest', 'poest', 'из магазина', 'noun-form', 'inner-local-cases'],
      ['koolis', 'koolis', 'в школе', 'noun-form', 'inner-local-cases'],
      ['kooli', 'kooli', 'в школу', 'noun-form', 'inner-local-cases'],
      ['koolist', 'koolist', 'из школы', 'noun-form', 'inner-local-cases'],
      ['toas', 'toas', 'в комнате', 'noun-form', 'inner-local-cases'],
      ['tuppa', 'tuppa', 'в комнату', 'noun-form', 'inner-local-cases'],
      ['toast', 'toast', 'из комнаты', 'noun-form', 'inner-local-cases'],
    ]),
    contexts: [
      { id: 'inner-home', label: 'Liikumine kodus', tags: ['home', 'movement'], names: ['Mari', 'Jüri'], times: [] },
      { id: 'inner-errands', label: 'Kodust poodi ja tagasi', tags: ['errands', 'movement'], names: ['Anna', 'Sergei'], times: [] },
      { id: 'inner-school', label: 'Koolipäev', tags: ['school', 'movement'], names: ['Liisa', 'Nikita'], times: [] },
    ],
    sentences: sentences('inner-local-cases', [
      ['1', 'inner-local-cases', 'inner-home', 'Laps mängib toas.'],
      ['2', 'inner-local-cases', 'inner-home', 'Laps läheb tuppa.'],
      ['3', 'inner-local-cases', 'inner-home', 'Laps tuleb toast kööki.'],
      ['4', 'inner-local-cases', 'inner-errands', 'Hommikul olen kodus.'],
      ['5', 'inner-local-cases', 'inner-errands', 'Pärast tööd lähen poodi ja siis koju.'],
      ['6', 'inner-local-cases', 'inner-errands', 'Tulime poest kell kuus.'],
      ['7', 'inner-local-cases', 'inner-school', 'Lapsed on koolis kella kolmeni.'],
      ['8', 'inner-local-cases', 'inner-school', 'Hommikul lähevad lapsed kooli.'],
      ['9', 'inner-local-cases', 'inner-school', 'Pärast tundi tulevad nad koolist koju.'],
    ]),
    dialogues: [{ id: 'inner-local-cases-d-1', focusIds: ['inner-local-cases'], contextIds: ['inner-errands'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Kus sa praegu oled?' },
      { who: 'B', text: 'Olen [poes].' },
      { who: 'A', text: 'Kuhu sa pärast lähed?' },
      { who: 'B', text: 'Lähen [koju].' },
    ] }],
    errorPairs: [
      { id: 'inner-local-cases-e-1', focusIds: ['inner-local-cases'], wrong: 'Ma lähen poes.', correct: 'Ma lähen poodi.' },
      { id: 'inner-local-cases-e-2', focusIds: ['inner-local-cases'], wrong: 'Ta tuleb kooli.', correct: 'Ta tuleb koolist.' },
      { id: 'inner-local-cases-e-3', focusIds: ['inner-local-cases'], wrong: 'Laps mängib tuppa.', correct: 'Laps mängib toas.' },
    ],
    translations: [
      { id: 'inner-local-cases-t-1', focusIds: ['inner-local-cases'], sourceLang: 'ru', source: 'После работы я иду в магазин.', target: 'Pärast tööd lähen poodi.', alternatives: [] },
      { id: 'inner-local-cases-t-2', focusIds: ['inner-local-cases'], sourceLang: 'ru', source: 'Дети возвращаются из школы домой.', target: 'Lapsed tulevad koolist koju.', alternatives: [] },
    ],
    transformations: [
      { id: 'inner-local-cases-tr-1', focusIds: ['inner-local-cases'], from: 'Ma olen kodus.', prompt: 'Muuda: kuhu?', answer: 'Ma lähen koju.', alternatives: [] },
      { id: 'inner-local-cases-tr-2', focusIds: ['inner-local-cases'], from: 'Ta on poes.', prompt: 'Muuda: kust?', answer: 'Ta tuleb poest.', alternatives: [] },
      { id: 'inner-local-cases-tr-3', focusIds: ['inner-local-cases'], from: 'Laps on toas.', prompt: 'Muuda: kuhu?', answer: 'Laps läheb tuppa.', alternatives: [] },
    ],
    listeningScripts: [],
    speakingPrompts: prompts('inner-local-cases', 'sp', [
      ['1', 'inner-local-cases', 'inner-errands', 'Räägi oma tavalisest marsruudist: kus sa oled, kuhu lähed ja kust tuled. Kasuta vähemalt kuut sisekohakäände vormi.'],
    ]),
    writingPrompts: prompts('inner-local-cases', 'wp', [
      ['1', 'inner-local-cases', 'inner-school', 'Kirjuta 6–8 lauset ühe päeva liikumistest. Kasuta vähemalt kahte kus-, kahte kuhu- ja kahte kust-vormi.'],
    ]),
    successCriteria: ['Ma valin sisekohakäänetes teadlikult vormi küsimuse Kus? Kuhu? või Kust? järgi.'],
  },
  'outer-local-cases': {
    id: 'outer-local-cases',
    focus: { id: 'outer-local-cases', type: 'grammar', label: 'Kus? Kuhu? Kust? — peal', patterns: ['tööl / tööle / töölt', 'laual / lauale / laualt', 'turul / turule / turult'], aliases: ['väliskohakäänded', 'kus kuhu kust', '-l -le -lt'] },
    vocabulary: vocabulary('outer-local-cases', [
      ['tool', 'tööl', 'на работе', 'noun-form', 'outer-local-cases'],
      ['toole', 'tööle', 'на работу', 'noun-form', 'outer-local-cases'],
      ['toolt', 'töölt', 'с работы', 'noun-form', 'outer-local-cases'],
      ['laual', 'laual', 'на столе', 'noun-form', 'outer-local-cases'],
      ['lauale', 'lauale', 'на стол', 'noun-form', 'outer-local-cases'],
      ['laualt', 'laualt', 'со стола', 'noun-form', 'outer-local-cases'],
      ['arstil', 'arstil', 'у врача', 'noun-form', 'outer-local-cases'],
      ['arstile', 'arstile', 'к врачу', 'noun-form', 'outer-local-cases'],
      ['arstilt', 'arstilt', 'от врача', 'noun-form', 'outer-local-cases'],
      ['turul', 'turul', 'на рынке', 'noun-form', 'outer-local-cases'],
      ['turule', 'turule', 'на рынок', 'noun-form', 'outer-local-cases'],
      ['turult', 'turult', 'с рынка', 'noun-form', 'outer-local-cases'],
    ]),
    contexts: [
      { id: 'outer-work', label: 'Tööpäev', tags: ['work', 'movement'], names: ['Andrei', 'Katrin'], times: [] },
      { id: 'outer-surface', label: 'Asjad laual', tags: ['surface', 'home'], names: ['Mari', 'Jaan'], times: [] },
      { id: 'outer-services', label: 'Arst ja turg', tags: ['services', 'movement'], names: ['Olga', 'Martin'], times: [] },
    ],
    sentences: sentences('outer-local-cases', [
      ['1', 'outer-local-cases', 'outer-work', 'Olen täna tööl kella viieni.'],
      ['2', 'outer-local-cases', 'outer-work', 'Hommikul lähen tööle bussiga.'],
      ['3', 'outer-local-cases', 'outer-work', 'Pärast tööd tulen töölt koju.'],
      ['4', 'outer-local-cases', 'outer-surface', 'Telefon on laual.'],
      ['5', 'outer-local-cases', 'outer-surface', 'Panen telefoni lauale.'],
      ['6', 'outer-local-cases', 'outer-surface', 'Võtan telefoni laualt.'],
      ['7', 'outer-local-cases', 'outer-services', 'Hommikul olen arstil, pärast lähen turule.'],
      ['8', 'outer-local-cases', 'outer-services', 'Ema tuli arstilt otse koju.'],
      ['9', 'outer-local-cases', 'outer-services', 'Ostan turult värsket köögivilja.'],
    ]),
    dialogues: [{ id: 'outer-local-cases-d-1', focusIds: ['outer-local-cases'], contextIds: ['outer-work'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Kas sa oled praegu [tööl]?' },
      { who: 'B', text: 'Jah. Kell viis tulen [töölt].' },
      { who: 'A', text: 'Kuhu sa siis lähed?' },
      { who: 'B', text: 'Lähen otse [koju].' },
    ] }],
    errorPairs: [
      { id: 'outer-local-cases-e-1', focusIds: ['outer-local-cases'], wrong: 'Ma lähen tööl.', correct: 'Ma lähen tööle.' },
      { id: 'outer-local-cases-e-2', focusIds: ['outer-local-cases'], wrong: 'Telefon on lauale.', correct: 'Telefon on laual.' },
      { id: 'outer-local-cases-e-3', focusIds: ['outer-local-cases'], wrong: 'Võtan raamatu lauale.', correct: 'Võtan raamatu laualt.' },
    ],
    translations: [
      { id: 'outer-local-cases-t-1', focusIds: ['outer-local-cases'], sourceLang: 'ru', source: 'После работы я иду к врачу.', target: 'Pärast tööd lähen arstile.', alternatives: [] },
      { id: 'outer-local-cases-t-2', focusIds: ['outer-local-cases'], sourceLang: 'ru', source: 'Телефон лежит на столе.', target: 'Telefon on laual.', alternatives: [] },
    ],
    transformations: [
      { id: 'outer-local-cases-tr-1', focusIds: ['outer-local-cases'], from: 'Ma olen tööl.', prompt: 'Muuda: kuhu?', answer: 'Ma lähen tööle.', alternatives: [] },
      { id: 'outer-local-cases-tr-2', focusIds: ['outer-local-cases'], from: 'Telefon on laual.', prompt: 'Muuda: kuhu?', answer: 'Panen telefoni lauale.', alternatives: [] },
      { id: 'outer-local-cases-tr-3', focusIds: ['outer-local-cases'], from: 'Ta on arstil.', prompt: 'Muuda: kust?', answer: 'Ta tuleb arstilt.', alternatives: [] },
    ],
    listeningScripts: [],
    speakingPrompts: prompts('outer-local-cases', 'sp', [
      ['1', 'outer-local-cases', 'outer-services', 'Kirjelda kolme liikumist: töö, arst või turg. Iga koha kohta kasuta Kus?, Kuhu? ja Kust? vormi.'],
    ]),
    writingPrompts: prompts('outer-local-cases', 'wp', [
      ['1', 'outer-local-cases', 'outer-surface', 'Kirjuta 6 lauset, kus kirjeldad asjade asukohta ja liigutamist lauale või laualt.'],
    ]),
    successCriteria: ['Ma valin väliskohakäänetes teadlikult vormi küsimuse Kus? Kuhu? või Kust? järgi.'],
  },
  neighbourhood: {
    id: 'neighbourhood',
    focus: { id: 'neighbourhood', type: 'listening', label: 'Korter ja naabruskond', patterns: ['asub … lähedal', '… kõrval / vastas', 'kolmandal korrusel'], aliases: ['naabruskond', 'korter', 'asukoht'] },
    vocabulary: vocabulary('neighbourhood', [
      ['asub', 'asub', 'находится', 'verb', 'neighbourhood'],
      ['lahedal', 'lähedal', 'рядом / недалеко', 'adverb', 'neighbourhood'],
      ['korval', 'kõrval', 'рядом с', 'adposition', 'neighbourhood'],
      ['vastas', 'vastas', 'напротив', 'adposition', 'neighbourhood'],
      ['korrus', 'korrus', 'этаж', 'noun', 'neighbourhood'],
      ['lift', 'lift', 'лифт', 'noun', 'neighbourhood'],
      ['parkla', 'parkla', 'парковка', 'noun', 'neighbourhood'],
      ['bussipeatus', 'bussipeatus', 'автобусная остановка', 'noun', 'neighbourhood'],
      ['apteek', 'apteek', 'аптека', 'noun', 'neighbourhood'],
      ['pood', 'pood', 'магазин', 'noun', 'neighbourhood'],
      ['park', 'park', 'парк', 'noun', 'neighbourhood'],
      ['maja', 'maja', 'дом / здание', 'noun', 'neighbourhood'],
    ]),
    contexts: [
      { id: 'neighbourhood-flat', label: 'Korter Mustamäel', tags: ['home', 'neighbourhood', 'listening'], names: ['Mari'], times: [] },
      { id: 'neighbourhood-map', label: 'Naabruskonna kaart', tags: ['map', 'neighbourhood'], names: ['Jaan'], times: [] },
      { id: 'neighbourhood-route', label: 'Kodust peatusesse', tags: ['route', 'neighbourhood'], names: ['Olga'], times: [] },
    ],
    sentences: sentences('neighbourhood', [
      ['1', 'neighbourhood', 'neighbourhood-flat', 'Minu korter asub Mustamäel.'],
      ['2', 'neighbourhood', 'neighbourhood-flat', 'Ma elan kolmandal korrusel ja majas on lift.'],
      ['3', 'neighbourhood', 'neighbourhood-flat', 'Parkla on maja kõrval.'],
      ['4', 'neighbourhood', 'neighbourhood-map', 'Apteek asub poe kõrval.'],
      ['5', 'neighbourhood', 'neighbourhood-map', 'Bussipeatus on maja vastas.'],
      ['6', 'neighbourhood', 'neighbourhood-map', 'Park on kodu lähedal.'],
      ['7', 'neighbourhood', 'neighbourhood-route', 'Kodust bussipeatusesse lähen umbes kolm minutit.'],
      ['8', 'neighbourhood', 'neighbourhood-route', 'Bussipeatusest tööle sõidan kakskümmend minutit.'],
      ['9', 'neighbourhood', 'neighbourhood-route', 'Nädalavahetusel jalutan tavaliselt kodu lähedal pargis.'],
    ]),
    dialogues: [{ id: 'neighbourhood-d-1', focusIds: ['neighbourhood'], contextIds: ['neighbourhood-map'], speakers: ['A', 'B'], lines: [
      { who: 'A', text: 'Kus lähim [apteek] asub?' },
      { who: 'B', text: 'See on poe [kõrval], bussipeatuse vastas.' },
      { who: 'A', text: 'Kas park on kaugel?' },
      { who: 'B', text: 'Ei, park on väga [lähedal].' },
    ] }],
    errorPairs: [
      { id: 'neighbourhood-e-1', focusIds: ['neighbourhood'], wrong: 'Apteek asub pood kõrval.', correct: 'Apteek asub poe kõrval.' },
      { id: 'neighbourhood-e-2', focusIds: ['neighbourhood'], wrong: 'Ma elan kolmas korrusel.', correct: 'Ma elan kolmandal korrusel.' },
      { id: 'neighbourhood-e-3', focusIds: ['neighbourhood'], wrong: 'Park on kodu lähedale.', correct: 'Park on kodu lähedal.' },
    ],
    translations: [
      { id: 'neighbourhood-t-1', focusIds: ['neighbourhood'], sourceLang: 'ru', source: 'Аптека находится рядом с магазином.', target: 'Apteek asub poe kõrval.', alternatives: [] },
      { id: 'neighbourhood-t-2', focusIds: ['neighbourhood'], sourceLang: 'ru', source: 'Я живу на третьем этаже.', target: 'Ma elan kolmandal korrusel.', alternatives: [] },
    ],
    transformations: [
      { id: 'neighbourhood-tr-1', focusIds: ['neighbourhood'], from: 'Parkla on maja kõrval.', prompt: 'Alusta sõnaga „Maja”.', answer: 'Maja kõrval on parkla.', alternatives: [] },
      { id: 'neighbourhood-tr-2', focusIds: ['neighbourhood'], from: 'Apteek on poe kõrval.', prompt: 'Kasuta verbi „asuma”.', answer: 'Apteek asub poe kõrval.', alternatives: [] },
    ],
    listeningScripts: [
      {
        id: 'neighbourhood-ls-1', focusIds: ['neighbourhood'], contextIds: ['neighbourhood-flat'], title: 'Minu kodu ja ümbrus',
        transcript: 'Minu korter asub Mustamäel viiekorruselises majas. Ma elan kolmandal korrusel. Majas on lift. Bussipeatus on maja ees ja väike parkla maja kõrval. Apteek asub üle tee, poe kõrval. Lähim park on umbes viie minuti kaugusel. Tööpäeval lähen tavaliselt bussiga tööle, aga nädalavahetusel jalutan pargis.',
        sentences: 'Korter asub [Mustamäel].\nTa elab [kolmandal] korrusel.\nMajas on [lift].\nParkla on maja [kõrval].\nNädalavahetusel jalutab ta [pargis].',
      },
      {
        id: 'neighbourhood-ls-2', focusIds: ['neighbourhood'], contextIds: ['neighbourhood-route'], title: 'Tee bussipeatusesse',
        transcript: 'Olga elab uues majas teisel korrusel. Tema maja vastas on väike pood ja poe kõrval on apteek. Bussipeatus asub majast umbes kolmesaja meetri kaugusel. Olga läheb hommikul kodust peatusesse jalgsi. Pärast tööd tuleb ta sageli poest läbi ja alles siis läheb koju.',
        sentences: 'Olga elab [teisel] korrusel.\nMaja vastas on [pood].\nPoe kõrval on [apteek].\nPeatus on umbes [kolmesaja] meetri kaugusel.\nPärast tööd käib Olga sageli [poest] läbi.',
      },
    ],
    speakingPrompts: prompts('neighbourhood', 'sp', [
      ['1', 'neighbourhood', 'neighbourhood-map', 'Kirjelda oma naabruskonda: mis on kodu lähedal, kõrval või vastas ja kuidas sa liigud kolme tuttavasse kohta.'],
      ['2', 'neighbourhood', 'neighbourhood-route', 'Selgita õpetajale teed kodust bussipeatusesse või poodi. Kasuta Kus?, Kuhu? ja Kust? vorme.'],
    ]),
    writingPrompts: prompts('neighbourhood', 'wp', [
      ['1', 'neighbourhood', 'neighbourhood-flat', 'Kirjuta 70–90 sõna oma kodust ja naabruskonnast. Nimeta korrus, vähemalt kolm lähedast kohta ja üks tavaline marsruut.'],
    ]),
    successCriteria: ['Ma mõistan lühikest kodu ja naabruskonna kirjeldust ning oskan ise kirjeldada asukohta ja liikumist.'],
  },
});

export const LESSON_CONTENT_BLUEPRINTS = Object.freeze({
  'a2-002': { packIds: ['introduction', 'basic-questions'], title: 'Tutvumine ja viisakus', lessonKind: 'communication' },
  'a2-003': { packIds: ['olema-present', 'present-common-verbs'], title: 'Olen, elan, räägin', lessonKind: 'grammar' },
  'a2-004': { packIds: ['personal-info', 'numbers-dates'], title: 'Isikuandmed ja lihtne ankeet', lessonKind: 'writing' },
  'a2-005': { packIds: ['introduction', 'basic-questions', 'olema-present', 'present-common-verbs', 'personal-info', 'numbers-dates'], title: 'Kontroll 1 — eneseinfo', lessonKind: 'assessment' },
  'a2-006': { packIds: ['family-relations'], title: 'Pere ja lähedased', lessonKind: 'vocabulary' },
  'a2-007': { packIds: ['possession-genitive'], title: 'Kelle oma? Genitiiv', lessonKind: 'grammar' },
  'a2-008': { packIds: ['appearance-character'], title: 'Välimus ja iseloom', lessonKind: 'vocabulary' },
  'a2-009': { packIds: ['people-profiles'], title: 'Minu inimesed', lessonKind: 'reading' },
  'a2-010': { packIds: ['family-relations', 'possession-genitive', 'appearance-character', 'people-profiles'], title: 'Kontroll 2 — pere ja inimesed', lessonKind: 'assessment' },
  'a2-011': { packIds: ['daily-routine'], title: 'Minu päev', lessonKind: 'communication' },
  'a2-012': { packIds: ['clock-time'], title: 'Kellaaeg ja ajaväljendid', lessonKind: 'grammar' },
  'a2-013': { packIds: ['frequency'], title: 'Kui tihti?', lessonKind: 'grammar' },
  'a2-014': { packIds: ['week-plan'], title: 'Minu nädal', lessonKind: 'writing' },
  'a2-015': { packIds: ['daily-routine', 'clock-time', 'frequency', 'week-plan'], title: 'Kontroll 3 — päev ja aeg', lessonKind: 'assessment' },
  'a2-016': { packIds: ['home-rooms'], title: 'Minu kodu', lessonKind: 'vocabulary' },
  'a2-017': { packIds: ['inner-local-cases'], title: 'Kus? Kuhu? Kust? — sees', lessonKind: 'grammar' },
  'a2-018': { packIds: ['outer-local-cases'], title: 'Kus? Kuhu? Kust? — peal', lessonKind: 'grammar' },
  'a2-019': { packIds: ['neighbourhood'], title: 'Korter ja naabruskond', lessonKind: 'listening' },
  'a2-020': { packIds: ['home-rooms', 'inner-local-cases', 'outer-local-cases', 'neighbourhood'], title: 'Kontroll 4 — kodu ja ümbrus', lessonKind: 'assessment' },
});
