(function(){
'use strict';const $=id=>document.getElementById(id),endpoint='https://us-central1-keelesepp-5136b.cloudfunctions.net/';let auth,user,record,answers={},role='',selected='',dirty=false,busy=false,previewStudent=null;
const status=t=>$('status').textContent=t;
const statusLabel=value=>({active:'Tegemata',submitted:'Saadetud õpetajale',reviewed:'Tagasiside saadud'})[value]||value;
async function api(action,data={},name='interactiveLessonApi'){if(!auth.currentUser||auth.currentUser.uid!==user.uid)throw Error('Logi uuesti sisse.');const requestingUid=user.uid;const r=await fetch(endpoint+name,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await user.getIdToken()},body:JSON.stringify({action,...data})});const body=await r.json();if(!auth.currentUser||auth.currentUser.uid!==requestingUid)throw Error('Konto muutus. Ava leht uuesti.');if(!r.ok)throw Object.assign(Error(r.status===409?'Vahepeal on salvestatud teine versioon. Sinu vastused jäid alles; laadi serverist uuesti ainult siis, kui soovid need asendada.':body.error||'Päring ebaõnnestus'),{status:r.status});return body;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message);}finally{busy=false;document.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=false);if(record)render();}}
function recoveryKey(){return 'keelesepp.interactive.'+user.uid+'.'+record.id;}
function clearRecovery(){try{localStorage.removeItem(recoveryKey());}catch{}}
function recover(){try{localStorage.setItem(recoveryKey(),JSON.stringify({revision:record.revision,answers,currentActivityId:selected}));}catch{status('Kohalik varukoopia pole saadaval. Salvesta serverisse.');}}
function render(){if(!record)return;$('title').textContent=record.title;$('list').hidden=true;$('lesson').hidden=false;$('home').hidden=false;const student=role==='student'||role==='student_preview',editable=role==='student'&&record.status==='active',testable=editable||role==='student_preview';$('view-mode').textContent=(role==='student'?'ÕPILASE TÖÖLAUD':role==='student_preview'?'TURVALINE ÕPILASE VAADE':'ÕPETAJA VAADE')+(role==='student'?'':' · '+(record.studentName||previewStudent?.name||''));$('save').hidden=$('submit').hidden=!editable;$('reload').hidden=role!=='student';document.querySelector('.actions').hidden=role!=='student';$('review').hidden=student||record.status!=='submitted';$('feedback').textContent=record.feedback||'';
const nav=$('steps');nav.replaceChildren();for(const a of record.lesson.activities){const b=document.createElement('button');b.textContent=a.title;b.setAttribute('aria-current',String(a.id===selected));b.disabled=busy;b.onclick=()=>{selected=a.id;if(editable){dirty=true;recover();}render();};nav.append(b);}
const a=record.lesson.activities.find(a=>a.id===selected)||record.lesson.activities[0];selected=a.id;$('activity-title').textContent=a.title;$('prompt').textContent=a.prompt;$('activity-kind').textContent=({short_text:'Lühivastus',long_text:'Pikem kirjalik vastus',single_choice:'Vali üks vastus',multiple_choice:'Vali mitu vastust',gaps:'Täida lüngad'})[a.response?.mode]||'Suuline või õpetaja juhitud';window.KeeleSeppResponseView.renderAssets($('assets'),a);$('response').replaceChildren();$('review-answer').textContent='';
const index=record.lesson.activities.indexOf(a),total=record.lesson.activities.length;$('progress').max=total;$('progress').value=index+1;$('progress-count').textContent=(index+1)+' / '+total;$('progress-title').textContent=a.title;$('activity-number').textContent='ÜLESANNE '+(index+1);$('outline-count').textContent='('+total+')';$('previous').disabled=busy||index===0;$('next').disabled=busy||index===total-1;
let inline=false;if(testable)inline=window.KeeleSeppResponseView.render($('response'),a,answers[a.id],value=>{answers[a.id]=value;if(editable){dirty=true;recover();status('Salvestamata vastused · kohalik varukoopia');}else status('Proovivastus on ainult selles kontrollvaates ja seda ei salvestata.');});else $('review-answer').textContent=answerText(a,answers[a.id]);$('prompt').hidden=inline;
$('teacher-guide').hidden=student;const t=record.teacherContent?.activities.find(x=>x.id===a.id)?.routes[record.route];$('teacher-content').textContent=t?[t.expected,t.teacherInstruction].filter(Boolean).join('\n\n'):'';
$('edit-activity').hidden=student||!record.teacherContent?.id;$('edit-activity').onclick=()=>{const frame=$('edit-frame');frame.src='/haldus-lesson-builder/?draftId='+encodeURIComponent(record.teacherContent.id)+'&activityId='+encodeURIComponent(a.id);$('edit-dialog').showModal();};
}
function answerText(a,value){if(value===undefined)return a.response?'Õpilane pole veel vastanud.':'See on suuline või õpetaja juhitud ülesanne. Õpilane ei pea siia midagi kirjutama.';const s=a.response;if(s?.mode==='single_choice')return s.items.find(i=>i.id===value)?.label||'—';if(s?.mode==='multiple_choice')return s.items.filter(i=>value.includes(i.id)).map(i=>i.label).join(', ');if(s?.mode==='gaps')return s.items.map(i=>i.label+': '+(value[i.id]||'—')).join('\n');return String(value);}
function assignmentCard(r,studentView=false){const b=document.createElement('button');b.className='assignment-card';const copy=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small'),openLabel=document.createElement('span');name.textContent=r.title;meta.textContent=(studentView?'':(r.studentName||'Õpilane')+' · ')+statusLabel(r.status);openLabel.className='assignment-open';openLabel.textContent='Ava ülesanded →';copy.append(name,meta);b.append(copy,openLabel);b.onclick=()=>run(()=>open(r.id));return b;}
async function open(id,{restore=true}={}){record=await api('get',{assignmentId:id,...(role==='student_preview'?{viewAsStudent:true,previewStudentId:previewStudent.id}:{})});answers=record.answers;selected=record.currentActivityId;dirty=false;if(role!=='student_preview'&&!restore)clearRecovery();let restored=false;if(role==='student'&&record.status==='active'&&restore){try{const raw=JSON.parse(localStorage.getItem(recoveryKey())||'null');if(raw&&raw.revision===record.revision){answers=raw.answers;selected=raw.currentActivityId;dirty=true;restored=true;}}catch{}}
history.replaceState(null,'','?assignmentId='+encodeURIComponent(id));render();if(restored)status('Kohalikud vastused taastatud. Salvesta need serverisse.');else if(role==='student')status(record.status==='active'?'Vasta ülesannetele ja salvesta.':record.status==='submitted'?'Õpetajale saadetud.':'Õpetaja tagasiside on saabunud.');else status(record.status==='active'?'Õpilane pole veel vastuseid saatnud.':record.status==='submitted'?'Õpilase vastused ootavad tagasisidet.':'Tagasiside on õpilasele saadetud.');}
async function list(){const data=await api('list');role=data.role;previewStudent=null;$('preview-banner').hidden=true;record=null;$('lesson').hidden=true;$('list').hidden=false;$('list').replaceChildren();history.replaceState(null,'',location.pathname);$('home').hidden=true;$('list').className=role==='student'?'student-list':'staff-list';if(role!=='student'){document.querySelector('header h1').textContent='Õpilaste ülesanded';const intro=document.createElement('section');intro.className='entry-hero';const heading=document.createElement('div');heading.innerHTML='<p class="eyebrow">KONTROLLI ÕPILASE KOGEMUST</p><h2>Vaata täpselt seda, mida õpilane näeb</h2><p>Vali õpilane, ava tema määratud tund ja proovi vastusevälju ilma midagi salvestamata.</p>';const preview=document.createElement('button');preview.className='primary-entry';preview.innerHTML='<strong>Vaata õpilase pilguga</strong><small>Vali õpilane ja tema tund →</small>';preview.onclick=()=>run(previewForm);intro.append(heading,preview);const tools=document.createElement('div');tools.className='secondary-actions';const a=document.createElement('a');a.href='/haldus-lesson-builder/';a.textContent='＋ Koosta uus tund';const assign=document.createElement('button');assign.textContent='Määra avaldatud tund';assign.onclick=()=>run(assignForm);tools.append(a,assign);$('list').append(intro,tools);if(data.assignments.length){const h=document.createElement('h2');h.className='list-title';h.textContent='Õpilastele määratud tunnid';$('list').append(h);}}else document.querySelector('header h1').textContent='Minu ülesanded';
for(const r of data.assignments)$('list').append(assignmentCard(r,role==='student'));if(data.nextCursor){const more=document.createElement('p');more.textContent='Kuvatakse esimesed 50 ülesannet. Ülejäänud ülesande saab avada otselingiga.';$('list').append(more);}status(data.assignments.length?(role==='student'?'Vali ülesanne ja alusta.':'Ava määratud tund või vaata seda õpilase pilguga.'):'Ülesandeid veel pole.');}
async function previewForm(){const host=$('list');host.replaceChildren();host.className='preview-picker';const back=document.createElement('button');back.className='back-link';back.textContent='← Tagasi ülesannete juurde';back.onclick=()=>run(list);const heading=document.createElement('div');heading.innerHTML='<p class="eyebrow">1. SAMM</p><h2>Vali õpilane</h2><p>Seejärel näed ainult sellele õpilasele määratud tunde.</p>';const label=document.createElement('label');label.textContent='Õpilane';const input=document.createElement('select');input.add(new Option('Vali õpilane…',''));let cursor;do{const page=await api('students',cursor?{cursor}:{});for(const s of page.students)input.add(new Option(s.name,s.id));cursor=page.nextCursor;}while(cursor);label.append(input);const button=document.createElement('button');button.className='primary-entry';button.textContent='Näita õpilase ülesandeid →';button.disabled=true;input.onchange=()=>button.disabled=!input.value;button.onclick=()=>run(async()=>{const data=await api('previewStart',{studentId:input.value});role=data.role;previewStudent=data.student;$('preview-student').textContent=data.student.name;$('preview-banner').hidden=false;host.replaceChildren();const h=document.createElement('h2');h.textContent=data.student.name+' · vali tund';host.append(h);for(const r of data.assignments)host.append(assignmentCard(r,true));status(data.assignments.length?'Ava tund. Kontrollvaade ei salvesta muudatusi.':'Sellel õpilasel pole veel ülesandeid.');});host.append(back,heading,label,button);status('Vali õpilane ja vajuta sinist nuppu.');}
async function assignForm(){const requestedVersion=new URLSearchParams(location.search).get('lessonVersionId')||'';const drafts=await api('list',{},'lessonDraftsApi');const host=$('list');host.replaceChildren();const select=document.createElement('select');select.setAttribute('aria-label','Avaldatud tund');select.add(new Option('Vali avaldatud tund',''));for(const d of drafts.drafts.filter(d=>d.lastPublishedVersionId))select.add(new Option(d.title+' · v'+d.versionNumber,d.lastPublishedVersionId));if([...select.options].some(o=>o.value===requestedVersion))select.value=requestedVersion;const label=document.createElement('label');label.textContent='Õpilane';const input=document.createElement('select');input.add(new Option('Vali õpilane',''));let cursor;do{const page=await api('students',cursor?{cursor}:{});for(const s of page.students)input.add(new Option(s.name,s.id));cursor=page.nextCursor;}while(cursor);label.append(input);const button=document.createElement('button');button.textContent='Määra õpilasele';const ready=()=>button.disabled=!select.value||!input.value;select.onchange=input.onchange=ready;button.onclick=()=>run(async()=>{const r=await api('assign',{lessonVersionId:select.value,studentId:input.value.trim()});await open(r.id);status('Määratud. Õpilane leiab tunni oma ülesannete loendist.');});ready();host.append(select,label,button);status(select.value?'Vali õpilane ja kinnita määramine.':'Vali avaldatud tund ja õpilane.');}
$('save').onclick=()=>run(async()=>{const r=await api('save',{assignmentId:record.id,revision:record.revision,answers,currentActivityId:selected});record.revision=r.revision;record.answers=answers;dirty=false;clearRecovery();status('Vastused serverisse salvestatud.');});
$('submit').onclick=()=>{if(confirm('Saata vastused õpetajale? Pärast saatmist neid enam muuta ei saa.'))run(async()=>{await api('submit',{assignmentId:record.id,revision:record.revision,answers,currentActivityId:selected});clearRecovery();await open(record.id,{restore:false});});};
$('reload').onclick=()=>{if(!dirty||confirm('Asendada kohalikud vastused serveris salvestatud vastustega?'))run(()=>open(record.id,{restore:false}));};
$('home').onclick=()=>{if(!dirty||confirm('Lahkuda? Salvestamata vastused jäävad selle brauseri varukoopiasse.'))run(list);};
$('previous').onclick=()=>{const i=record.lesson.activities.findIndex(a=>a.id===selected);if(i>0){selected=record.lesson.activities[i-1].id;render();scrollTo({top:0,behavior:'smooth'});}};
$('next').onclick=()=>{const i=record.lesson.activities.findIndex(a=>a.id===selected);if(i<record.lesson.activities.length-1){selected=record.lesson.activities[i+1].id;render();scrollTo({top:0,behavior:'smooth'});}};
$('preview-exit').onclick=()=>run(list);
$('edit-close').onclick=()=>{$('edit-dialog').close();$('edit-frame').src='about:blank';};
$('review-save').onclick=()=>run(async()=>{await api('review',{assignmentId:record.id,revision:record.revision,feedback:$('review-text').value});await open(record.id,{restore:false});});
addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(!firebase.apps.length)firebase.initializeApp({apiKey:'AIzaSyAp8emBOh1fIqv72k_O5hkLkXVkfBt1al4',authDomain:'keelesepp-5136b.firebaseapp.com',projectId:'keelesepp-5136b',appId:'1:674098517935:web:e73d04a4ada67874da015a'});auth=firebase.auth();auth.onAuthStateChanged(u=>{if(user&&u&&user.uid!==u.uid){record=null;answers={};$('lesson').hidden=true;$('list').replaceChildren();location.reload();return;}user=u;if(!u){record=null;$('list').replaceChildren();$('lesson').hidden=true;$('signin').hidden=false;status('Logi sisse, et avada oma ülesanded.');return;}const params=new URLSearchParams(location.search),assignmentId=params.get('assignmentId'),lessonVersionId=params.get('lessonVersionId'),action=params.get('action');run(async()=>{const data=await api('list');role=data.role;if(assignmentId)await open(assignmentId);else if((lessonVersionId||action==='assign')&&role!=='student')await assignForm();else await list();});});
})();
