import { MessageCircle, Search, Send } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useAuth } from '../../app/AuthContext.jsx';
import { Button, Card, EmptyState, ErrorState, LoadingState, PageHeader } from '../../components/ui/index.js';
import { useAsyncData } from '../../hooks/useAsyncData.js';
import { messagesService, studentsService } from '../../services/firebase/index.js';
import { hasAnyRole, ROLES } from '../../utils/roles.js';

export default function MessagesPage() {
  const { user } = useAuth(); const staff = hasAnyRole(user.roles, [ROLES.ADMIN, ROLES.TEACHER]); const [selected, setSelected] = useState(''); const [query, setQuery] = useState(''); const [text, setText] = useState(''); const [sending, setSending] = useState(false); const [actionError, setActionError] = useState('');
  const state = useAsyncData(async () => { const owned = staff ? null : await studentsService.listOwned(user.uid); const studentResult = staff ? await studentsService.list({ status: 'active', pageSize: 500, exhaustive: true }) : { items: owned }; const messages = staff ? await messagesService.list() : await messagesService.listByStudentIds(owned.map((item) => item.id)); return [messages, studentResult]; }, [staff, user.uid]);
  const conversations = useMemo(() => { const map = new Map(); for (const message of state.data?.[0] || []) { const id = message.studentId || message.studentName; const previous = map.get(id) || { id, name: message.studentName || 'Vestlus', messages: [], unread: 0 }; previous.messages.push(message); if (!message.read && message.fromUid !== user.uid) previous.unread += 1; map.set(id, previous); } return [...map.values()].filter((item) => item.name.toLocaleLowerCase('et').includes(query.toLocaleLowerCase('et'))).sort((a, b) => String(b.messages.at(-1)?.createdAt || '').localeCompare(String(a.messages.at(-1)?.createdAt || ''))); }, [state.data, query, user.uid]);
  if (state.loading) return <LoadingState label="Laen sõnumeid…" />;
  if (state.error) return <ErrorState message={state.error.message} onRetry={state.reload} />;
  const students = state.data[1].items; const selectedStudent = students.find((item) => item.id === selected);
  const active = conversations.find((item) => item.id === selected) || (selectedStudent ? { id: selectedStudent.id, name: selectedStudent.name, messages: [], unread: 0 } : conversations[0]);
  const send = async (event) => { event.preventDefault(); if (!text.trim() || !active) return; setSending(true); try { await messagesService.send({ studentId: active.id, studentName: active.name, text }, user); setText(''); await state.reload(); } catch (error) { setActionError(error.message); } finally { setSending(false); } };
  const start = (event) => { const student = students.find((item) => item.id === event.target.value); if (student) setSelected(student.id); };
  return <div className="page-content"><PageHeader eyebrow="Suhtlus" title="Sõnumid" description="Vestlused õpilaste ja lapsevanematega." />{actionError ? <div className="action-error">{actionError}<button onClick={() => setActionError('')}>×</button></div> : null}<Card className="messages-shell"><aside className="conversation-list"><div className="search-field"><Search size={17} /><input aria-label="Otsi vestlust" placeholder="Otsi vestlust" value={query} onChange={(e) => setQuery(e.target.value)} /></div><select className="new-conversation" aria-label="Alusta vestlust" value="" onChange={start}><option value="">+ Alusta uut vestlust</option>{students.map((student) => <option value={student.id} key={student.id}>{student.name}</option>)}</select><div>{conversations.map((item) => <button className={active?.id === item.id ? 'conversation active' : 'conversation'} key={item.id} onClick={() => setSelected(item.id)}><span className="conversation-avatar">{item.name[0]}</span><div><strong>{item.name}</strong><small>{item.messages.at(-1)?.text}</small></div>{item.unread ? <b>{item.unread}</b> : null}</button>)}</div></aside><section className="chat-panel">{active ? <><header><span className="conversation-avatar">{active.name[0]}</span><div><strong>{active.name}</strong><small>{active.messages.length} sõnumit</small></div></header><div className="message-stream">{active.messages.map((message) => <div className={message.fromUid === user.uid ? 'message own' : 'message'} key={message.id}><p>{message.text}</p><time>{new Date(message.createdAt || `${message.date}T12:00:00`).toLocaleString('et-EE', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}</time></div>)}</div><form className="message-composer" onSubmit={send}><textarea aria-label="Sõnum" placeholder="Kirjuta sõnum…" rows="2" value={text} onChange={(e) => setText(e.target.value)} /><Button loading={sending} aria-label="Saada"><Send size={18} /></Button></form></> : <EmptyState title="Vestlusi veel ei ole" description="Vali õpilane ja alusta esimest vestlust." action={<MessageCircle size={28} />} />}</section></Card></div>;
}
