export const ACTIVITY_CATALOG_VERSION = 1;

const ALL_KINDS = ['grammar', 'vocabulary', 'communication', 'reading', 'listening', 'writing', 'assessment', 'integrated'];

export const ACTIVITY_CATALOG = [
  {
    id: 'discover-vocabulary-match',
    phase: 'discover',
    blockType: 'match',
    family: 'lexical-recognition',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['vocabulary', 'reading'],
    production: 'recognition',
    cognitiveLoad: 1,
    tags: ['input', 'meaning', 'controlled'],
    needs: ['vocabularyTranslations'],
  },
  {
    id: 'discover-context-truefalse',
    phase: 'discover',
    blockType: 'truefalse',
    family: 'context-comprehension',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['reading'],
    production: 'recognition',
    cognitiveLoad: 1,
    tags: ['input', 'context', 'controlled'],
    needs: ['sentences2'],
  },
  {
    id: 'discover-focus-choice',
    phase: 'discover',
    blockType: 'choice',
    family: 'lexical-choice',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'B2',
    skills: ['vocabulary', 'reading'],
    production: 'recognition',
    cognitiveLoad: 1,
    tags: ['input', 'meaning', 'controlled'],
    needs: ['vocabularyTranslations3'],
  },
  {
    id: 'discover-focus-categorize',
    phase: 'discover',
    blockType: 'categorize',
    family: 'classification',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['vocabulary', 'grammar'],
    production: 'recognition',
    cognitiveLoad: 2,
    tags: ['noticing', 'form-meaning', 'controlled'],
    needs: ['focusVocabulary'],
  },
  {
    id: 'discover-guided-dialogue',
    phase: 'discover',
    blockType: 'dialogue',
    family: 'guided-dialogue',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['reading', 'communication'],
    production: 'guided',
    cognitiveLoad: 2,
    tags: ['context', 'noticing', 'guided'],
    needs: ['dialogues'],
  },
  {
    id: 'discover-selfcheck',
    phase: 'discover',
    blockType: 'selfcheck',
    family: 'reflection',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['metacognition'],
    production: 'reflection',
    cognitiveLoad: 1,
    tags: ['reflection'],
    needs: ['successCriteria'],
  },

  {
    id: 'practice-gap-fill',
    phase: 'practice',
    blockType: 'gaps',
    family: 'controlled-cloze',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['grammar', 'vocabulary'],
    production: 'controlled',
    cognitiveLoad: 2,
    tags: ['accuracy', 'form', 'controlled'],
    needs: ['sentences2', 'vocabulary'],
  },
  {
    id: 'practice-context-choice',
    phase: 'practice',
    blockType: 'choice',
    family: 'controlled-cloze',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'B2',
    skills: ['grammar', 'vocabulary', 'reading'],
    production: 'controlled',
    cognitiveLoad: 2,
    tags: ['accuracy', 'form-meaning', 'controlled'],
    needs: ['sentences2', 'vocabularyTranslations3'],
  },
  {
    id: 'practice-sentence-transformation',
    phase: 'practice',
    blockType: 'transformation',
    family: 'transformation',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['grammar', 'writing'],
    production: 'controlled',
    cognitiveLoad: 3,
    tags: ['accuracy', 'transformation', 'controlled'],
    needs: ['transformations'],
  },
  {
    id: 'practice-error-repair',
    phase: 'practice',
    blockType: 'errorfix',
    family: 'error-repair',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['grammar', 'writing'],
    production: 'controlled',
    cognitiveLoad: 3,
    tags: ['accuracy', 'repair', 'controlled'],
    needs: ['errorPairs'],
  },
  {
    id: 'practice-translation',
    phase: 'practice',
    blockType: 'translation',
    family: 'mediation',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['mediation', 'writing'],
    production: 'guided',
    cognitiveLoad: 3,
    tags: ['accuracy', 'mediation', 'guided'],
    needs: ['translations'],
  },
  {
    id: 'practice-word-order',
    phase: 'practice',
    blockType: 'wordorder',
    family: 'sentence-reconstruction',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'B2',
    skills: ['grammar', 'reading'],
    production: 'controlled',
    cognitiveLoad: 2,
    tags: ['accuracy', 'reconstruction', 'controlled'],
    needs: ['sentences1'],
  },
  {
    id: 'practice-clock',
    phase: 'practice',
    blockType: 'clock',
    family: 'functional-form',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'A2',
    skills: ['vocabulary', 'communication'],
    production: 'controlled',
    cognitiveLoad: 2,
    tags: ['accuracy', 'functional', 'controlled'],
    needs: ['contextTimes'],
  },
  {
    id: 'practice-focus-categorize',
    phase: 'practice',
    blockType: 'categorize',
    family: 'classification',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['grammar', 'vocabulary'],
    production: 'controlled',
    cognitiveLoad: 2,
    tags: ['accuracy', 'form-meaning', 'controlled'],
    needs: ['focusVocabulary'],
  },
  {
    id: 'practice-functional-reading',
    phase: 'practice',
    blockType: 'reading',
    family: 'functional-reading',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['reading', 'mediation'],
    production: 'controlled',
    cognitiveLoad: 3,
    tags: ['accuracy', 'reading', 'controlled'],
    needs: ['readingDocuments'],
  },
  {
    id: 'practice-listening-comprehension',
    phase: 'practice',
    blockType: 'listening',
    family: 'listening-reconstruction',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['listening', 'reading'],
    production: 'controlled',
    cognitiveLoad: 3,
    tags: ['accuracy', 'listening', 'controlled'],
    needs: ['listeningScripts'],
  },
  {
    id: 'practice-dictation',
    phase: 'practice',
    blockType: 'dictation',
    family: 'sentence-reconstruction',
    lessonKinds: ['grammar', 'vocabulary', 'listening', 'integrated', 'assessment'],
    minLevel: 'A2',
    maxLevel: 'B2',
    skills: ['listening', 'writing'],
    production: 'controlled',
    cognitiveLoad: 3,
    tags: ['accuracy', 'listening', 'reconstruction'],
    needs: ['sentences2'],
  },

  {
    id: 'transfer-rolecards',
    phase: 'transfer',
    blockType: 'rolecards',
    family: 'interaction',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['speaking', 'interaction'],
    production: 'free',
    cognitiveLoad: 3,
    tags: ['transfer', 'oral', 'interaction'],
    needs: ['vocabulary'],
  },
  {
    id: 'transfer-speaking',
    phase: 'transfer',
    blockType: 'speaking',
    family: 'oral-production',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['speaking'],
    production: 'free',
    cognitiveLoad: 3,
    tags: ['transfer', 'oral', 'production'],
    needs: ['speakingOrSuccess'],
  },
  {
    id: 'transfer-planning',
    phase: 'transfer',
    blockType: 'planning',
    family: 'planning',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['writing', 'speaking'],
    production: 'guided',
    cognitiveLoad: 3,
    tags: ['transfer', 'planning', 'guided'],
    needs: ['successCriteria'],
  },
  {
    id: 'transfer-problem-solving',
    phase: 'transfer',
    blockType: 'planning',
    family: 'problem-solving',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['speaking', 'interaction', 'writing'],
    production: 'free',
    cognitiveLoad: 4,
    tags: ['transfer', 'oral', 'production'],
    needs: ['successCriteria', 'vocabulary'],
  },
  {
    id: 'transfer-writing',
    phase: 'transfer',
    blockType: 'writing',
    family: 'written-production',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['writing'],
    production: 'free',
    cognitiveLoad: 4,
    tags: ['transfer', 'written', 'production'],
    needs: ['writingOrSuccess'],
  },
  {
    id: 'transfer-guided-letter',
    phase: 'transfer',
    blockType: 'guidedletter',
    family: 'written-production',
    lessonKinds: ['communication', 'writing', 'integrated', 'assessment'],
    minLevel: 'B1',
    maxLevel: 'C1',
    skills: ['writing', 'communication'],
    production: 'free',
    cognitiveLoad: 5,
    tags: ['transfer', 'written', 'production'],
    needs: ['formalLetterPrompt'],
  },
  {
    id: 'transfer-rubric',
    phase: 'transfer',
    blockType: 'rubric',
    family: 'reflection',
    lessonKinds: ALL_KINDS,
    minLevel: 'A2',
    maxLevel: 'C1',
    skills: ['metacognition'],
    production: 'reflection',
    cognitiveLoad: 2,
    tags: ['reflection'],
    needs: ['successCriteria'],
  },
  {
    id: 'transfer-selfcheck',
    phase: 'transfer',
    blockType: 'selfcheck',
    family: 'reflection',
    lessonKinds: ALL_KINDS,
    minLevel: 'A1',
    maxLevel: 'C1',
    skills: ['metacognition'],
    production: 'reflection',
    cognitiveLoad: 1,
    tags: ['reflection'],
    needs: ['successCriteria'],
  },
];

export function activityById(id) {
  return ACTIVITY_CATALOG.find((item) => item.id === id) || null;
}

export function activitiesForPhase(phase) {
  return ACTIVITY_CATALOG.filter((item) => item.phase === phase);
}
